/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.devtools.mobileharness.shared.util.testresult.loader;

import static com.google.common.truth.Truth.assertThat;

import com.google.common.collect.ImmutableList;
import com.google.devtools.mobileharness.shared.util.file.local.LocalFileUtil;
import com.google.devtools.mobileharness.shared.util.path.PathUtil;
import com.google.wireless.qa.mobileharness.shared.model.job.JobInfo;
import com.google.wireless.qa.mobileharness.shared.model.job.JobLocator;
import com.google.wireless.qa.mobileharness.shared.model.job.JobSetting;
import com.google.wireless.qa.mobileharness.shared.model.job.TestInfo;
import com.google.wireless.qa.mobileharness.shared.proto.Job.JobType;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.Optional;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

/** Unit test for {@link JunitXmlResultLoader}. */
@RunWith(JUnit4.class)
public final class JunitXmlResultLoaderTest {

  /** A JUnit XML in the shape generated by the iOS XCTest UTP result processor. */
  private static final String IOS_JUNIT_XML =
      "<?xml version='1.0' encoding='UTF-8'?>\n"
          + "<testsuites>\n"
          + "  <testsuite name='' tests='2' failures='1' skipped='0' errors='0' time='15'>\n"
          + "    <testcase name='testCustomAction'"
          + " classname='EarlGreyExampleSwiftTests.EarlGreyExampleSwiftTests' time='10' />\n"
          + "    <testcase name='testLayout'"
          + " classname='EarlGreyExampleSwiftTests.EarlGreyExampleSwiftTests' time='4'>\n"
          + "      <failure message='assertion failed'>stack trace</failure>\n"
          + "    </testcase>\n"
          + "  </testsuite>\n"
          + "</testsuites>\n";

  @Rule public final TemporaryFolder tempFolder = new TemporaryFolder();

  private LocalFileUtil localFileUtil;
  private TestInfo testInfo;
  private JunitXmlResultLoader loader;

  @Before
  public void setUp() throws Exception {
    localFileUtil = new LocalFileUtil();
    JobInfo jobInfo =
        JobInfo.newBuilder()
            .setLocator(new JobLocator("job_id", "job_name"))
            .setType(JobType.newBuilder().setDriver("IosNativeXcTest").build())
            .setSetting(
                JobSetting.newBuilder()
                    .setGenFileDir(tempFolder.getRoot().getAbsolutePath())
                    .build())
            .build();
    testInfo = jobInfo.tests().add("test_name");
    loader = new JunitXmlResultLoader(localFileUtil);
  }

  @Test
  public void loadTestSuites_noXmlFile_returnsEmpty() throws Exception {
    assertThat(loader.loadTestSuites(testInfo)).isEmpty();
  }

  @Test
  public void loadTestSuites_junitXml_returnsParsedTestSuites() throws Exception {
    writeGenFile("junit.xml", IOS_JUNIT_XML);

    Optional<ImmutableList<JunitXmlTestSuite>> testSuites = loader.loadTestSuites(testInfo);

    assertThat(testSuites).isPresent();
    assertThat(testSuites.get()).hasSize(1);
    JunitXmlTestSuite testSuite = testSuites.get().get(0);
    assertThat(testSuite.testCases()).hasSize(2);
    assertThat(testSuite.testCases().get(0).name()).isEqualTo("testCustomAction");
    assertThat(testSuite.testCases().get(0).className())
        .isEqualTo("EarlGreyExampleSwiftTests.EarlGreyExampleSwiftTests");
    assertThat(testSuite.testCases().get(0).elapsedTime()).isEqualTo(Duration.ofSeconds(10));
    assertThat(testSuite.testCases().get(0).status()).isEqualTo(JunitXmlTestCase.Status.PASSED);
    assertThat(testSuite.testCases().get(1).status()).isEqualTo(JunitXmlTestCase.Status.FAILED);
    assertThat(testSuite.testCases().get(1).stackTrace()).hasValue("assertion failed\nstack trace");
  }

  @Test
  public void loadTestSuites_legacyTestResultXml_returnsParsedTestSuites() throws Exception {
    // Lab servers which have not picked up the rename to junit.xml yet (b/556567181).
    writeGenFile("test_result.xml", IOS_JUNIT_XML);

    Optional<ImmutableList<JunitXmlTestSuite>> testSuites = loader.loadTestSuites(testInfo);

    assertThat(testSuites).isPresent();
    assertThat(testSuites.get().get(0).testCases()).hasSize(2);
  }

  @Test
  public void loadTestSuites_junitXmlPreferredOverLegacyNames() throws Exception {
    writeGenFile("junit.xml", IOS_JUNIT_XML);
    writeGenFile(
        "test_result.xml",
        "<?xml version='1.0' encoding='UTF-8'?><testsuites><testsuite name='stale'/></testsuites>");

    Optional<ImmutableList<JunitXmlTestSuite>> testSuites = loader.loadTestSuites(testInfo);

    assertThat(testSuites).isPresent();
    assertThat(testSuites.get().get(0).testCases()).hasSize(2);
  }

  @Test
  public void loadTestSuites_malformedXml_returnsEmpty() throws Exception {
    writeGenFile("junit.xml", "not xml at all");

    assertThat(loader.loadTestSuites(testInfo)).isEmpty();
  }

  @Test
  public void loadTestSuites_nestedTestSuites_doesNotDoubleCountTestCases() throws Exception {
    writeGenFile(
        "junit.xml",
        "<?xml version='1.0' encoding='UTF-8'?>\n"
            + "<testsuites>\n"
            + "  <testsuite name='OuterSuite'>\n"
            + "    <testcase name='testOuter' classname='Target.OuterTest' time='1' />\n"
            + "    <testsuite name='InnerSuite'>\n"
            + "      <testcase name='testInner' classname='Target.InnerTest' time='2' />\n"
            + "    </testsuite>\n"
            + "  </testsuite>\n"
            + "</testsuites>\n");

    Optional<ImmutableList<JunitXmlTestSuite>> testSuites = loader.loadTestSuites(testInfo);

    assertThat(testSuites).isPresent();
    assertThat(testSuites.get()).hasSize(2);
    assertThat(testSuites.get().get(0).name()).isEqualTo("OuterSuite");
    assertThat(testSuites.get().get(0).testCases()).hasSize(1);
    assertThat(testSuites.get().get(0).testCases().get(0).name()).isEqualTo("testOuter");
    assertThat(testSuites.get().get(1).name()).isEqualTo("InnerSuite");
    assertThat(testSuites.get().get(1).testCases()).hasSize(1);
    assertThat(testSuites.get().get(1).testCases().get(0).name()).isEqualTo("testInner");
  }

  @Test
  public void loadTestSuites_errorAndSkippedElements_returnsExpectedStatusesAndStackTraces()
      throws Exception {
    writeGenFile(
        "junit.xml",
        "<?xml version='1.0' encoding='UTF-8'?>\n"
            + "<testsuite name='Suite'>\n"
            + "  <testcase name='testErrorNoMessage' classname='Target.Test' time='1'>\n"
            + "    <error>crash trace only</error>\n"
            + "  </testcase>\n"
            + "  <testcase name='testFailureMessageOnly' classname='Target.Test' time='1'>\n"
            + "    <failure message='assertion failed' />\n"
            + "  </testcase>\n"
            + "  <testcase name='testSkipped' classname='Target.Test' time='0'>\n"
            + "    <skipped />\n"
            + "  </testcase>\n"
            + "</testsuite>\n");

    Optional<ImmutableList<JunitXmlTestSuite>> testSuites = loader.loadTestSuites(testInfo);

    assertThat(testSuites).isPresent();
    ImmutableList<JunitXmlTestCase> cases = testSuites.get().get(0).testCases();
    assertThat(cases).hasSize(3);
    assertThat(cases.get(0).status()).isEqualTo(JunitXmlTestCase.Status.ERROR);
    assertThat(cases.get(0).stackTrace()).hasValue("crash trace only");
    assertThat(cases.get(1).status()).isEqualTo(JunitXmlTestCase.Status.FAILED);
    assertThat(cases.get(1).stackTrace()).hasValue("assertion failed");
    assertThat(cases.get(2).status()).isEqualTo(JunitXmlTestCase.Status.SKIPPED);
    assertThat(cases.get(2).stackTrace()).isEmpty();
  }

  @Test
  public void loadTestSuites_timeAttributeEdgeCases_returnsExpectedDurations() throws Exception {
    writeGenFile(
        "junit.xml",
        "<?xml version='1.0' encoding='UTF-8'?>\n"
            + "<testsuite name='Suite'>\n"
            + "  <testcase name='testFractional' classname='Target.Test' time='1.234' />\n"
            + "  <testcase name='testMissingTime' classname='Target.Test' />\n"
            + "  <testcase name='testMalformedTime' classname='Target.Test' time='invalid' />\n"
            + "</testsuite>\n");

    Optional<ImmutableList<JunitXmlTestSuite>> testSuites = loader.loadTestSuites(testInfo);

    assertThat(testSuites).isPresent();
    ImmutableList<JunitXmlTestCase> cases = testSuites.get().get(0).testCases();
    assertThat(cases).hasSize(3);
    assertThat(cases.get(0).elapsedTime()).isEqualTo(Duration.ofMillis(1234));
    assertThat(cases.get(1).elapsedTime()).isEqualTo(Duration.ZERO);
    assertThat(cases.get(2).elapsedTime()).isEqualTo(Duration.ZERO);
  }

  private void writeGenFile(String fileName, String content) throws Exception {
    localFileUtil.writeToFile(
        PathUtil.join(testInfo.getGenFileDir(), fileName),
        content.getBytes(StandardCharsets.UTF_8));
  }
}
