/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.devtools.mobileharness.platform.android.dropbox;

/** Enum class to to hold dropbox tag values. */
public enum DropboxTag {
  // Apps that are installed on the device.
  DATA_APP_ANR,
  DATA_APP_CRASH,
  DATA_APP_NATIVE_CRASH,
  // These are for system/preloaded OEM apps
  SYSTEM_APP_ANR,
  SYSTEM_APP_CRASH,
  SYSTEM_APP_NATIVE_CRASH,
  // System tombstones are generated by the OS when a native crash occurs
  SYSTEM_TOMBSTONE;

  @Override
  public String toString() {
    return switch (this) {
      case DATA_APP_ANR -> "data_app_anr";
      case DATA_APP_CRASH -> "data_app_crash";
      case DATA_APP_NATIVE_CRASH -> "data_app_native_crash";
      case SYSTEM_APP_ANR -> "system_app_anr";
      case SYSTEM_APP_CRASH -> "system_app_crash";
      case SYSTEM_APP_NATIVE_CRASH -> "system_app_native_crash";
      case SYSTEM_TOMBSTONE -> "SYSTEM_TOMBSTONE";
    };
  }
}
