# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Description:
#   Job file resolver constants.

package_group(
    name = "job_file_resolver_user",
    includes = [
        "//:deviceinfra_all_pkg",
    ],
)

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = [":job_file_resolver_user"],
)

java_library(
    name = "job_file_resolver_constants",
    srcs = ["JobFileResolverConstants.java"],
    deps = [],
)
