# proto-file: third_party/deviceinfra/src/java/com/google/wireless/qa/mobileharness/shared/proto/config.proto
# proto-message: mobileharness.shared.ApiConfig

composite_dimension {
  supported_dimension {
  }
}
