#include <M5Unified.h>
#include <Wire.h>
#include <Adafruit_PWMServoDriver.h>
#include <Preferences.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>

#include "./logo.h"

// ============================================================================
// RecoverBot Firmware
// Target: M5Stack Core3 (ESP32) + PCA9685 servo boards.
//
// What this firmware does (feature list)
// ----------------------------------------------------------------------------
// 1) Board auto-detection
//    - Scans I2C addresses 0x40 ~ 0x47 on Wire1 (Core3 Port A)
//    - For each detected PCA9685 board, initializes it at 50Hz servo frequency
//
// 2) Per-servo calibration (persisted in ESP32 NVS / Preferences)
//    - Each (boardAddr, channel) can have calibrated pressTick + releaseTick
//    - Stored as a packed uint32: (pressTick<<16) | releaseTick
//    - Key format: "c_<ADDR>_<CH>" e.g. "c_40_00"
//    - On boot: loads calibrations for all detected boards/channels
//    - On boot: sets every channel to its releaseTick (calibrated if present)
//
// 3) Safe "press then auto-release" servo actuation
//    - press_ms <boardHex> <ch> <ms>  : press for ms then auto-release
//    - press    <boardHex> <ch>       : press using max duration cap
//    - release  <boardHex> <ch>       : go to releaseTick immediately
//    - A safety cap FORCE_MAX_PRESS_MS prevents "stuck press" forever
//
// 4) RAW tick mode (guarded, timed unlock)
//    - raw on [sec]   : enable RAW mode for N seconds (default 300s)
//    - raw off        : disable RAW mode immediately
//    - raw_tick <boardHex> <ch> <tick>
//        Writes a tick value directly, but ONLY when RAW is enabled
//        AND tick is within [g_rawTickMin, g_rawTickMax] (configurable)
//    - RAW mode auto-locks after expiration
//
// 5) Serial command interface
//    - Type commands over Serial @115200
//    - "help" prints all available commands
//
// 6) Dual logging: Serial + on-device screen
//    - logMsg(...) prints the same line to Serial and the Core3 display
//    - Screen is cleared when switching from the idle logo back to logs
//
// 7) Idle logo screensaver (optional UI)
//    - If no "event" happens for IDLE_SHOW_LOGO_MS (default 30s),
//      the firmware shows the embedded PNG logo.
//    - While the logo is shown:
//        * Any new log line will automatically return to log screen
//        * A screen tap will return to log screen
//
// Notes / Assumptions
// ----------------------------------------------------------------------------
// - PCA9685 servo frequency is set to 50Hz.
// - "tick" means PCA9685 PWM OFF count [0..4095] within one 20ms period.
// - This firmware intentionally keeps UI simple (no scrollback buffer,
//   no timestamps on-screen, no gesture scroll).
//
// Dependencies (Arduino Library Manager)
// ----------------------------------------------------------------------------
// - M5Unified (by M5Stack)
// - Adafruit PWM Servo Driver Library (Adafruit_PWMServoDriver.h)
// - Adafruit BusIO (required by Adafruit PWM Servo Driver Library)
// ============================================================================


// Embedded logo data (from logo.h generated by build.sh)
// This makes sure the firmware always has the latest logo data.
#define LOGO_DATA logo_240_png
#define LOGO_LEN  logo_240_png_len

// PNG is 240x240.
static const int LOGO_W = 240;
static const int LOGO_H = 240;

// ===== Safety cap for forced press =====
const uint32_t FORCE_MAX_PRESS_MS = 100000UL;  // 100 seconds

// ===== RAW tick guard rails =====
static uint32_t g_rawUnlockWindowMs = 300000UL;  // default 5 minutes
static uint16_t g_rawTickMin        = 250;       // safe lower bound
static uint16_t g_rawTickMax        = 450;       // safe upper bound

bool     g_rawEnabled = false;
uint32_t g_rawExpire  = 0;   // 0 => no expiry

// ===== Default Servo PWM presets (ticks) =====
// If a channel has no saved calibration, these defaults are used.
const int POWER_SERVO_PRESS         = 360;
const int POWER_SERVO_RELEASE       = 300;
const int VOLUME_UP_SERVO_PRESS     = 360;
const int VOLUME_UP_SERVO_RELEASE   = 300;
const int VOLUME_DOWN_SERVO_PRESS   = 360;
const int VOLUME_DOWN_SERVO_RELEASE = 300;

const int MAX_CHANNELS = 16;
const int MAX_BOARDS   = 8;   // max boards 0x40..0x47

Adafruit_PWMServoDriver* pwmBoards[MAX_BOARDS];
uint8_t boardAddresses[MAX_BOARDS];
uint8_t numBoards = 0;

// Servo active state (for auto-release)
struct ServoState {
  bool     active = false;
  uint32_t releaseTime = 0;
};
ServoState servoStates[MAX_BOARDS][MAX_CHANNELS];

// Debug: last tick written (not required for functionality)
uint16_t lastTicks[MAX_BOARDS][MAX_CHANNELS];

// Per-servo calibration storage (in RAM)
// If g_cal[b][ch].has == true, press/release ticks override defaults.
struct CalEntry {
  bool     has = false;
  uint16_t pressTick = 0;
  uint16_t releaseTick = 0;
};
CalEntry g_cal[MAX_BOARDS][MAX_CHANNELS];

Preferences prefs;  // NVS namespace: "recoverbot"


// ---------------------------------------------------------
// Idle logo control (simple "screensaver")
// ---------------------------------------------------------
static const uint32_t IDLE_SHOW_LOGO_MS = 30000UL;
static uint32_t g_lastEventMs = 0;
static bool g_logoShown = false;

// Treat any interaction or servo action as an "event" to reset idle timer.
static inline void markEvent() {
  g_lastEventMs = millis();
}


// ---------------------------------------------------------
// UI helpers
// ---------------------------------------------------------
void showLogScreenHeader() {
  // Hard clear the screen to avoid any leftovers from PNG alpha blending
  M5.Display.fillScreen(TFT_BLACK);
  M5.Display.setCursor(0, 0);
  M5.Display.setTextColor(TFT_GREEN, TFT_BLACK);
  M5.Display.println("RecoverBot");
  M5.Display.setTextColor(TFT_WHITE, TFT_BLACK);
}

void showLogoScreen() {
  // Center the logo
  int x = (M5.Display.width()  - LOGO_W) / 2;
  int y = (M5.Display.height() - LOGO_H) / 2;
  if (x < 0) x = 0;
  if (y < 0) y = 0;

  // Clear entire screen first
  M5.Display.fillScreen(TFT_WHITE);

  // Also clear logo area in case PNG has transparent pixels
  M5.Display.fillRect(x, y, LOGO_W, LOGO_H, TFT_WHITE);

  // Draw PNG from embedded byte array
  M5.Display.drawPng(LOGO_DATA, LOGO_LEN, x, y);

  g_logoShown = true;
}

// Tap while logo shown => return to logs
void handleTouchToExitLogo() {
  if (!g_logoShown) return;

  int32_t x, y;
  if (M5.Display.getTouch(&x, &y)) {
    g_logoShown = false;
    markEvent();
    showLogScreenHeader();
    M5.Display.println("Back to logs (tap)");
  }
}


// ---------------------------------------------------------
// Logging: Serial + Screen (screen always stays coherent)
// ---------------------------------------------------------
void logMsg(const char* format, ...) {
  // If logo is currently shown, switch back to log screen first.
  // NOTE: Do this BEFORE markEvent() so we don't lose the state.
  if (g_logoShown) {
    g_logoShown = false;
    showLogScreenHeader();
  }

  markEvent();

  char buf[192];
  va_list args;
  va_start(args, format);
  vsnprintf(buf, sizeof(buf), format, args);
  va_end(args);

  Serial.println(buf);
  M5.Display.println(buf);
}


// ---------------------------------------------------------
// PCA9685 / servo helpers
// ---------------------------------------------------------
bool isPCA9685Present(uint8_t addr) {
  Wire1.beginTransmission(addr);
  return Wire1.endTransmission() == 0;
}

int getBoardIndex(uint8_t boardAddr) {
  for (int i = 0; i < (int)numBoards; ++i) {
    if (boardAddresses[i] == boardAddr) return i;
  }
  return -1;
}

bool isTickSafe(uint16_t t) {
  return (t >= g_rawTickMin && t <= g_rawTickMax);
}

void getDefaultPressRelease(uint8_t channel, int& pressPwm, int& releasePwm) {
  // Example mapping by channel%4
  if (channel % 4 == 0) {
    pressPwm = POWER_SERVO_PRESS;
    releasePwm = POWER_SERVO_RELEASE;
  } else if (channel % 4 == 1) {
    pressPwm = VOLUME_UP_SERVO_PRESS;
    releasePwm = VOLUME_UP_SERVO_RELEASE;
  } else if (channel % 4 == 2) {
    pressPwm = VOLUME_DOWN_SERVO_PRESS;
    releasePwm = VOLUME_DOWN_SERVO_RELEASE;
  } else {
    // reserved / fallback
    pressPwm = POWER_SERVO_PRESS;
    releasePwm = POWER_SERVO_RELEASE;
  }
}

void buildCalKey(char* out, size_t cap, uint8_t boardAddr, uint8_t ch) {
  // Key example: "c_40_00"
  snprintf(out, cap, "c_%02X_%02u", boardAddr, ch);
}


// ---------------------------------------------------------
// Calibration load/save (NVS)
// ---------------------------------------------------------
void loadOneCal(uint8_t boardAddr, uint8_t ch) {
  int b = getBoardIndex(boardAddr);
  if (b < 0 || ch >= MAX_CHANNELS) return;

  char key[16];
  buildCalKey(key, sizeof(key), boardAddr, ch);

  // Stored as uint32: (press<<16) | release. 0 => not set.
  uint32_t packed = prefs.getUInt(key, 0);
  if (packed == 0) {
    g_cal[b][ch].has = false;
    return;
  }

  uint16_t pressT = (uint16_t)(packed >> 16);
  uint16_t relT   = (uint16_t)(packed & 0xFFFF);

  // Reject out-of-policy data
  if (!isTickSafe(pressT) || !isTickSafe(relT)) {
    g_cal[b][ch].has = false;
    return;
  }

  g_cal[b][ch].has = true;
  g_cal[b][ch].pressTick = pressT;
  g_cal[b][ch].releaseTick = relT;
}

void loadAllCalForDetectedBoards() {
  for (int b = 0; b < (int)numBoards; ++b) {
    for (int ch = 0; ch < MAX_CHANNELS; ++ch) {
      loadOneCal(boardAddresses[b], static_cast<uint8_t>(ch));
    }
  }
}

void saveOneCal(uint8_t boardAddr, uint8_t ch, uint16_t pressT, uint16_t relT) {
  char key[16];
  buildCalKey(key, sizeof(key), boardAddr, ch);
  uint32_t packed = ((uint32_t)pressT << 16) | (uint32_t)relT;
  prefs.putUInt(key, packed);
}

void deleteOneCal(uint8_t boardAddr, uint8_t ch) {
  char key[16];
  buildCalKey(key, sizeof(key), boardAddr, ch);
  prefs.remove(key);

  int b = getBoardIndex(boardAddr);
  if (b >= 0 && ch < MAX_CHANNELS) g_cal[b][ch].has = false;
}

void getPressAndReleaseTicks(uint8_t boardAddr, uint8_t channel,
                             uint16_t& pressT, uint16_t& relT) {
  int b = getBoardIndex(boardAddr);
  if (b >= 0 && channel < MAX_CHANNELS && g_cal[b][channel].has) {
    pressT = g_cal[b][channel].pressTick;
    relT   = g_cal[b][channel].releaseTick;
    return;
  }

  int dp, dr;
  getDefaultPressRelease(channel, dp, dr);
  pressT = (uint16_t)dp;
  relT   = (uint16_t)dr;
}

void loadGlobalConfig() {
  g_rawUnlockWindowMs = prefs.getUInt("cfg_win", 300000UL);
  g_rawTickMin        = prefs.getUShort("cfg_min", 250);
  g_rawTickMax        = prefs.getUShort("cfg_max", 450);
}

void saveGlobalConfig() {
  prefs.putUInt("cfg_win", g_rawUnlockWindowMs);
  prefs.putUShort("cfg_min", g_rawTickMin);
  prefs.putUShort("cfg_max", g_rawTickMax);
}

void resetGlobalConfig() {
  prefs.remove("cfg_win");
  prefs.remove("cfg_min");
  prefs.remove("cfg_max");
  g_rawUnlockWindowMs = 300000UL;
  g_rawTickMin        = 250;
  g_rawTickMax        = 450;
}

// ---------------------------------------------------------
// Core servo actions
// ---------------------------------------------------------
void applyTicks(int boardIndex, uint8_t channel, uint16_t ticks) {
  pwmBoards[boardIndex]->setPWM(channel, 0, ticks);
  lastTicks[boardIndex][channel] = ticks;

  // Servo activity counts as an event (prevents idle logo during active usage)
  markEvent();
}

void releaseServo(uint8_t boardAddr, uint8_t channel) {
  if (channel >= MAX_CHANNELS) { logMsg("ERR: invalid channel"); return; }
  int index = getBoardIndex(boardAddr);
  if (index < 0) { logMsg("ERR: board not found"); return; }

  uint16_t pressT, relT;
  getPressAndReleaseTicks(boardAddr, channel, pressT, relT);

  applyTicks(index, channel, relT);
  servoStates[index][channel].active = false;

  logMsg("OK,RELEASE,0x%02X,ch=%u", boardAddr, channel);
}

void pressServo(uint8_t boardAddr, uint8_t channel, uint32_t duration) {
  if (channel >= MAX_CHANNELS) { logMsg("ERR: invalid channel"); return; }
  int index = getBoardIndex(boardAddr);
  if (index < 0) { logMsg("ERR: board not found"); return; }

  // Safety cap
  if (duration > FORCE_MAX_PRESS_MS) duration = FORCE_MAX_PRESS_MS;

  uint16_t pressT, relT;
  getPressAndReleaseTicks(boardAddr, channel, pressT, relT);

  applyTicks(index, channel, pressT);
  servoStates[index][channel].active = true;
  servoStates[index][channel].releaseTime = millis() + duration;

  logMsg("OK,PRESS,0x%02X,ch=%u,ms=%lu,tick=%u", boardAddr, channel,
         duration, pressT);
}

void checkAndReleaseServos() {
  uint32_t now = millis();
  for (int b = 0; b < (int)numBoards; ++b) {
    for (int c = 0; c < MAX_CHANNELS; ++c) {
      if (servoStates[b][c].active && now >= servoStates[b][c].releaseTime) {
        uint16_t pressT, relT;
        getPressAndReleaseTicks(boardAddresses[b], static_cast<uint8_t>(c),
                                pressT, relT);
        applyTicks(b, static_cast<uint8_t>(c), relT);
        servoStates[b][c].active = false;
        logMsg("AUTO_RELEASE,0x%02X,ch=%d", boardAddresses[b], c);
      }
    }
  }
}

void setRawTicks(uint8_t boardAddr, uint8_t channel, uint16_t ticks) {
  if (channel >= MAX_CHANNELS) { logMsg("ERR: invalid channel"); return; }
  int index = getBoardIndex(boardAddr);
  if (index < 0) { logMsg("ERR: board not found"); return; }

  // Auto-lock RAW if expired
  if (!g_rawEnabled || (g_rawExpire && millis() > g_rawExpire)) {
    g_rawEnabled = false;
    logMsg("ERR: raw disabled");
    return;
  }

  if (!isTickSafe(ticks)) {
    logMsg("ERR: raw tick out of range [%u,%u]", g_rawTickMin, g_rawTickMax);
    return;
  }

  applyTicks(index, channel, ticks);
  servoStates[index][channel].active = false;

  logMsg("OK,RAW_TICK,0x%02X,ch=%u,tick=%u", boardAddr, channel, ticks);
}


// ---------------------------------------------------------
// Status / Help
// ---------------------------------------------------------
void printStatus() {
  uint32_t now = millis();
  logMsg("=== Status ===");
  logMsg("Boards: %u", numBoards);
  logMsg("RAW Config: win=%lu ms, min=%u, max=%u",
         g_rawUnlockWindowMs, g_rawTickMin, g_rawTickMax);

  if (g_rawEnabled) {
    if (g_rawExpire) {
      int32_t remain = (int32_t)(g_rawExpire - now);
      logMsg("RAW: ON (expires in %d ms)", remain);
    } else {
      logMsg("RAW: ON (no expiry)");
    }
  } else {
    logMsg("RAW: OFF");
  }

  int activeCount = 0;
  for (int b = 0; b < (int)numBoards; ++b)
    for (int c = 0; c < MAX_CHANNELS; ++c)
      if (servoStates[b][c].active) activeCount++;

  logMsg("Active servos: %d", activeCount);
  for (int b = 0; b < (int)numBoards; ++b) {
    for (int c = 0; c < MAX_CHANNELS; ++c) {
      if (servoStates[b][c].active) {
        int32_t remain = (int32_t)(servoStates[b][c].releaseTime - now);
        logMsg(" - 0x%02X ch%d remaining=%d ms", boardAddresses[b], c,
               remain);
      }
    }
  }
  logMsg("=============");
}

void printHelp() {
  logMsg("=== Commands ===");
  logMsg("ping");
  logMsg("status");
  logMsg("help");
  logMsg("");
  logMsg("press_ms <boardHex> <ch> <ms>");
  logMsg("press    <boardHex> <ch>        (auto-release at 100s cap)");
  logMsg("release  <boardHex> <ch>");
  logMsg("");
  logMsg("cal_set   <boardHex> <ch> <pressTick> <releaseTick>   (ticks %u~%u)",
         g_rawTickMin, g_rawTickMax);
  logMsg("cal_get   <boardHex> <ch>");
  logMsg("cal_reset <boardHex> <ch>");
  logMsg("cal_list");
  logMsg("");
  logMsg("raw on [sec]   | raw off");
  logMsg("raw_tick <boardHex> <ch> <tick> (ticks %u~%u)", g_rawTickMin,
         g_rawTickMax);
  logMsg("");
  logMsg("cfg_set   <win|min|max> <val>");
  logMsg("cfg_get");
  logMsg("cfg_reset");
  logMsg("================");
}


// ---------------------------------------------------------
// Serial command parsing
// ---------------------------------------------------------
bool readLine(char* buf, size_t cap) {
  static size_t pos = 0;
  while (Serial.available()) {
    char c = Serial.read();
    if (c == '\r') continue;  // Windows friendly
    if (c == '\n') {
      buf[pos] = '\0';
      pos = 0;
      return true;
    }
    if (pos < cap - 1) buf[pos++] = c;
  }
  return false;
}

int tokenize(char* line, char* argv[], int maxArgv) {
  int argc = 0;
  char* saveptr;
  char* tok = strtok_r(line, " ", &saveptr);
  while (tok && argc < maxArgv) {
    argv[argc++] = tok;
    tok = strtok_r(NULL, " ", &saveptr);
  }
  return argc;
}


// ---------------------------------------------------------
// Command handlers
// ---------------------------------------------------------
void cmd_ping(int /*argc*/, char** /*argv*/) {
  logMsg("This is auto recovery controller");
}
void cmd_status(int /*argc*/, char** /*argv*/) { printStatus(); }
void cmd_help(int /*argc*/, char** /*argv*/) { printHelp(); }

void cmd_press_ms(int argc, char** argv) {
  if (argc < 4) { logMsg("ERR: press_ms <boardHex> <ch> <ms>"); return; }
  uint8_t board = static_cast<uint8_t>(strtoul(argv[1], nullptr, 16)); // NOLINT
  uint8_t ch = static_cast<uint8_t>(strtoul(argv[2], nullptr, 10)); // NOLINT
  uint32_t ms = static_cast<uint32_t>(strtoul(argv[3], nullptr, 10)); // NOLINT
  pressServo(board, ch, ms);
}

void cmd_press(int argc, char** argv) {
  if (argc < 3) { logMsg("ERR: press <boardHex> <ch>"); return; }
  uint8_t board = static_cast<uint8_t>(strtoul(argv[1], nullptr, 16)); // NOLINT
  uint8_t ch = static_cast<uint8_t>(strtoul(argv[2], nullptr, 10)); // NOLINT
  pressServo(board, ch, FORCE_MAX_PRESS_MS);
}

void cmd_release(int argc, char** argv) {
  if (argc < 3) { logMsg("ERR: release <boardHex> <ch>"); return; }
  uint8_t board = static_cast<uint8_t>(strtoul(argv[1], nullptr, 16)); // NOLINT
  uint8_t ch = static_cast<uint8_t>(strtoul(argv[2], nullptr, 10)); // NOLINT
  releaseServo(board, ch);
}

void cmd_raw_on(int argc, char** argv) {
  uint32_t sec = 0;
  if (argc >= 2) sec = strtoul(argv[1], nullptr, 10); // NOLINT
  if (sec == 0) sec = g_rawUnlockWindowMs / 1000;
  g_rawEnabled = true;
  g_rawExpire  = millis() + sec * 1000UL;
  logMsg("OK,RAW_ON,sec=%lu", sec);
}

void cmd_raw_off(int /*argc*/, char** /*argv*/) {
  g_rawEnabled = false;
  g_rawExpire = 0;
  logMsg("OK,RAW_OFF");
}

void cmd_raw_tick(int argc, char** argv) {
  if (argc < 4) { logMsg("ERR: raw_tick <boardHex> <ch> <tick>"); return; }
  uint8_t board = static_cast<uint8_t>(strtoul(argv[1], nullptr, 16)); // NOLINT
  uint8_t ch = static_cast<uint8_t>(strtoul(argv[2], nullptr, 10)); // NOLINT
  uint16_t tick = static_cast<uint16_t>(strtoul(argv[3], nullptr, 10)); // NOLINT
  setRawTicks(board, ch, tick);
}

void cmd_cal_set(int argc, char** argv) {
  if (argc < 5) {
    logMsg("ERR: cal_set <boardHex> <ch> <pressTick> <releaseTick>");
    return;
  }
  uint8_t board = static_cast<uint8_t>(strtoul(argv[1], nullptr, 16)); // NOLINT
  uint8_t ch = static_cast<uint8_t>(strtoul(argv[2], nullptr, 10)); // NOLINT
  uint16_t pressT = static_cast<uint16_t>(strtoul(argv[3], nullptr, 10)); // NOLINT
  uint16_t relT = static_cast<uint16_t>(strtoul(argv[4], nullptr, 10)); // NOLINT

  if (ch >= MAX_CHANNELS) { logMsg("ERR: invalid channel"); return; }
  if (!isTickSafe(pressT) || !isTickSafe(relT)) {
    logMsg("ERR: ticks must be in [%u,%u]", g_rawTickMin, g_rawTickMax);
    return;
  }

  int bi = getBoardIndex(board);
  if (bi < 0) { logMsg("ERR: board not found"); return; }

  g_cal[bi][ch].has = true;
  g_cal[bi][ch].pressTick = pressT;
  g_cal[bi][ch].releaseTick = relT;

  saveOneCal(board, ch, pressT, relT);
  logMsg("OK,CAL_SET,0x%02X,ch=%u,press=%u,release=%u", board, ch, pressT,
         relT);
}

void cmd_cal_get(int argc, char** argv) {
  if (argc < 3) { logMsg("ERR: cal_get <boardHex> <ch>"); return; }
  uint8_t board = static_cast<uint8_t>(strtoul(argv[1], nullptr, 16)); // NOLINT
  uint8_t ch = static_cast<uint8_t>(strtoul(argv[2], nullptr, 10)); // NOLINT
  if (ch >= MAX_CHANNELS) { logMsg("ERR: invalid channel"); return; }
  int bi = getBoardIndex(board);
  if (bi < 0) { logMsg("ERR: board not found"); return; }

  uint16_t pressT, relT;
  getPressAndReleaseTicks(board, ch, pressT, relT);

  logMsg("OK,CAL_GET,0x%02X,ch=%u,press=%u,release=%u,source=%s",
         board, ch, pressT, relT, g_cal[bi][ch].has ? "calibrated" : "default");
}

void cmd_cal_reset(int argc, char** argv) {
  if (argc < 3) { logMsg("ERR: cal_reset <boardHex> <ch>"); return; }
  uint8_t board = static_cast<uint8_t>(strtoul(argv[1], nullptr, 16)); // NOLINT
  uint8_t ch = static_cast<uint8_t>(strtoul(argv[2], nullptr, 10)); // NOLINT
  if (ch >= MAX_CHANNELS) { logMsg("ERR: invalid channel"); return; }
  int bi = getBoardIndex(board);
  if (bi < 0) { logMsg("ERR: board not found"); return; }

  deleteOneCal(board, ch);
  logMsg("OK,CAL_RESET,0x%02X,ch=%u", board, ch);
}

void cmd_cal_list(int /*argc*/, char** /*argv*/) {
  logMsg("==================================");
  logMsg("=== CAL LIST (calibrated only) ===");
  for (int b = 0; b < (int)numBoards; ++b) {
    for (int ch = 0; ch < MAX_CHANNELS; ++ch) {
      if (g_cal[b][ch].has) {
        logMsg("0x%02X,ch=%d,press=%u,release=%u", boardAddresses[b], ch,
               g_cal[b][ch].pressTick, g_cal[b][ch].releaseTick);
      }
    }
  }
  logMsg("==================================");
}

void cmd_cfg_set(int argc, char** argv) {
  if (argc < 3) { logMsg("ERR: cfg_set <win|min|max> <val>"); return; }
  uint32_t val = strtoul(argv[2], nullptr, 10); // NOLINT
  if (strcmp(argv[1], "win") == 0) {
    g_rawUnlockWindowMs = val * 1000UL;
  } else if (strcmp(argv[1], "min") == 0) {
    g_rawTickMin = (uint16_t)val;
  } else if (strcmp(argv[1], "max") == 0) {
    g_rawTickMax = (uint16_t)val;
  } else {
    logMsg("ERR: unknown key"); return;
  }
  saveGlobalConfig();
  logMsg("OK,CFG_SET,%s=%lu", argv[1], val);
}

void cmd_cfg_get(int /*argc*/, char** /*argv*/) {
  logMsg("=== Config ===");
  logMsg("win: %lu ms", g_rawUnlockWindowMs);
  logMsg("min: %u", g_rawTickMin);
  logMsg("max: %u", g_rawTickMax);
}

void cmd_cfg_reset(int /*argc*/, char** /*argv*/) {
  resetGlobalConfig();
  logMsg("OK,CFG_RESET");
}

// Command table
struct Cmd { const char* name; void (*fn)(int, char**); };

const Cmd g_cmds[] = {
  { "ping",      cmd_ping      },
  { "status",    cmd_status    },
  { "help",      cmd_help      },
  { "press_ms",  cmd_press_ms  },
  { "press",     cmd_press     },
  { "release",   cmd_release   },
  { "raw_tick",  cmd_raw_tick  },
  { "raw_on",    cmd_raw_on    },
  { "raw_off",   cmd_raw_off   },
  { "cal_set",   cmd_cal_set   },
  { "cal_get",   cmd_cal_get   },
  { "cal_reset", cmd_cal_reset },
  { "cal_list",  cmd_cal_list  },
  { "cfg_set",   cmd_cfg_set   },
  { "cfg_get",   cmd_cfg_get   },
  { "cfg_reset", cmd_cfg_reset },
};
const size_t g_cmdCount = sizeof(g_cmds) / sizeof(g_cmds[0]);

void dispatchCommand(char* line) {
  // Auto-lock RAW if expired
  if (g_rawEnabled && g_rawExpire && millis() > g_rawExpire) {
    g_rawEnabled = false;
  }

  char* argv[12];
  int argc = tokenize(line, argv, 12);
  if (!argc) return;

  // Any command input is an event
  markEvent();

  // Allow "raw on/off" form (user convenience)
  if (strcmp(argv[0], "raw") == 0) {
    if (argc >= 2 && strcmp(argv[1], "on") == 0) {
      if (argc >= 3) {
        char* fakeArgv[2] = { (char*)"raw_on", argv[2] };
        cmd_raw_on(2, fakeArgv);
      } else {
        char* fakeArgv[1] = { (char*)"raw_on" };
        cmd_raw_on(1, fakeArgv);
      }
      return;
    } else if (argc >= 2 && strcmp(argv[1], "off") == 0) {
      cmd_raw_off(0, nullptr);
      return;
    } else {
      logMsg("ERR: raw [on [sec] | off]");
      return;
    }
  }

  // Lookup normal commands
  for (size_t i = 0; i < g_cmdCount; ++i) {
    if (strcmp(argv[0], g_cmds[i].name) == 0) {
      g_cmds[i].fn(argc, argv);
      return;
    }
  }

  logMsg("ERR: unknown cmd: %s", argv[0]);
}


// ---------------------------------------------------------
// Arduino setup/loop (Core3)
// ---------------------------------------------------------
void setup() {
  auto cfg = M5.config();
  M5.begin(cfg);  // Core3 power management / screen init
  M5.Display.setRotation(1);
  M5.Display.setTextSize(1);

  Serial.begin(115200);
  delay(200);

  // Initialize idle timer baseline
  g_lastEventMs = millis();
  g_logoShown = false;

  showLogScreenHeader();
  M5.Display.println("RecoverBot booting...");

  // Core3 Port A I2C: SDA=2, SCL=1
  Wire1.begin(2, 1, 100000);
  delay(500);

  // Open NVS namespace
  prefs.begin("recoverbot", false);

  // Detect PCA9685 boards on Wire1
  for (uint8_t addr = 0x40; addr <= 0x47 && numBoards < MAX_BOARDS; ++addr) {
    if (!isPCA9685Present(addr)) continue;

    uint8_t idx = numBoards;

    // Adafruit library expects TwoWire& (reference), NOT pointer
    pwmBoards[idx] = new Adafruit_PWMServoDriver(addr, Wire1);
    boardAddresses[idx] = addr;

    // Init arrays for this board
    for (int c = 0; c < MAX_CHANNELS; ++c) {
      servoStates[idx][c].active = false;
      servoStates[idx][c].releaseTime = 0;
      lastTicks[idx][c] = 0;
      g_cal[idx][c].has = false;
    }

    // Increment numBoards BEFORE loading calibration
    numBoards++;

    pwmBoards[idx]->begin();
    pwmBoards[idx]->setPWMFreq(50);

    logMsg("Found Board: 0x%02X", addr);
  }

  if (numBoards == 0) {
    M5.Display.setTextColor(RED, TFT_BLACK);
    logMsg("ERROR: No PCA9685 boards detected on Wire1 (Port A)!");
    return;
  }

  // Load global configuration
  loadGlobalConfig();

  // Load calibration for detected boards
  loadAllCalForDetectedBoards();

  // Set all channels to RELEASE position (calibrated if exists else default)
  for (int b = 0; b < (int)numBoards; ++b) {
    for (int ch = 0; ch < MAX_CHANNELS; ++ch) {
      uint16_t pressT, relT;
      getPressAndReleaseTicks(boardAddresses[b], static_cast<uint8_t>(ch),
                                pressT, relT);
      applyTicks(b, static_cast<uint8_t>(ch), relT);
    }
  }

  M5.Display.setTextColor(TFT_GREEN, TFT_BLACK);
  logMsg("System Ready. Boards=%u. Type 'help'.", numBoards);
}

void loop() {
  M5.update();

  // Tap screen to exit logo (only active while logo is shown)
  handleTouchToExitLogo();

  // Serial command input (one line per command)
  static char line[180];
  if (readLine(line, sizeof(line))) {
    dispatchCommand(line);
  }

  // Periodic release checks (auto-release when time is up)
  checkAndReleaseServos();

  // Idle => show logo once and keep it until an event occurs (or tap)
  uint32_t now = millis();
  if (!g_logoShown && (now - g_lastEventMs) >= IDLE_SHOW_LOGO_MS) {
    showLogoScreen();
  }

  delay(1);
}
