/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.devtools.mobileharness.platform.testbed.mobly;

/** Values shared across Mobly related tasks. */
public final class MoblyConstant {

  /** Private constructor to prevent instatiation. */
  private MoblyConstant() {}

  /** Mobly test-generated output files/paths. */
  public static final class TestGenOutput {
    /**
     * The name of a sub-directory of the Mobile Harness genfiles, where files generated by a Mobly
     * test are written.
     */
    public static final String MOBLY_LOG_DIR = "mobly_logs";

    /** The Mobly result summary filename. */
    public static final String SUMMARY_FILE_NAME = "test_summary.yaml";

    /**
     * Config file name that is generated by {@link
     * com.google.wireless.qa.mobileharness.shared.api.driver.MoblyTest} and passed to Mobly.
     */
    public static final String CONFIG_FILE = "config.yaml";

    private TestGenOutput() {}
  }

  /** Constants for {@link TestInfo} {@link Properties} used in Mobly+MH integration. */
  public static final class TestProperty {
    /** Key for property where the value is the Mobly test class name. */
    public static final String MOBLY_TEST_CLASS_KEY = "mobly_test_class";

    /** Key for property designating a Mobile Harness TestInfo object as a Mobly test case. */
    public static final String TEST_TYPE_KEY = "test_type";

    /** Value for property designating a Mobile Harness TestInfo object as a Mobly test case. */
    public static final String MOBLY_TEST_VALUE = "mobly_test";

    /** Value for property designating a Mobile Harness TestInfo object as a Mobly test class. */
    public static final String MOBLY_TEST_CLASS_VALUE = "mobly_class";

    /** Key for property designating the reason for why a Mobly test was skipped. */
    public static final String SKIP_REASON_KEY = "skip_reason";

    /** Key for property designating the test's Unique Identifier (UID) specified by user. */
    public static final String MOBLY_UID_KEY = "mobly_uid";

    /** Key for property designating the Mobly test retry parent. */
    public static final String MOBLY_RETRY_PARENT_KEY = "mobly_retry_parent";

    /** Key for property designating the Mobly generated test signature. */
    public static final String MOBLY_SIGNATURE_KEY = "mobly_signature";

    /** Key for property designating Mobly test start time. */
    public static final String MOBLY_BEGIN_TIME_KEY = "mobly_begin_time";

    /** Key for property designating Mobly test end time. */
    public static final String MOBLY_END_TIME_KEY = "mobly_end_time";

    /** Key for property designating a stack trace produced by a Mobly test case. */
    public static final String MOBLY_STACK_TRACE_KEY = "mobly_stack_trace";

    /** Key for property designating an error/failure message from a test case. */
    public static final String MOBLY_ERROR_MESSAGE_KEY = "mobly_error_message";

    /** Key for property designating an test fission link for a test case. */
    public static final String MOBLY_TEST_FISSION = "test_fission";

    private TestProperty() {}
  }

  /** String keys for parsing user-added data in Mobly test summaries, to surfaced to Sponge. */
  public static final class UserDataKey {
    /** Key for user data where value is the collection of Sponge properties to add. */
    public static final String SPONGE = "sponge_properties";

    /** Key for user data where value is the test class name to match. */
    public static final String TEST_CLASS = "Test Class";

    /** Key for user data where value is the test case name to match. */
    public static final String TEST_NAME = "Test Name";

    private UserDataKey() {}
  }

  /**
   * Testbed config key names in the JSON file **created by** {@link MoblyTest}, which is passed to
   * the Mobly .par file for execution.
   */
  public static final class ConfigKey {
    /** Config key for parameters generated by {@link MoblyTest} consumed by Mobly. */
    public static final String MOBLY_PARAMS = "MoblyParams";

    /** Config key for the array of testbeds. */
    public static final String TESTBEDS = "TestBeds";

    /** Config key for the name of the testbed instance. */
    public static final String TESTBED_NAME = "Name";

    /** Config key for the configs of the controllers in a testbed. */
    public static final String TESTBED_CONTROLLERS = "Controllers";

    /** Config key for the test parameters map. */
    public static final String TEST_PARAMS = "TestParams";

    /** Config key within TestParams that contains actual user. */
    public static final String TEST_PARAM_ACTUAL_USER = "actual_user";

    /** Config key within TestParams that contains the map of files fetched by Mobile Harness. */
    public static final String TEST_PARAM_MH_FILES = "mh_files";

    /** Config key within TestParams that contains the map of Mobile Harness dimension. */
    public static final String TEST_PARAM_MH_DIMENSIONS = "mh_dimensions";

    /**
     * Config key within TestParams that contains the map of Mobile Harness {@link
     * com.google.wireless.qa.mobileharness.shared.model.job.TestInfo#properties() TestInfo
     * properties}.
     *
     * <p>These properties relate to an individual Mobile Harness "test" which is part of a "job."
     * Properties of its parent "job" (which can have many child tests) are stored in the {@link
     * TESTS_PARAM_MH_JOB_PROPERTIES}.
     */
    public static final String TESTS_PARAM_MH_TEST_PROPERTIES = "mh_test_properties";

    /**
     * Config key within TestParams that contains the map of Mobile Harness {@link
     * com.google.wireless.qa.mobileharness.shared.model.job.JobInfo#properties() JobInfo
     * properties}.
     *
     * <p>These properties relate to a Mobile Harness "job" which can have many individual tests.
     * Properties of specific test cases are stored in the {@link TESTS_PARAM_MH_TEST_PROPERTIES}.
     */
    public static final String TESTS_PARAM_MH_JOB_PROPERTIES = "mh_job_properties";

    /**
     * Config key within TestParams that contains a url string for the sponge invocation (e.g.,
     * http://sponge/1a2b3c4d5e6f7g8h9i0).
     */
    public static final String TEST_PARAM_MH_SPONGE_LINK = "mh_sponge_link";

    /**
     * Config key within a controller config that contains the user-defined label of the device --
     * used by {@link
     * com.google.wireless.qa.mobileharness.shared.api.decorator.MoblyDecoratorAdapter}
     */
    public static final String SUBDEVICE_LABEL = "label";

    /**
     * Config key for either testbed level dimensions or subdevice dimensions; in both cases these
     * are propagated up into the respective Mobile Harness representation
     */
    public static final String MOBILE_HARNESS_DIMENSIONS = "dimensions";

    private ConfigKey() {}
  }

  // Miscellaneous other shared constants:

  /** Prefix for all valid Mobly testcases. */
  public static final String MOBLY_TESTCASE_PREFIX = "test";
}
