/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.devtools.mobileharness.api.model.error;

import com.google.common.base.Preconditions;
import com.google.devtools.common.metrics.stability.model.proto.ErrorTypeProto.ErrorType;
import com.google.devtools.common.metrics.stability.util.ErrorIdFormatter;

/**
 * Error IDs for Mobile Harness Android platform supports, or Android related Driver/Decorator,
 * Detector/Device implementations.
 *
 * @see <a href="http://go/mh-exception">MH Exception</a> for more detail and guidance
 */
public enum AndroidErrorId implements ErrorId {
  // ***********************************************************************************************
  // Standard Android Platforms: 100_001 ~ 170_000
  // ***********************************************************************************************

  /** Android Low Level Utils: 100_001 ~ 110_000 */

  // ActivityManager: 100_001 ~ 100_020
  ANDROID_AM_PARSE_LOCALE_ERROR(100_001, ErrorType.INFRA_ISSUE),
  ANDROID_AM_GET_LOCALE_ERROR(100_002, ErrorType.DEPENDENCY_ISSUE),

  // AndroidSystemSettingUtil: 100_021 ~ 100_120
  ANDROID_SYSTEM_SETTING_ERROR(100_021, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_TIMEOUT(100_022, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_ENABLE_GPS_ERROR(100_023, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_ENABLE_NETWORK_LOCATION_ERROR(100_024, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_CHECK_LOCATION_SERVICE_ERROR(100_025, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_DEVICE_PROPERTY_ERROR(100_026, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_DEVICE_SDK_ERROR(100_027, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_DEVICE_VERSION_CODE_NAME_ERROR(100_028, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_PACKAGE_STORAGE_MODE_ERROR(100_029, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_SET_PACKAGE_STORAGE_MODE_ERROR(100_030, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_ISOLATED_STORAGE_MODE_ERROR(100_031, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_CLEAR_GSERVICE_OVERRIDE_ERROR(100_032, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_GSERVICE_ANDROID_ID_ERROR(100_033, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_PARSE_SYSTEM_TIME_ERROR(100_034, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_DISABLE_AIRPLANE_MODE_ERROR(100_035, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_PARSE_AIRPLANE_MODE_ERROR(100_036, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_BROADCAST_AIRPLANE_MODE_ERROR(100_037, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_BATTERY_LEVEL_ERROR(100_038, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_BATTERY_TEMP_ERROR(100_039, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_BATTERY_STATS_ERROR(100_040, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_CPU_USAGE_ERROR(100_041, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_BATTERY_STATE_CMD_ERROR(100_042, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_SET_BATTERY_DISCHARGE_ERROR(100_043, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_SYSTEM_TIME_ERROR(100_044, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_EPOCH_SYSTEM_TIME_ERROR(100_045, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_ALLOW_MOCK_LOCATION_ERROR(100_046, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_DISABLE_SCREENLOCK_ERROR(100_047, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_DISMISS_KEYGUARD_ERROR(100_048, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_ENABLE_UNKNOWN_SOURCES_ERROR(100_049, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_PARSE_RESOLUTION_ERROR(100_050, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_SYSTEM_SETTING_SET_MOCK_LOCATION_PROVIDER_ERROR(100_051, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_SET_DEX_PRE_VERIFICATION_ERROR(100_052, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_SET_VERITY_ERROR(100_053, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_TIME_ZONE_OFFSET_ERROR(100_054, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_SET_SYSTEM_TIME_ERROR(100_055, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_INVALID_DENSITY_VALUE(100_056, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_SYSTEM_SETTING_KEEP_AWAKE_ERROR(100_057, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_SCREEN_DENSITY_PROP_ERROR(100_058, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_DUMPSYS_WINDOW_ERROR(100_059, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_BUILD_PROP_ERROR(100_060, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_SET_LOG_LEVEL_PROP_ERROR(100_061, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_SQLITE_CMD_ERROR(100_062, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_FORCE_USB2ADB_MODE_ERROR(100_063, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_DEVICE_INT_PROPERTY_ERROR(100_064, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_GET_PACKAGE_OP_MODE_ERROR(100_065, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SETTING_SET_PACKAGE_OP_MODE_ERROR(100_066, ErrorType.INFRA_ISSUE),

  // AndroidConnectivityUtil: 100_121 ~ 100_220
  ANDROID_CONNECTIVITY_FAIL_CONNECT_TO_WIFI(100_121, ErrorType.UNDETERMINED),
  ANDROID_CONNECTIVITY_ENABLE_WIFI_VIA_WIFIUTIL_ERROR(100_122, ErrorType.INFRA_ISSUE),
  ANDROID_CONNECTIVITY_ENABLE_WIFI_ERROR(100_123, ErrorType.INFRA_ISSUE),
  ANDROID_CONNECTIVITY_GET_NET_STATUS_ERROR(100_124, ErrorType.INFRA_ISSUE),
  ANDROID_CONNECTIVITY_GET_SAVED_SSIDS_PSKS_ERROR(100_125, ErrorType.INFRA_ISSUE),
  ANDROID_CONNECTIVITY_DISABLE_WIFI_ERROR(100_126, ErrorType.INFRA_ISSUE),
  ANDROID_CONNECTIVITY_DISABLE_WIFI_VIA_WIFIUTIL_ERROR(100_127, ErrorType.INFRA_ISSUE),
  ANDROID_CONNECTIVITY_SET_NFC_ERROR(100_128, ErrorType.INFRA_ISSUE),
  ANDROID_CONNECTIVITY_SDK_VERSION_NOT_SUPPORT(100_129, ErrorType.DEPENDENCY_ISSUE),

  // AndroidDexDump: 100_221 ~ 100_300
  ANDROID_DEXDUMP_ERROR(100_221, ErrorType.INFRA_ISSUE),

  // AndroidInstrumentationUtil: 100_301 ~ 100_350
  ANDROID_INSTRUMENTATION_COMMAND_EXEC_FAILED(100_301, ErrorType.UNDETERMINED),
  ANDROID_INSTRUMENTATION_COMMAND_EXEC_TIMEOUT(100_302, ErrorType.UNDETERMINED),
  ANDROID_INSTRUMENTATION_COMMAND_START_ERROR(100_303, ErrorType.UNDETERMINED),
  ANDROID_INSTRUMENTATION_CONTENT_QUERY_ERROR(100_304, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_CONTENT_WRITE_ERROR(100_305, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_CONTENT_READ_ERROR(100_306, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_CONTENT_READ_FOLDER_ERROR(100_307, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_PUSH_TEST_DATA_ERROR(100_308, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_PROCESS_TEST_PROPERTY_ERROR(100_309, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_PROCESS_TEST_OUTPUT_ERROR(100_310, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_PREPARE_TEST_ARGS_ERROR(100_311, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_PULL_TEST_PROPERTY_ERROR(100_312, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_LIST_INSTRUMENTATION_ERROR(100_313, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_RUNNER_NOT_FOUND_FOR_PKG(100_314, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_INSTRUMENTATION_GET_ONLINE_DEVICES_ERROR(100_315, ErrorType.INFRA_ISSUE),

  // Android fastboot: 100_351 ~ 100_450
  ANDROID_FASTBOOT_UPDATE_MISSING_IMG_ZIP_FILE(100_351, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FASTBOOT_DEVICE_TYPE_NOT_MATCH_ERROR(100_352, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FASTBOOT_UNEXPECTED_IMG_FILE(100_353, ErrorType.INFRA_ISSUE),
  ANDROID_FASTBOOT_UNKNOWN_SLOT(100_354, ErrorType.INFRA_ISSUE),
  ANDROID_FASTBOOT_FLASH_PARTITION_ERROR(100_355, ErrorType.INFRA_ISSUE),
  ANDROID_FASTBOOT_UPDATE_COMMAND_EXEC_ERROR(100_356, ErrorType.INFRA_ISSUE),
  ANDROID_FASTBOOT_DEVICE_LIST_OUTPUT_FORMAT_ERROR(100_357, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_FASTBOOT_UNKNOWN_DEVICE_TYPE(100_358, ErrorType.INFRA_ISSUE),
  ANDROID_FASTBOOT_COMMAND_EXEC_ERROR(100_359, ErrorType.UNDETERMINED),
  ANDROID_FASTBOOT_MISSING_FASTBOOT_BINARY_ERROR(100_360, ErrorType.INFRA_ISSUE),

  // AndroidSystemStateUtil: 100_451 ~ 100_650
  ANDROID_SYSTEM_STATE_FACTORY_RESET_VIA_TEST_HARNESS_ERROR(100_451, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_STATE_BROADCAST_DEVICE_IS_READY_ERROR(100_452, ErrorType.UNDETERMINED),
  ANDROID_SYSTEM_STATE_STOP_ZYGOTE_PROCESS_ERROR(100_453, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_STATE_START_ZYGOTE_PROCESS_ERROR(100_454, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_STATE_DEVICE_NOT_ONLINE_READY(100_455, ErrorType.UNDETERMINED),
  ANDROID_SYSTEM_STATE_FACTORY_RESET_VIA_BROADCAST_ERROR(100_456, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_STATE_REBOOT_ERROR(100_457, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_STATE_REBOOT_TO_BOOTLOADER_ERROR(100_458, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_STATE_REBOOT_TO_RECOVERY_ERROR(100_459, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_STATE_UNROOT_DEVICE_ERROR(100_460, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_STATE_ROOT_DEVICE_ERROR(100_461, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_STATE_WAIT_FOR_DEVICE_CMD_ERROR(100_462, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_STATE_CHECK_DEVICE_ONLINE_BROKEN_PIPE_ERROR(100_463, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_SYSTEM_STATE_FACTORY_RESET_VIA_TEST_HARNESS_SCREEN_LOCKED_ERROR(
      100_464, ErrorType.CUSTOMER_ISSUE),

  // AndroidAdbUtil: 100_651 ~ 100_850
  ANDROID_ADB_UTIL_GET_DEVICE_PROPERTY_ERROR(100_651, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_DUMPSYS_ERROR(100_652, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_CMD_ERROR(100_653, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_CLEAR_LOG_ERROR(100_654, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_ADB_UTIL_GET_TIME_FOR_LOGCAT_ERROR(100_655, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_DUMP_LOG_ERROR(100_656, ErrorType.UNDETERMINED),
  ANDROID_ADB_UTIL_DUMP_LOG_ASYNC_ERROR(100_657, ErrorType.UNDETERMINED),
  ANDROID_ADB_UTIL_SDK_NOT_SUPPORT(100_658, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_ADB_UTIL_SET_LOGCAT_BUFFER_SIZE_ERROR(100_659, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_TIMEOUT(100_660, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_CHECK_ROOT_ERROR(100_661, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_SETTINGS_CMD_ERROR(100_666, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_BUGREPORT_ERROR(100_667, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_FIND_BUGREPORT_DIR_ERROR(100_668, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_SET_DEVICE_PROPERTY_ERROR(100_669, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_KEY_EVENT_ERROR(100_670, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_BROADCAST_ERROR(100_671, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_BROADCAST_EMPTY_INTENT_ARG(100_672, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_SQLITE_ERROR(100_673, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_CONTENT_ERROR(100_674, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_SVC_CMD_ERROR(100_675, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_FORWARD_TCP_PORT_ERROR(100_676, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_REMOVE_ALL_REVERSE_TCP_PORTS_ERROR(100_677, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_REMOVE_FORWARD_PORT_ERROR(100_678, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_REVERSE_TCP_PORT_ERROR(100_679, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_UTIL_WAIT_FOR_SIGNAL_IN_LOG_ERROR(100_680, ErrorType.INFRA_ISSUE),

  // Android File Util: 100_851 ~ 101_000
  ANDROID_FILE_UTIL_LIST_FILE_ERROR(100_851, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_PULL_FILE_ERROR(100_852, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_PUSH_FILE_ADB_ERROR(100_853, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_PUSH_FILE_LOCAL_FILE_ERROR(100_854, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_MAKE_DIRECTORY_ERROR(100_855, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_REMOVE_FILE_ERROR(100_856, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_RENAME_FILE_ERROR(100_857, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_GET_DISK_INFO_ERROR(100_858, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_GET_INTERNAL_STORAGE_INFO_ERROR(100_859, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_INVALID_DISK_INFO(100_860, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_FILE_UTIL_INVALID_INTERNAL_STORAGE_INFO(100_861, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_FILE_UTIL_CHECK_FILE_OR_DIR_EXIST_ERROR(100_862, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_MAKE_FILE_EXECUTABLE_ERROR(100_863, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_SDK_VERSION_NOT_SUPPORT(100_864, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_FILE_UTIL_GET_FILE_MD5_ERROR(100_865, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_INVALID_MD5_OUTPUT(100_866, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_FILE_UTIL_REMOUNT_ERROR(100_867, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_EXTERNAL_STORAGE_NOT_FOUND(100_868, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_FILE_UTIL_GET_EXTERNAL_STORAGE_ERROR(100_869, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_ILLEGAL_ARGUMENT(100_870, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FILE_PERMISSIONS_ILLEGAL_ARGUMENT(100_871, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_REMOVE_FILE_INVALID_ARGUMENT(100_872, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FILE_UTIL_CAT_FILE_EXE_ERROR(100_873, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_CAT_FILE_PARSER_ERROR(100_874, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_NO_SPACE_TO_MAKE_DIRECTORY_ERROR_IN_SHARED_LAB(100_875, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_NO_SPACE_TO_MAKE_DIRECTORY_ERROR_IN_SATELLITE_LAB(
      100_876, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_UTIL_CREATE_SYMLINK_ERROR(100_877, ErrorType.INFRA_ISSUE),

  // AndroidSystemSpecUtil: 101_001 ~ 101_200
  ANDROID_SYSTEM_SPEC_USB_LOCATOR_ADB_INVALID_LINE(101_001, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_SYSTEM_SPEC_USB_LOCATOR_SERIAL_NOT_FOUND(101_002, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SPEC_USB_LOCATOR_INVALID_USB_ID(101_003, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_SYSTEM_SPEC_INVALID_ABI(101_004, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_SYSTEM_SPEC_GET_IMEI_ERROR(101_005, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SPEC_GET_MAC_ADDRESS_ERROR(101_006, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SPEC_GET_CPU_INFO_ERROR(101_007, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SPEC_NO_CPU_FOUND(101_008, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_SYSTEM_SPEC_LIST_FEATURES_ERROR(101_009, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SPEC_GET_TOTAL_MEM_ERROR(101_010, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SPEC_INVALID_TOTAL_MEM_VALUE(101_011, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_SYSTEM_SPEC_TOTAL_MEM_VALUE_NOT_FOUND(101_012, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_SYSTEM_SPEC_GET_ICCID_ERROR(101_013, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_SPEC_GET_BLUETOOTH_MAC_ADDRESS_ERROR(101_014, ErrorType.INFRA_ISSUE),

  // UsbUtil: 101_201 ~ 101_300
  ANDROID_USB_UTIL_RESET_USB_ERROR(101_201, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_USB_UTIL_COMMAND_EXEC_ERROR(101_202, ErrorType.INFRA_ISSUE),

  // AndroidPackageManagerUtil: 101_301 ~ 101_600
  ANDROID_PKG_MNGR_UTIL_CLEAR_PACKAGE_ERROR(101_301, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_PKG_MNGR_UTIL_DISABLE_PACKAGE_ERROR(101_302, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_PKG_MNGR_UTIL_DUMPSYS_ERROR(101_303, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_PKG_MNGR_UTIL_INVALID_VERSION(101_304, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_PKG_MNGR_UTIL_GET_VERSION_INFO_ERROR(101_305, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_PKG_MNGR_UTIL_GET_INSTALLED_APK_PATH_ERROR(101_306, ErrorType.INFRA_ISSUE),
  ANDROID_PKG_MNGR_UTIL_PM_PATH_NO_PACKAGE_FOUND(101_307, ErrorType.INFRA_ISSUE),
  ANDROID_PKG_MNGR_UTIL_GRANT_PERMISSION_ERROR(101_308, ErrorType.INFRA_ISSUE),
  ANDROID_PKG_MNGR_UTIL_GET_PACKAGE_NAME_ERROR(101_309, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_PKG_MNGR_UTIL_INSTALLATION_APP_BLACKLISTED(101_310, ErrorType.CUSTOMER_ISSUE),
  /**
   * @deprecated Please use ANDROID_PKG_MNGR_UTIL_INSTALLATION_ERROR_IN_SHARED_LAB or
   *     ANDROID_PKG_MNGR_UTIL_INSTALLATION_ERROR_IN_SATELLITE_LAB
   */
  @Deprecated
  ANDROID_PKG_MNGR_UTIL_INSTALLATION_ERROR(101_311, ErrorType.UNDETERMINED),
  ANDROID_PKG_MNGR_UTIL_INSTALLATION_ABI_INCOMPATIBLE(101_312, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PKG_MNGR_UTIL_INSTALLATION_MISSING_SHARED_LIBRARY(101_313, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_PKG_MNGR_UTIL_INSTALLATION_UPDATE_INCOMPATIBLE(101_314, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PKG_MNGR_UTIL_LIST_PACKAGES_ERROR(101_315, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_PKG_MNGR_UTIL_GET_PACKAGE_LIST_ERROR(101_316, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_PKG_MNGR_UTIL_UNINSTALLATION_ERROR(101_317, ErrorType.UNDETERMINED),
  ANDROID_PKG_MNGR_UTIL_GET_APK_ABI_ERROR(101_318, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PKG_MNGR_UTIL_GET_APK_MIN_SDK_VERSION_ERROR(101_319, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PKG_MNGR_UTIL_GET_APK_PACKAGE_NAME_ERROR(101_320, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PKG_MNGR_UTIL_GET_APK_VERSION_CODE_ERROR(101_321, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PKG_MNGR_UTIL_GET_APK_VERSION_NAME_ERROR(101_322, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PKG_MNGR_UTIL_SDK_VERSION_NOT_SUPPORT(101_323, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_PKG_MNGR_UTIL_GET_DEVICE_PROP_ERROR(101_324, ErrorType.INFRA_ISSUE),
  ANDROID_PKG_MNGR_UTIL_GET_APEX_MODULE_VERSION_CODE_ERROR(101_325, ErrorType.INFRA_ISSUE),
  ANDROID_PKG_MNGR_UTIL_INVALID_APEX_VERSION_CODE(101_326, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_PKG_MNGR_UTIL_MISSING_APEX_VERSION_CODE(101_327, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_PKG_MNGR_UTIL_PARTIAL_INSTALL_NOT_ALLOWED_ERROR(101_328, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PKG_MNGR_UTIL_INSTALLATION_VERSION_DOWNGRADE(101_329, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_PKG_MNGR_UTIL_INSTALLATION_INSUFFICIENT_STORAGE(101_330, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_PKG_MNGR_UTIL_INSTALLATION_ERROR_IN_SHARED_LAB(101_331, ErrorType.INFRA_ISSUE),
  ANDROID_PKG_MNGR_UTIL_INSTALLATION_ERROR_IN_SATELLITE_LAB(101_332, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PKG_MNGR_UTIL_INSTALLATION_PARSE_FAILED_MANIFEST_MALFORMED(
      101_333, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PKG_MNGR_UTIL_INSTALLATION_FAILED_INVALID_APK(101_334, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PKG_MNGR_UTIL_INSTALLATION_FAILED_DUPLICATE_PERMISSION(101_335, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PKG_MNGR_UTIL_INSTALLATION_FAILED_OLDER_SDK(101_336, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PKG_MNGR_UTIL_INSTALLATION_FAILED_NO_VALID_UID_ASSIGNED(
      101_337, ErrorType.DEPENDENCY_ISSUE),

  // AAPT: 101_601 ~ 101_800
  ANDROID_AAPT_GET_APK_ABI_ERROR(101_601, ErrorType.CUSTOMER_ISSUE),
  ANDROID_AAPT_GET_LAUNCHABLE_ACTIVITY_NAME_ERROR(101_602, ErrorType.CUSTOMER_ISSUE),
  ANDROID_AAPT_APK_INVALID_VERSION_CODE(101_603, ErrorType.CUSTOMER_ISSUE),
  ANDROID_AAPT_APK_UNMATCHED_VERSION_INFO_FORMAT(101_604, ErrorType.CUSTOMER_ISSUE),
  ANDROID_AAPT_APK_UNMATCHED_VERSION_NAME_FORMAT(101_605, ErrorType.CUSTOMER_ISSUE),
  ANDROID_AAPT_GET_APK_PACKAGE_NAME_ERROR(101_606, ErrorType.CUSTOMER_ISSUE),
  ANDROID_AAPT_COMMAND_EXEC_TIMEOUT(101_607, ErrorType.INFRA_ISSUE),
  ANDROID_AAPT_PATH_NOT_SET(101_608, ErrorType.INFRA_ISSUE),
  ANDROID_AAPT_COMMAND_START_ERROR(101_609, ErrorType.INFRA_ISSUE),

  // Dexdump Util: 101_801 ~ 101_850
  ANDROID_DEX_DUMP_NO_DEX_ENTRIES(101_801, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_DEX_DUMP_GET_DEX_DUMP_FILES_ERROR(101_802, ErrorType.INFRA_ISSUE),
  ANDROID_DEX_DUMP_GET_DEXES_FROM_APK_ERROR(101_803, ErrorType.INFRA_ISSUE),
  ANDROID_DEX_DUMP_CMD_EXEC_ERROR(101_804, ErrorType.DEPENDENCY_ISSUE),

  // AndroidProcessUtil: 101_851 ~ 102_100
  ANDROID_PROCESS_GET_PROCESS_ID_ERROR(101_851, ErrorType.INFRA_ISSUE),
  ANDROID_PROCESS_DUMP_HEAP_ERROR(101_852, ErrorType.INFRA_ISSUE),
  ANDROID_PROCESS_GET_PROCESS_STATUS_ERROR(101_853, ErrorType.INFRA_ISSUE),
  ANDROID_PROCESS_DUMPSYS_SERVICE_ERROR(101_854, ErrorType.INFRA_ISSUE),
  ANDROID_PROCESS_START_APP_ERROR(101_855, ErrorType.UNDETERMINED),
  ANDROID_PROCESS_START_APP_BY_INTENT_ERROR(101_856, ErrorType.UNDETERMINED),
  ANDROID_PROCESS_STOP_PROCESS_ERROR(101_857, ErrorType.INFRA_ISSUE),
  ANDROID_PROCESS_UPDATE_SERVICE_ERROR(101_858, ErrorType.UNDETERMINED),
  ANDROID_PROCESS_STOP_PROCESS_TIMEOUT(101_859, ErrorType.CUSTOMER_ISSUE),

  // AndroidAccountManagerUtil: 102_101 ~ 102_250
  ANDROID_ACCOUNT_MNGR_UTIL_ADD_ACCOUNT_BY_ACCOUNT_UTIL_ERROR(102_101, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_ACCOUNT_MNGR_UTIL_ADD_ACCOUNT_BY_ACCOUNT_MNGR_ERROR(102_102, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_ACCOUNT_MNGR_UTIL_WRONG_PASSWORD(102_103, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ACCOUNT_MNGR_UTIL_REMOVE_ACCOUNT_ERROR(102_104, ErrorType.INFRA_ISSUE),
  ANDROID_ACCOUNT_MNGR_UTIL_REMOVE_ACCOUNT_BY_ACCOUNT_UTIL_ERROR(102_105, ErrorType.CUSTOMER_ISSUE),

  // AndroidUserUtil: 102_251 ~ 102_400
  ANDROID_USER_UTIL_CREATE_WORK_PROFILE_ERROR(102_251, ErrorType.INFRA_ISSUE),
  ANDROID_USER_UTIL_LIST_USERS_ERROR(102_252, ErrorType.INFRA_ISSUE),
  ANDROID_USER_UTIL_REMOVE_USER_ERROR(102_254, ErrorType.INFRA_ISSUE),
  ANDROID_USER_UTIL_START_USER_ERROR(102_255, ErrorType.INFRA_ISSUE),
  ANDROID_USER_UTIL_GET_FOREGROUND_USER_ERROR(102_256, ErrorType.INFRA_ISSUE),
  ANDROID_USER_UTIL_USER_NOT_EXIST(102_257, ErrorType.INFRA_ISSUE),
  ANDROID_USER_UTIL_SWITCH_USER_ERROR(102_258, ErrorType.INFRA_ISSUE),
  ANDROID_USER_UTIL_GET_RUNNING_USER_ERROR(102_259, ErrorType.INFRA_ISSUE),
  ANDROID_USER_UTIL_CREATE_USER_ERROR(102_260, ErrorType.INFRA_ISSUE),
  ANDROID_USER_UTIL_SDK_VERSION_NOT_SUPPORT(102_261, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_USER_UTIL_WAIT_FOR_USER_NOT_READY(102_262, ErrorType.DEPENDENCY_ISSUE),

  // AndroidMediaUtil: 102_401 ~ 102_600
  ANDROID_MEDIA_UTIL_ENTER_VR_MODE_ERROR(102_401, ErrorType.INFRA_ISSUE),
  ANDROID_MEDIA_UTIL_INPUT_TEXT_ERROR(102_402, ErrorType.INFRA_ISSUE),
  ANDROID_MEDIA_UTIL_RECORD_SCREEN_ERROR(102_403, ErrorType.INFRA_ISSUE),
  ANDROID_MEDIA_UTIL_ROTATE_SCREEN_ERROR(102_404, ErrorType.INFRA_ISSUE),
  ANDROID_MEDIA_UTIL_SET_ACCELEROMETER_ROTATION_ERROR(102_405, ErrorType.INFRA_ISSUE),
  ANDROID_MEDIA_UTIL_START_SCREEN_RECORD_VR_ERROR(102_406, ErrorType.INFRA_ISSUE),
  ANDROID_MEDIA_UTIL_STOP_SCREEN_RECORD_TIMEOUT(102_407, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_MEDIA_UTIL_STOP_SCREEN_RECORD_VR_ERROR(102_408, ErrorType.INFRA_ISSUE),
  ANDROID_MEDIA_UTIL_TAKE_SCREEN_SHOT_ERROR(102_409, ErrorType.INFRA_ISSUE),
  ANDROID_MEDIA_UTIL_GET_SCREEN_ORIENTATION_ERROR(102_410, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_MEDIA_UTIL_DUMPSYS_ORIENTATION_INFO_ERROR(102_411, ErrorType.INFRA_ISSUE),

  // Adb: 102_601 ~ 102_700
  ANDROID_ADB_SYNC_CMD_EXECUTION_ERROR(102_601, ErrorType.UNDETERMINED),
  ANDROID_ADB_SYNC_CMD_EXECUTION_TIMEOUT(102_602, ErrorType.UNDETERMINED),
  ANDROID_ADB_SYNC_CMD_EXECUTION_FAILURE(102_603, ErrorType.UNDETERMINED),
  ANDROID_ADB_CMD_RETRY_ERROR(102_604, ErrorType.UNDETERMINED),
  ANDROID_ADB_SYNC_CMD_START_ERROR(102_605, ErrorType.UNDETERMINED),
  ANDROID_ADB_SHELL_RETRY_ERROR(102_606, ErrorType.UNDETERMINED),
  ANDROID_ADB_SHELL_START_ERROR(102_607, ErrorType.UNDETERMINED),
  ANDROID_ADB_ASYNC_CMD_START_ERROR(102_608, ErrorType.UNDETERMINED),
  ANDROID_ADB_WITHOUT_DEVICE_BLOCK_FEATURE_FOR_SANDBOX(102_609, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ADB_CHECK_DEVICE_SANDBOX_SUPPORT_ERROR(102_610, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_ADB_SYNC_CMD_EXECUTION_ASSERTION_FAILURE(102_611, ErrorType.CUSTOMER_ISSUE),

  // AndroidAdbInternalUtil: 102_701 ~ 102_900
  ANDROID_ADB_INTERNAL_UTIL_INVALID_ADB_LINE_FORMAT(102_701, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_ADB_INTERNAL_UTIL_GET_DEVICE_SERIALS_CMD_ERROR(102_702, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_ADB_INTERNAL_UTIL_ADB_KILL_SERVER_ERROR(102_703, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_INTERNAL_UTIL_GET_ADB_VERSION_ERROR(102_704, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_ADB_INTERNAL_UTIL_CONNECT_CMD_ERROR(102_705, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_INTERNAL_UTIL_CONNECT_ERROR(102_706, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_ADB_INTERNAL_UTIL_DISCONNECT_CMD_ERROR(102_707, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_INTERNAL_UTIL_DISCONNECT_ERROR(102_708, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_ADB_INTERNAL_UTIL_DEVICE_DETACH_ERROR(102_709, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_INTERNAL_UTIL_DEVICE_ATTACH_ERROR(102_710, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_INTERNAL_UTIL_GET_HOST_FEATURES_ERROR(102_711, ErrorType.INFRA_ISSUE),

  // UiAutomatorUtil: 102_901 ~ 102_950
  UIAUTOMATOR_UTIL_DUMP_ERROR(102_901, ErrorType.INFRA_ISSUE),
  UIAUTOMATOR_UTIL_DUMP_UNEXPECT_OUTPUT(102_902, ErrorType.DEPENDENCY_ISSUE),
  UIAUTOMATOR_UTIL_UIAUTOMATOR_TEST_TIMEOUT(102_903, ErrorType.CUSTOMER_ISSUE),

  // AndroidMonkeyUtil: 102_951 ~ 103_000
  ANDROID_MONKEY_UTIL_RUN_MONKEY_TIMEOUT(102_951, ErrorType.CUSTOMER_ISSUE),

  // NativeBinUtil: 103_001 ~ 103_050
  NATIVE_BIN_UTIL_RUN_NATIVE_BIN_TIMEOUT(103_001, ErrorType.CUSTOMER_ISSUE),
  NATIVE_BIN_UTIL_RUN_NATIVE_BIN_FAILURE(103_002, ErrorType.CUSTOMER_ISSUE),
  NATIVE_BIN_UTIL_RUN_NATIVE_BIN_NON_ZERO_EXIT_CODE_FROM_ECHO(103_003, ErrorType.CUSTOMER_ISSUE),
  NATIVE_BIN_UTIL_RUN_NATIVE_BIN_NULL_COMMAND_RESULT_ERROR(103_004, ErrorType.INFRA_ISSUE),

  // Android Waterfall Service: 103_051 ~ 103_100
  ANDROID_WATERFALL_SERVICE_RESOURCE_NOT_FOUND(103_051, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_WATERFALL_SERVICE_BOOT_CMD_FAILED(103_052, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_WATERFALL_SERVICE_UNSUPPORTED_ARCH(103_053, ErrorType.DEPENDENCY_ISSUE),

  // AndroidEmulatorUtil: 109_201 ~ 109_400
  ANDROID_EMULATOR_UTIL_START_EMULATOR_ERROR(109_201, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_EMULATOR_UTIL_NO_ENOUGH_STORAGE(109_202, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_EMULATOR_PORT_PICK_UP_ERROR(109_203, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_EMULATOR_START_SCRIPT_NOT_FOUND(109_204, ErrorType.DEPENDENCY_ISSUE),

  // AndroidApiUtil: 109_401 ~ 109_950. AndroidApiUtil may be refactored later as of
  // go/mh-lightning-api.
  ANDROID_API_UTIL_PROCESS_OUTPUT_FILES_ERROR(109_401, ErrorType.INFRA_ISSUE),
  ANDROID_API_UTIL_PULL_PROPERTY_FILES_ERROR(109_402, ErrorType.INFRA_ISSUE),

  // Flashstation: 109_951 ~ 110_000
  ANDROID_FLASHSTATION_COMMAND_EXEC_ERROR(109_951, ErrorType.DEPENDENCY_ISSUE),
  // TODO deprecate remaining legecy error codes
  ANDROID_FLASHSTATION_BUILD_INCOMPATIBLE_ERROR(109_952, ErrorType.CUSTOMER_ISSUE),
  /**
   * @deprecated Replaced by errors in FS namespace.
   */
  @Deprecated
  ANDROID_FLASHSTATION_USB_TRANSFER_ERROR(109_953, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FLASHSTATION_BUILD_NOT_FOUND_ERROR(109_954, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FLASHSTATION_ANDROID_INFO_REQUIREMENTS_NOT_MET_ERROR(109_955, ErrorType.CUSTOMER_ISSUE),
  /**
   * @deprecated Replaced by errors in FS namespace.
   */
  @Deprecated
  ANDROID_FLASHSTATION_TIMED_OUT_WAITING_FOR_DEVICE_ERROR(109_956, ErrorType.CUSTOMER_ISSUE),
  /**
   * @deprecated Replaced by errors in FS namespace.
   */
  @Deprecated
  ANDROID_FLASHSTATION_NO_SPACE_LEFT_ERROR(109_957, ErrorType.CUSTOMER_ISSUE),

  /** Android Devices: 110_001 ~ 115_000 */
  // Android Detector: 110_001 ~ 110_200
  ANDROID_DM_DETECTOR_ADB_ERROR(110_001, ErrorType.INFRA_ISSUE),
  ANDROID_DM_DETECTOR_FASTBOOT_ERROR(110_002, ErrorType.INFRA_ISSUE),
  ANDROID_DM_DETECTOR_EMULATOR_RECONNECT_ERROR(110_003, ErrorType.INFRA_ISSUE),

  // AndroidRealDevice: 110_201 ~ 111_000
  ANDROID_REAL_DEVICE_MISS_RECOVERY_DIMENSION_ERROR(110_201, ErrorType.CUSTOMER_ISSUE),
  ANDROID_REAL_DEVICE_REBOOT_FASTBOOT_DEVICE_TO_RECOVER(110_202, ErrorType.CUSTOMER_ISSUE),
  ANDROID_REAL_DEVICE_ONLINE_DEVICE_NOT_READY(110_203, ErrorType.INFRA_ISSUE),
  ANDROID_REAL_DEVICE_PASSTHROUGH_TO_SANDBOX_TIMEOUT(110_204, ErrorType.INFRA_ISSUE),
  ANDROID_REAL_DEVICE_PASSTHROUGH_FROM_SANDBOX_TIMEOUT(110_205, ErrorType.INFRA_ISSUE),
  ANDROID_REAL_DEVICE_USB_LOCATOR_NOT_SET(110_206, ErrorType.INFRA_ISSUE),
  ANDROID_REAL_DEVICE_PASSTHROUGH_FAILED(110_207, ErrorType.INFRA_ISSUE),
  ANDROID_REAL_DEVICE_PUT_PROXY_ERROR(110_208, ErrorType.INFRA_ISSUE),

  // AndroidDeviceDelegate: 111_001 ~ 111_200
  ANDROID_DEVICE_DELEGATE_TEST_PREP_ERROR(111_001, ErrorType.INFRA_ISSUE),

  /** Android Drivers: 115_001 ~ 125_000 */
  // Android Instrumentation: 115_001 ~ 115_500
  ANDROID_INSTRUMENTATION_TEST_FAILED(115_001, ErrorType.CUSTOMER_ISSUE),
  ANDROID_INSTRUMENTATION_TEST_ERROR(115_002, ErrorType.UNDETERMINED),
  ANDROID_INSTRUMENTATION_TEST_INFRA_ERROR(115_003, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_TEST_TIMEOUT(115_004, ErrorType.CUSTOMER_ISSUE),
  ANDROID_INSTRUMENTATION_TEST_RESULT_NOT_FOUND(115_005, ErrorType.UNDETERMINED),

  ANDROID_INSTRUMENTATION_INCOMPATIBLE_DEVICE(115_010, ErrorType.CUSTOMER_ISSUE),
  ANDROID_INSTRUMENTATION_INVALID_TEST_DATA(115_011, ErrorType.CUSTOMER_ISSUE),
  ANDROID_INSTRUMENTATION_RUNNER_NOT_FOUND(115_012, ErrorType.CUSTOMER_ISSUE),
  ANDROID_INSTRUMENTATION_SPEC_PARSE_ERROR(115_013, ErrorType.CUSTOMER_ISSUE),
  ANDROID_INSTRUMENTATION_TEST_ARGS_NOT_SET(115_014, ErrorType.CUSTOMER_ISSUE),

  ANDROID_INSTRUMENTATION_CHECK_FILE_ERROR(115_020, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_CLEAN_TEST_STORAGE_ERROR(115_021, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_WRITE_FILE_ERROR(115_022, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_PULL_FILE_ERROR(115_023, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_PUSH_FILE_ERROR(115_024, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_EXTERNAL_STORAGE_NOT_FOUND(115_025, ErrorType.INFRA_ISSUE),

  ANDROID_INSTRUMENTATION_ADB_COMMAND_ERROR(115_031, ErrorType.UNDETERMINED),
  ANDROID_INSTRUMENTATION_INSTALL_APK_ERROR(115_032, ErrorType.UNDETERMINED),
  ANDROID_INSTRUMENTATION_CLEAR_PACKAGE_ERROR(115_033, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_GET_SDK_VERSION_ERROR(115_034, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_ENABLE_LEGACY_STORAGE_ERROR(115_035, ErrorType.INFRA_ISSUE),
  ANDROID_INSTRUMENTATION_DEX_DUMP_CMD_EXEC_ERROR(115_036, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_INSTRUMENTATION_DEX_DUMP_METHOD_INFOS_FROM_APK_ERROR(115_037, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_INSTRUMENTATION_ENABLE_MANAGE_EXTERNAL_STORAGE_ERROR(115_038, ErrorType.INFRA_ISSUE),

  ANDROID_INSTRUMENTATION_CREATE_MESSAGE_ERROR(115_041, ErrorType.INFRA_ISSUE),

  ANDROID_INSTRUMENTATION_LISTER_ILLEGAL_ARGUMENT(115_050, ErrorType.CUSTOMER_ISSUE),
  ANDROID_INSTRUMENTATION_LISTER_DEX_DUMP_CMD_EXEC_ERROR(115_051, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_INSTRUMENTATION_LISTER_DEX_DUMP_METHOD_INFOS_FROM_APK_ERROR(
      115_052, ErrorType.DEPENDENCY_ISSUE),

  // Android Marmoset Driver: 115_501 ~ 115_550
  // 115_501 is available
  ANDROID_MARMOSET_CRAWL_DRIVER_ERROR(115_502, ErrorType.INFRA_ISSUE),
  ANDROID_MARMOSET_CRAWL_PLATFORM_ERROR(115_503, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_MARMOSET_CRAWL_MONITOR_ERROR(115_504, ErrorType.INFRA_ISSUE),
  ANDROID_MARMOSET_APK_SIGN_ERROR(115_505, ErrorType.INFRA_ISSUE),
  ANDROID_MARMOSET_CRAWLER_REPACKAGING_ERROR(115_506, ErrorType.INFRA_ISSUE),
  ANDROID_MARMOSET_LOGCAT_PROCESS_ERROR(115_507, ErrorType.CUSTOMER_ISSUE),
  ANDROID_MARMOSET_CLEAR_LOG_ERROR(115_508, ErrorType.UNDETERMINED),
  ANDROID_MARMOSET_SET_LOG_LEVEL_PROPERTY_ERROR(115_509, ErrorType.INFRA_ISSUE),
  ANDROID_MARMOSET_SET_LOGCAT_BUFFER_SIZE_ERROR(115_510, ErrorType.INFRA_ISSUE),
  ANDROID_MARMOSET_GET_DEVICE_SDK_ERROR(115_511, ErrorType.INFRA_ISSUE),
  ANDROID_MARMOSET_OPEN_FILE_WRITER_ERROR(115_512, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_MARMOSET_FILE_WRITER_WRITE_ERROR(115_513, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_MARMOSET_CLOSE_FILE_WRITER_ERROR(115_514, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_MARMOSET_PROCESS_AWAIT_ERROR(115_515, ErrorType.UNDETERMINED),
  ANDROID_MARMOSET_INSTALL_FAILED_UPDATE_INCOMPATIBLE(115_516, ErrorType.CUSTOMER_ISSUE),
  ANDROID_MARMOSET_CRAWL_TIMEOUT(115_517, ErrorType.INFRA_ISSUE),
  ANDROID_MARMOSET_INVALID_CRAWLER_DURATION_ERROR(115_518, ErrorType.CUSTOMER_ISSUE),
  ANDROID_MARMOSET_INSTALL_APK_INFRA_ISSUE(115_519, ErrorType.INFRA_ISSUE),
  ANDROID_MARMOSET_INSTALL_APK_CUSTOMER_ISSUE(115_520, ErrorType.CUSTOMER_ISSUE),

  // AndroidNativeBin driver: 115_551 ~ 115_600
  ANDROID_NATIVE_BIN_EXIT_CODE_ERROR(115_551, ErrorType.CUSTOMER_ISSUE),
  ANDROID_NATIVE_BIN_SIGNAL_NOT_FOUND(115_552, ErrorType.CUSTOMER_ISSUE),
  ANDROID_NATIVE_BIN_ANDROID_BUILD_ERROR(115_553, ErrorType.CUSTOMER_ISSUE),
  ANDROID_NATIVE_BIN_TEST_NOT_FOUND_IN_BIN(115_554, ErrorType.CUSTOMER_ISSUE),

  // GoogleTradefedDriver driver: 115_601 ~ 115_650
  GOOGLE_TRADEFED_DRIVER_SPEC_ERROR(115_601, ErrorType.INFRA_ISSUE),
  GOOGLE_TRADEFED_DRIVER_PROCESS_ERROR(115_602, ErrorType.INFRA_ISSUE),
  GOOGLE_TRADEFED_DRIVER_BAD_RESULT(115_603, ErrorType.INFRA_ISSUE),
  GOOGLE_TRADEFED_MISSING_ARTIFACTS(115_604, ErrorType.CUSTOMER_ISSUE),
  GOOGLE_TRADEFED_MISSING_DIMENSIONS(115_605, ErrorType.CUSTOMER_ISSUE),
  GOOGLE_TRADEFED_MISSING_KEYSTORE_KEY(115_606, ErrorType.CUSTOMER_ISSUE),
  GOOGLE_TRADEFED_UNSUPPORTED_FILE_ACTION(115_607, ErrorType.CUSTOMER_ISSUE),
  GOOGLE_TRADEFED_DEVICE_NOT_FOUND(115_608, ErrorType.CUSTOMER_ISSUE),
  GOOGLE_TRADEFED_TOO_MANY_DEVICES(115_609, ErrorType.CUSTOMER_ISSUE),

  // AndroidTestExecutor driver: 115_651 ~ 115_700
  ANDROID_TRADEFED_TEST_EXECUTION_ERROR(115_651, ErrorType.INFRA_ISSUE),
  ANDROID_TRADEFED_TEST_FAILED_TO_COPY_RESULTS(115_652, ErrorType.INFRA_ISSUE),
  ANDROID_TRADEFED_TEST_RESULT_PARSING_ERROR(115_653, ErrorType.INFRA_ISSUE),
  ANDROID_TRADEFED_TEST_FAILED_TO_DECODE_BASE64_TEST_COMMAND(115_654, ErrorType.CUSTOMER_ISSUE),
  ANDROID_TRADEFED_TEST_FAILED_COPY_KEY(115_655, ErrorType.INFRA_ISSUE),
  ANDROID_TRADEFED_TEST_UNKNOWN_ERROR(115_656, ErrorType.INFRA_ISSUE),
  ANDROID_TRADEFED_TEST_ENVIRONMENT_ERROR(115_657, ErrorType.INFRA_ISSUE),
  ANDROID_TRADEFED_TEST_ASSUMPTION_FAILURE(115_658, ErrorType.CUSTOMER_ISSUE),
  ANDROID_TRADEFED_TEST_IGNORED(115_659, ErrorType.CUSTOMER_ISSUE),
  ANDROID_TRADEFED_TEST_HAS_ERROR_SUBTEST(115_660, ErrorType.UNDETERMINED),
  ANDROID_TRADEFED_TEST_HAS_FAIL_SUBTEST(115_661, ErrorType.CUSTOMER_ISSUE),
  ANDROID_TRADEFED_TEST_ALL_SUBTESTS_SKIPPED(115_662, ErrorType.CUSTOMER_ISSUE),
  ANDROID_TRADEFED_TEST_FAILED_COPY_CONFIG(115_663, ErrorType.INFRA_ISSUE),
  ANDROID_TRADEFED_TEST_GRPC_ERROR(115_664, ErrorType.INFRA_ISSUE),

  // AndroidGUnit driver: 115_701 ~ 115_750
  ANDROID_GUNIT_OUTPUT_FILE_ERROR(115_701, ErrorType.CUSTOMER_ISSUE),

  // AndroidMonkey driver:115_751 ~ 115_800
  ANDROID_MONKEY_BUILD_APK_NOT_FOUND(115_751, ErrorType.CUSTOMER_ISSUE),
  ANDROID_MONKEY_INSTALL_APP_ERROR(115_752, ErrorType.INFRA_ISSUE),
  ANDROID_MONKEY_PRE_START_ACTIVITY_ERROR(115_753, ErrorType.INFRA_ISSUE),
  ANDROID_MONKEY_TIMEOUT(115_754, ErrorType.INFRA_ISSUE),
  ANDROID_MONKEY_FAIL(115_755, ErrorType.CUSTOMER_ISSUE),
  ANDROID_MONKEY_FAIL_ACTIVITY_NOT_FOUND(115_756, ErrorType.CUSTOMER_ISSUE),
  ANDROID_MONKEY_FINISHED_UNEXPECTLY(115_757, ErrorType.INFRA_ISSUE),
  ANDROID_MONKEY_KILL_MONKEY_ERROR(115_758, ErrorType.INFRA_ISSUE),
  ANDROID_MONKEY_START_SCREEN_PINNING_ERROR(115_759, ErrorType.INFRA_ISSUE),
  ANDROID_MONKEY_KILL_SCREEN_PINNING_ERROR(115_760, ErrorType.INFRA_ISSUE),
  ANDROID_MONKEY_GET_VERSION_ERROR(115_761, ErrorType.INFRA_ISSUE),

  // AndroidChromedriver driver: 115_801 ~ 115_850
  ANDROID_CHROMEDRIVER_TEST_FAIL(115_801, ErrorType.INFRA_ISSUE),
  ANDROID_CHROMEDRIVER_TEST_ERROR(115_802, ErrorType.INFRA_ISSUE),
  ANDROID_CHROMEDRIVER_JOB_FILE_ERROR(115_803, ErrorType.INFRA_ISSUE),
  ANDROID_CHROMEDRIVER_TEST_LISTER_ERROR(115_804, ErrorType.INFRA_ISSUE),
  ANDROID_CHROMEDRIVER_DEVICE_NOT_SUPPORTED(115_805, ErrorType.INFRA_ISSUE),
  ANDROID_CHROMEDRIVER_TEST_RUNNER_ERROR(115_806, ErrorType.INFRA_ISSUE),

  /** Android Decorators: 125_001 ~ 135_000 */

  // AndroidFilePusherDecorator: 125_001 ~ 125_200
  ANDROID_FILE_PUSHER_DECORATOR_READ_ONLY_FILE_FROM_USER(125_001, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FILE_PUSHER_DECORATOR_PUSH_USER_DIRECTORY_TO_FILE_ERROR(
      125_002, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FILE_PUSHER_DECORATOR_USER_FILE_NOT_FOUND(125_003, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FILE_PUSHER_DECORATOR_DELETE_FILE_ERROR(125_004, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_PUSHER_DECORATOR_PUSH_FILE_ERROR(125_005, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_PUSHER_DECORATOR_DEVICE_NOT_FOUND(125_006, ErrorType.UNDETERMINED),
  ANDROID_FILE_PUSHER_DECORATOR_ILLEGAL_ARGUMENT(125_007, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FILE_PUSHER_DECORATOR_DELETE_FILE_INVALID_ARGUMENT(125_008, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FILE_PUSHER_DECORATOR_GET_ONLINE_DEVICES_ERROR(125_009, ErrorType.INFRA_ISSUE),

  // AndroidFilePullerDecorator: 125_201 ~ 125_400
  ANDROID_FILE_PULLER_DECORATOR_OUTPUT_FILE_NOT_FOUND(125_201, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FILE_PULLER_DECORATOR_PULL_FILE_ERROR(125_202, ErrorType.INFRA_ISSUE),

  // AndroidResMonitorDecorator: 125_401 ~ 125_600
  ANDROID_RES_MONITOR_DUMP_HEAP_ERROR(125_401, ErrorType.INFRA_ISSUE),
  ANDROID_RES_MONITOR_GET_CPU_USAGE_ERROR(125_402, ErrorType.INFRA_ISSUE),
  ANDROID_RES_MONITOR_GET_GFXINFO_ERROR(125_403, ErrorType.INFRA_ISSUE),
  ANDROID_RES_MONITOR_GET_MEMINFO_ERROR(125_404, ErrorType.INFRA_ISSUE),
  ANDROID_RES_MONITOR_GET_SDK_VERSION_ERROR(125_405, ErrorType.INFRA_ISSUE),
  ANDROID_RES_MONITOR_GET_TOTAL_MEM_ERROR(125_406, ErrorType.INFRA_ISSUE),
  ANDROID_RES_MONITOR_INVALID_MEMINFO(125_407, ErrorType.INFRA_ISSUE),
  ANDROID_RES_MONITOR_CREATE_REPORT_FOLDER_ERROR(125_408, ErrorType.INFRA_ISSUE),
  ANDROID_RES_MONITOR_WRITE_REPORT_ERROR(125_409, ErrorType.INFRA_ISSUE),

  // AndroidSystemHealthMemoryDecorator: 125_601 ~ 125_800
  ANDROID_SYSTEM_HEALTH_APP_VERSION_NOT_FOUND(125_601, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_HEALTH_ENABLE_HEAP_COLLECTION_ERROR(125_602, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_SYSTEM_HEALTH_GET_GEN_FILE_ERROR(125_604, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_HEALTH_GET_MEMINFO_ERROR(125_605, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_HEALTH_INVALID_TEST_MESSAGE(125_606, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_HEALTH_ISSUE_GC_ERROR(125_607, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_SYSTEM_HEALTH_PERFORMANCE_LOGGER_ERROR(125_608, ErrorType.INFRA_ISSUE),
  ANDROID_SYSTEM_HEALTH_START_ASYNC_LOGCAT_ERROR(125_609, ErrorType.INFRA_ISSUE),

  // AndroidAdbShellDecorator: 125_801 ~ 126_000
  ANDROID_ADB_SHELL_DECORATOR_BECOME_NON_ROOT_ERROR(125_802, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_SHELL_DECORATOR_BECOME_ROOT_ERROR(125_803, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_SHELL_DECORATOR_CHECK_ROOT_ERROR(125_804, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_SHELL_DECORATOR_COMMAND_EXEC_ERROR(125_805, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ADB_SHELL_DECORATOR_CREATE_MTAAS_SCRIPT_ERROR(125_806, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_SHELL_DECORATOR_EXEC_MTAAS_SCRIPT_ERROR(125_807, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ADB_SHELL_DECORATOR_GET_TEST_REMAINING_TIME_ERROR(125_808, ErrorType.INFRA_ISSUE),
  ANDROID_ADB_SHELL_DECORATOR_REMOVE_MTAAS_SCRIPT_ERROR(125_809, ErrorType.INFRA_ISSUE),

  // AndroidFlashstationDecorator: 126_001 ~ 126_200
  ANDROID_FLASHSTATION_DECORATOR_GET_TEST_TIMEOUT_ERROR(126_002, ErrorType.INFRA_ISSUE),
  ANDROID_FLASHSTATION_DECORATOR_GRANT_FILE_ACCESS_ERROR(126_003, ErrorType.INFRA_ISSUE),
  ANDROID_FLASHSTATION_DECORATOR_INIT_DEVICE_ERROR(126_004, ErrorType.UNDETERMINED),
  ANDROID_FLASHSTATION_DECORATOR_PREPARE_CACHE_ERROR(126_005, ErrorType.INFRA_ISSUE),
  ANDROID_FLASHSTATION_DECORATOR_TEST_TIMEOUT(126_006, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FLASHSTATION_DECORATOR_UPDATE_DEVICE_PROPERTY_ERROR(126_007, ErrorType.INFRA_ISSUE),
  ANDROID_FLASHSTATION_DECORATOR_START_DEVICE_DAEMON_ERROR(126_008, ErrorType.INFRA_ISSUE),
  ANDROID_FLASHSTATION_DECORATOR_UNABLE_TO_WRITE_FLASHING_INFO_ERROR(
      126_009, ErrorType.INFRA_ISSUE),
  ANDROID_FLASHSTATION_DECORATOR_UNABLE_DETERMINE_BUILD_TARGET_IN_FASTBOOT(
      126_010, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FLASHSTATION_DECORATOR_GET_KEY_ERROR(126_011, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FLASHSTATION_DECORATOR_PREP_LOCAL_KEY_FILE_ERROR(126_012, ErrorType.INFRA_ISSUE),
  ANDROID_FLASHSTATION_DECORATOR_GET_DEVICE_PROPERTY_ERROR(126_013, ErrorType.INFRA_ISSUE),
  ANDROID_FLASHSTATION_DECORATOR_REMAINING_TEST_TIME_NOT_ENOUGH(126_014, ErrorType.CUSTOMER_ISSUE),

  // AndroidAccountDecorator: 126_201 ~ 126_400
  ANDROID_ACCOUNT_DECORATOR_APK_INSTALL_ERROR(126_201, ErrorType.UNDETERMINED),
  ANDROID_ACCOUNT_DECORATOR_REMOVE_ACCOUNT_ERROR(126_202, ErrorType.INFRA_ISSUE),
  ANDROID_ACCOUNT_DECORATOR_GET_ONLINE_DEVICES_ERROR(126_203, ErrorType.INFRA_ISSUE),
  ANDROID_ACCOUNT_DECORATOR_DEVICE_NOT_FOUND(126_204, ErrorType.INFRA_ISSUE),
  ANDROID_ACCOUNT_DECORATOR_ADD_ACCOUNT_ERROR(126_205, ErrorType.UNDETERMINED),
  ANDROID_ACCOUNT_DECORATOR_ACCOUNT_WRONG_PASSWORD(126_206, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ACCOUNT_DECORATOR_CHECK_DEVICE_ROOTED_ERROR(126_207, ErrorType.INFRA_ISSUE),
  ANDROID_ACCOUNT_DECORATOR_INVALID_PARAMS(126_208, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ACCOUNT_DECORATOR_APK_INSTALL_INSUFFICIENT_STORAGE(126_209, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_ACCOUNT_DECORATOR_ACCOUNT_PRE_CHECK_ERROR(126_210, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ACCOUNT_DECORATOR_USE_LST_ON_RELEASE_KEYS_DEVICE_ERROR(126_211, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ACCOUNT_DECORATOR_LOGIN_WITH_TAS_FAILURE(126_212, ErrorType.DEPENDENCY_ISSUE),

  // AndroidCrashMonitorDecorator: 126_401 ~ 126_600
  ANDROID_CRASH_MONITOR_DECORATOR_START_ASYNC_MONITOR_ERROR(126_401, ErrorType.INFRA_ISSUE),
  ANDROID_CRASH_MONITOR_DECORATOR_CRASH_DETECTED(126_402, ErrorType.CUSTOMER_ISSUE),
  ANDROID_CRASH_MONITOR_DECORATOR_WRITE_CRASH_REPORT_ERROR(126_403, ErrorType.INFRA_ISSUE),

  // AndroidFlashDeviceDecorator: 126_601 ~ 126_800
  ANDROID_FLASH_DEVICE_DECORATOR_GET_DEVICE_PROPERTY_ERROR(126_601, ErrorType.INFRA_ISSUE),
  ANDROID_FLASH_DEVICE_DECORATOR_GET_TEST_TIMEOUT_ERROR(126_602, ErrorType.INFRA_ISSUE),
  ANDROID_FLASH_DEVICE_DECORATOR_REBOOT_TO_BOOTLOADER_ERROR(126_603, ErrorType.INFRA_ISSUE),
  ANDROID_FLASH_DEVICE_DECORATOR_INIT_DEVICE_ERROR(126_604, ErrorType.UNDETERMINED),
  ANDROID_FLASH_DEVICE_DECORATOR_UPDATE_DEVICE_PROPERTY_ERROR(126_605, ErrorType.INFRA_ISSUE),
  ANDROID_FLASH_DEVICE_DECORATOR_READ_FILE_CONTENT_ERROR(126_606, ErrorType.INFRA_ISSUE),
  ANDROID_FLASH_DEVICE_DECORATOR_TEST_TIMEOUT(126_607, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FLASH_DEVICE_DECORATOR_BUILD_TARGET_MISMATCH_PRODUCT(126_608, ErrorType.CUSTOMER_ISSUE),

  // AndroidViewDumpDecorator: 126_801 ~ 126_900
  ANDROID_VIEWDUMP_DECORATOR_DUMP_VIEW_XML_ERROR(126_801, ErrorType.INFRA_ISSUE),
  ANDROID_VIEWDUMP_DECORATOR_REMOVE_FILE_ERROR(126_802, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_VIEWDUMP_DECORATOR_GRANT_FILE_ACCESS_ERROR(126_803, ErrorType.INFRA_ISSUE),
  ANDROID_VIEWDUMP_DECORATOR_PULL_VIEW_XML_ERROR(126_804, ErrorType.INFRA_ISSUE),
  ANDROID_VIEWDUMP_DECORATOR_PREPARE_FILE_ERROR(126_805, ErrorType.INFRA_ISSUE),

  // AndroidLogcatDecorator: 126_901 ~ 127_000
  ANDROID_LOGCAT_DECORATOR_GET_ONLINE_DEVICES_ERROR(126_901, ErrorType.INFRA_ISSUE),
  ANDROID_LOGCAT_DECORATOR_CLEAR_LOGCAT_ERROR(126_902, ErrorType.UNDETERMINED),
  ANDROID_LOGCAT_DECORATOR_DEVICE_NOT_FOUND(126_903, ErrorType.UNDETERMINED),
  ANDROID_LOGCAT_DECORATOR_SET_LOG_LEVEL_PROPERTY_ERROR(126_904, ErrorType.INFRA_ISSUE),
  /**
   * @deprecated Please use ANDROID_LOGCAT_DECORATOR_SET_LOGCAT_BUFFER_SIZE_ERROR_IN_SHARED_LAB or
   *     ANDROID_LOGCAT_DECORATOR_SET_LOGCAT_BUFFER_SIZE_ERROR_IN_SATELLITE_LAB
   */
  @Deprecated
  ANDROID_LOGCAT_DECORATOR_SET_LOGCAT_BUFFER_SIZE_ERROR(126_905, ErrorType.INFRA_ISSUE),
  ANDROID_LOGCAT_DECORATOR_LOGCAT_EXEC_ERROR(126_906, ErrorType.INFRA_ISSUE),
  ANDROID_LOGCAT_DECORATOR_SAVE_LOG_FILE_TO_HOST_ERROR(126_907, ErrorType.INFRA_ISSUE),
  ANDROID_LOGCAT_DECORATOR_OPEN_FILE_WRITER_ERROR(126_908, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_LOGCAT_DECORATOR_FILE_WRITER_WRITE_ERROR(126_909, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_LOGCAT_DECORATOR_CLOSE_FILE_WRITER_ERROR(126_910, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_LOGCAT_DECORATOR_GET_DEVICE_SDK_ERROR(126_911, ErrorType.INFRA_ISSUE),
  ANDROID_LOGCAT_DECORATOR_GET_DEVICE_TIME_ERROR(126_912, ErrorType.INFRA_ISSUE),
  ANDROID_LOGCAT_DECORATOR_SET_LOGCAT_BUFFER_SIZE_ERROR_IN_SHARED_LAB(
      126_913, ErrorType.INFRA_ISSUE),
  ANDROID_LOGCAT_DECORATOR_SET_LOGCAT_BUFFER_SIZE_ERROR_IN_SATELLITE_LAB(
      126_914, ErrorType.CUSTOMER_ISSUE),

  // AndroidDeviceSettingsDecorator: 127_001 ~ 127_300
  ANDROID_DEVICE_SETTINGS_DECORATOR_COMMAND_EXEC_ERROR(127_001, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_SETTINGS_DECORATOR_GET_CPU_NUM_ERROR(127_002, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_SETTINGS_DECORATOR_SETTINGS_CONFLICT(127_003, ErrorType.CUSTOMER_ISSUE),
  ANDROID_DEVICE_SETTINGS_DECORATOR_SETTING_NOT_SUPPORT_IN_SHARED_LAB(
      127_004, ErrorType.CUSTOMER_ISSUE),
  ANDROID_DEVICE_SETTINGS_DECORATOR_DEVICE_NOT_SUPPORT_REBOOT(127_005, ErrorType.CUSTOMER_ISSUE),
  ANDROID_DEVICE_SETTINGS_DECORATOR_GET_DEVICE_PROPERTY_ERROR(127_006, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_SETTINGS_DECORATOR_CHECK_DIR_OR_FILE_ON_DEVICE_ERROR(
      127_007, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_SETTINGS_DECORATOR_DEVICE_TEMPERATURE_TOO_HIGH(
      127_008, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_DEVICE_SETTINGS_DECORATOR_SYNC_DEVICE_SYSTEM_TIME_ERROR(127_009, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_SETTINGS_DECORATOR_GET_DEVICE_SDK_VERSION_ERROR(127_010, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_SETTINGS_DECORATOR_SET_DM_VERITY_ERROR(127_011, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_SETTINGS_DECORATOR_DEVICE_INIT_AFTER_REBOOT_ERROR(127_012, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_SETTINGS_DECORATOR_CHECK_LAB_EXPERIMENT_ERROR(127_013, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_SETTINGS_DECORATOR_SETTING_NOT_SUPPORT_ERROR(127_014, ErrorType.CUSTOMER_ISSUE),
  ANDROID_DEVICE_SETTINGS_DECORATOR_STOP_INVALID_SERVICE_ERROR(127_015, ErrorType.CUSTOMER_ISSUE),

  // AndroidBugreportDecorator: 127_301 ~ 127_400
  ANDROID_BUGREPORT_DECORATOR_ENABLE_NO_AUTO_RESET_ERROR(127_301, ErrorType.INFRA_ISSUE),
  ANDROID_BUGREPORT_DECORATOR_SET_LOGICAL_DISCHARGE_ERROR(127_302, ErrorType.INFRA_ISSUE),
  ANDROID_BUGREPORT_DECORATOR_GET_DEVICE_SDK_ERROR(127_303, ErrorType.INFRA_ISSUE),
  ANDROID_BUGREPORT_DECORATOR_SAVE_BUGREPORT_ERROR(127_304, ErrorType.INFRA_ISSUE),
  ANDROID_BUGREPORT_DECORATOR_DUMP_BUGREPORT_ERROR(127_305, ErrorType.INFRA_ISSUE),
  ANDROID_BUGREPORT_DECORATOR_DEVICE_NOT_FOUND(127_306, ErrorType.UNDETERMINED),
  ANDROID_BUGREPORT_DECORATOR_RESET_BATTERY_ERROR(127_307, ErrorType.INFRA_ISSUE),
  ANDROID_BUGREPORT_DECORATOR_GET_ONLINE_DEVICES_ERROR(127_308, ErrorType.INFRA_ISSUE),

  // AndroidCleanAppsDecorator: 127_401 ~ 127_600
  ANDROID_CLEAN_APPS_DECORATOR_INVALID_PARAM_VALUE(127_401, ErrorType.CUSTOMER_ISSUE),

  // AndroidInstallMultipleApkDecorator: 127_601 ~ 127_700
  ANDROID_INSTALL_MULTIPLE_DECORATOR_GET_PACKAGE_NAME_ERROR(127_601, ErrorType.INFRA_ISSUE),
  ANDROID_INSTALL_MULTIPLE_DECORATOR_GET_DEVICE_SDK_ERROR(127_602, ErrorType.INFRA_ISSUE),
  ANDROID_INSTALL_MULTIPLE_DECORATOR_LIST_PACKAGES_ERROR(127_603, ErrorType.INFRA_ISSUE),
  ANDROID_INSTALL_MULTIPLE_DECORATOR_UNINSTALL_APP_ERROR(127_604, ErrorType.INFRA_ISSUE),
  ANDROID_INSTALL_MULTIPLE_DECORATOR_INSTALL_APP_ERROR(127_605, ErrorType.UNDETERMINED),
  ANDROID_INSTALL_MULTIPLE_DECORATOR_INSTALL_APP_KILLED_ERROR(127_606, ErrorType.INFRA_ISSUE),
  ANDROID_INSTALL_MULTIPLE_DECORATOR_INSTALL_APP_BAD_ABI_ERROR(127_607, ErrorType.CUSTOMER_ISSUE),
  ANDROID_INSTALL_MULTIPLE_DECORATOR_INSTALL_APP_UNKNOWN_ERROR(127_608, ErrorType.UNDETERMINED),
  ANDROID_INSTALL_MULTIPLE_DECORATOR_GET_TIMEOUT_ERROR(127_609, ErrorType.CUSTOMER_ISSUE),
  ANDROID_INSTALL_MULTIPLE_DECORATOR_INSTANT_APP_UNSUPPORTED_ERROR(
      127_610, ErrorType.CUSTOMER_ISSUE),

  // AndroidDumpsysDecorator: 127_701 ~ 127_800
  ANDROID_DUMPSYS_DECORATOR_DEVICE_NOT_FOUND(127_701, ErrorType.UNDETERMINED),
  ANDROID_DUMPSYS_DECORATOR_DUMPSYS_COMMAND_ERROR(127_702, ErrorType.INFRA_ISSUE),
  ANDROID_DUMPSYS_DECORATOR_WRITE_LOG_FILE_ERROR(127_703, ErrorType.INFRA_ISSUE),

  // AndroidFactoryResetDecorator: 127_801 ~ 127_900
  ANDROID_FACTORY_RESET_DECORATOR_BROADCAST_RESET_NOT_SUPPORTED(127_801, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FACTORY_RESET_DECORATOR_TEST_HARNESS_NOT_SUPPORTED(127_802, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FACTORY_RESET_DECORATOR_INTERNAL_UNEXPECTED_RESET_MANNER(127_803, ErrorType.INFRA_ISSUE),

  // AndroidPerformanceLockDecorator: 127_901 ~ 128_000
  ANDROID_PERFORMANCE_LOCK_DECORATOR_LOCK_ERROR(127_901, ErrorType.INFRA_ISSUE),
  ANDROID_PERFORMANCE_LOCK_DECORATOR_GET_SUPPORTED_DEVICES_ERROR(127_902, ErrorType.INFRA_ISSUE),
  ANDROID_PERFORMANCE_LOCK_DECORATOR_DEVICE_NOT_SUPPORTED_ERROR(127_903, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PERFORMANCE_LOCK_DECORATOR_LOCK_FREQ_RATIO_ERROR(127_904, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PERFORMANCE_LOCK_DECORATOR_DEVICE_TOO_HOT(127_905, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_PERFORMANCE_LOCK_DECORATOR_GET_ONLINE_DEVICES_ERROR(127_906, ErrorType.INFRA_ISSUE),
  ANDROID_PERFORMANCE_LOCK_DECORATOR_DEVICE_NOT_FOUND(127_907, ErrorType.UNDETERMINED),
  ANDROID_PERFORMANCE_LOCK_DECORATOR_CHECK_TEMPERATURE_ERROR(127_908, ErrorType.INFRA_ISSUE),
  ANDROID_PERFORMANCE_LOCK_DECORATOR_GET_DEVICE_CODENAME_ERROR(127_909, ErrorType.INFRA_ISSUE),

  // AndroidInstallMainlineModulesDecorator: 128_001 ~ 128_050
  ANDROID_INSTALL_MAINLINE_MODULES_DECORATOR_DEVICE_NOT_SUPPORTED(
      128_001, ErrorType.CUSTOMER_ISSUE),

  // AndroidSwitchUserDecorator: 128_051 ~ 128_100
  ANDROID_SWITCH_USER_DECORATOR_USER_SWITCH_TIMEOUT(128_051, ErrorType.INFRA_ISSUE),
  ANDROID_SWITCH_USER_DECORATOR_VARIANT_MISSING(128_052, ErrorType.INFRA_ISSUE),
  ANDROID_SWITCH_USER_DECORATOR_USER_MISSING(128_053, ErrorType.INFRA_ISSUE),
  ANDROID_SWITCH_USER_DECORATOR_NOT_SUPPORTED(128_054, ErrorType.CUSTOMER_ISSUE),

  // AndroidSwitchLanguageDecorator: 128_101 ~ 128_150
  ANDROID_SWITCH_LANGUAGE_DECORATOR_WAIT_SIGNAL_IN_LOGCAT_TIMEOUT(
      128_101, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_SWITCH_LANGUAGE_DECORATOR_GRANT_PERMISSION_ERROR(128_102, ErrorType.INFRA_ISSUE),

  // AndroidPhoneskySelfUpdateDecorator: 128_151 ~ 128_200
  ANDROID_PHONESKY_SELF_UPDATE_DECORATOR_INVALID_PARAM_VALUE(128_151, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PHONESKY_SELF_UPDATE_DECORATOR_TEST_FAILED(128_152, ErrorType.CUSTOMER_ISSUE),

  // AndroidChromeWebViewInstallerDecorator: 128_201 ~ 128_250
  ANDROID_CHROME_WEBVIEW_INSTALLER_DECORATOR_INVALID_PARAM_VALUE(128_201, ErrorType.CUSTOMER_ISSUE),
  ANDROID_CHROME_WEBVIEW_INSTALLER_DECORATOR_SDK_VERSION_TOO_LOW(128_202, ErrorType.CUSTOMER_ISSUE),
  ANDROID_CHROME_WEBVIEW_INSTALLER_DECORATOR_COMMAND_ERROR(128_203, ErrorType.CUSTOMER_ISSUE),
  ANDROID_CHROME_WEBVIEW_INSTALLER_DECORATOR_FILE_NOT_FOUND(128_204, ErrorType.CUSTOMER_ISSUE),
  ANDROID_CHROME_WEBVIEW_INSTALLER_DECORATOR_MISSING_DEPENDENCY(128_205, ErrorType.CUSTOMER_ISSUE),
  ANDROID_CHROME_WEBVIEW_INSTALLER_DECORATOR_INTERRUPT(128_206, ErrorType.INFRA_ISSUE),
  ANDROID_CHROME_WEBVIEW_INSTALLER_DECORATOR_FETCH_KEY_FROM_KEYSTORE_FAIL(
      128_207, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_CHROME_WEBVIEW_INSTALLER_DECORATOR_RESOLVE_FILE_FAIL(128_208, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_CHROME_WEBVIEW_INSTALLER_DECORATOR_CREATE_TMP_FILE_FAIL(128_209, ErrorType.INFRA_ISSUE),

  // AndroidLazyProxyDecorator: 128_251 ~ 128_300
  ANDROID_LAZY_PROXY_DECORATOR_DEVICE_SETUP_ERROR(128_251, ErrorType.INFRA_ISSUE),
  ANDROID_LAZY_PROXY_DECORATOR_DEVICE_NOT_ROOTED_ERROR(128_252, ErrorType.INFRA_ISSUE),
  ANDROID_LAZY_PROXY_DECORATOR_FILE_READ_ERROR(128_253, ErrorType.CUSTOMER_ISSUE),

  // AndroidPerfettoDecorator: 129_001 - 129_100
  ANDROID_PERFETTO_DECORATOR_SYNC_EXCEED_TIMEOUT_LIMIT(129_001, ErrorType.INFRA_ISSUE),
  ANDROID_PERFETTO_DECORATOR_ASYNC_EXCEED_TIMEOUT_LIMIT(129_002, ErrorType.INFRA_ISSUE),
  ANDROID_PERFETTO_DECORATOR_ASYNC_EXIT_WITH_ERRORS(129_003, ErrorType.INFRA_ISSUE),
  ANDROID_PERFETTO_DECORATOR_SCRIPT_PATH_IS_NULL(129_004, ErrorType.INFRA_ISSUE),
  ADNROID_PERFETTO_DECORATOR_PYTHON3_NOT_INSTALL_IN_SATELLITE_LAB(
      129_005, ErrorType.CUSTOMER_ISSUE),
  ADNROID_PERFETTO_DECORATOR_PYTHON3_NOT_INSTALL_IN_SHARED_LAB(129_006, ErrorType.INFRA_ISSUE),
  ADNROID_PERFETTO_SCRIPT_NOT_FOUND(129_007, ErrorType.INFRA_ISSUE),
  ADNROID_PERFETTO_CONFIG_NOT_FOUND(129_008, ErrorType.INFRA_ISSUE),

  // AndroidNetworkSimulationDecorator: 129_101 - 129_150
  ANDROID_NETWORK_SIMULATION_DECORATOR_NOT_SUPPORTED_IN_SATELLITE_LAB(
      129_101, ErrorType.CUSTOMER_ISSUE),

  // AndroidDisableAutoUpdatesDecorator: 129_151 - 129_200
  ANDROID_DISABLE_AUTO_UPDATES_DECORATOR_FAILED_TO_UPDATE_AUTO_UPDATE_CONFIG(
      129_151, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_DISABLE_AUTO_UPDATES_DECORATOR_UNABLE_TO_UPDATE_CONFIG_FOR_UNROOTED_DEVICE(
      129_152, ErrorType.CUSTOMER_ISSUE),

  // AndroidSetWifiDecorator: 129_201 - 129_250
  ANDROID_SET_WIFI_DECORATOR_GET_DEFAULT_SSID_ERROR(129_201, ErrorType.CUSTOMER_ISSUE),

  // AndroidInstallAppBundleDecorator: 129_251 ~ 129_300
  ANDROID_INSTALL_APP_BUNDLE_DECORATOR_DEVICE_NOT_SUPPORTED(129_251, ErrorType.CUSTOMER_ISSUE),
  ANDROID_INSTALL_APP_BUNDLE_COMMAND_EXECUTOR_EXCEPTION(129_252, ErrorType.CUSTOMER_ISSUE),

  // AndroidInstallSystemAppsDecorator: 129_301 ~ 129_350
  ANDROID_INSTALL_SYSTEM_APPS_DECORATOR_FAIL_TO_INSTALL(129_301, ErrorType.UNDETERMINED),

  // InstallSystemApkStep: 134_851 ~ 134_899
  ANDROID_INSTALL_SYSTEM_APK_PATHS_NUM_NOT_THE_SAME(134_851, ErrorType.CUSTOMER_ISSUE),
  ANDROID_INSTALL_SYSTEM_APK_PERMISSION_FILES_NUM_NOT_THE_SAME(134_852, ErrorType.CUSTOMER_ISSUE),

  // InstallApkStep:134_900 ~ 134_950
  ANDROID_INSTALL_APK_STEP_INSTALL_NOT_SUPPORTED(134_900, ErrorType.CUSTOMER_ISSUE),
  ANDROID_INSTALL_APK_STEP_DEX_METADATA_WITHOUT_APK(134_901, ErrorType.CUSTOMER_ISSUE),
  ANDROID_INSTALL_APK_STEP_DEX_METADATA_CONFLICT(134_902, ErrorType.CUSTOMER_ISSUE),
  ANDROID_INSTALL_APK_STEP_REBOOT_ERROR(134_903, ErrorType.INFRA_ISSUE),

  // DeviceInitializationStep: 134_951 ~ 135_000
  ANDROID_DEVICE_INIT_STEP_INIT_DEVICE_ERROR(134_951, ErrorType.UNDETERMINED),
  ANDROID_DEVICE_INIT_STEP_UPDATE_DEVICE_PROPERTY_ERROR(134_952, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_INIT_STEP_START_DEVICE_DAEMON_ERROR(134_953, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_INIT_STEP_GET_JOB_PARAM_ERROR(134_954, ErrorType.CUSTOMER_ISSUE),
  ANDROID_DEVICE_INIT_STEP_INIT_DEVICE_NO_ENOUGH_TIME_LEFT(134_955, ErrorType.CUSTOMER_ISSUE),

  /** Plugins: 135_001 ~ 140_000 */
  // AndroidPlayStoreDownloaderPlugin: 135_001 ~ 135_200
  ANDROID_PLAY_STORE_DOWNLOADER_PLUGIN_GAIA_ERROR(135_001, ErrorType.INFRA_ISSUE),
  ANDROID_PLAY_STORE_DOWNLOADER_PLUGIN_MIXER_ERROR(135_002, ErrorType.INFRA_ISSUE),
  ANDROID_PLAY_STORE_DOWNLOADER_PLUGIN_BLOB_ERROR(135_003, ErrorType.INFRA_ISSUE),
  ANDROID_PLAY_STORE_DOWNLOADER_INVALID_GSERVICE_ID(135_004, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PLAY_STORE_DOWNLOADER_PARAM_FORMAT_ERROR(135_005, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PLAY_STORE_DOWNLOADER_PSTASH_ERROR(135_006, ErrorType.INFRA_ISSUE),
  ANDROID_PLAY_STORE_DOWNLOADER_UNKNOWN_DEVICE_PRODUCT_ERROR(135_007, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PLAY_STORE_DOWNLOADER_VERSION_NAME_AND_CODE_NOT_PRESENT_AS_COMBINATION_ERROR(
      135_008, ErrorType.CUSTOMER_ISSUE),
  ANDROID_PLAY_STORE_DOWNLOADER_VERSION_CODE_NOT_A_VALID_INTEGER_ERROR(
      135_009, ErrorType.CUSTOMER_ISSUE),

  // Android Powerbug Issue: 135_201 ~ 135_300
  ANDROID_POWERBUG_RPC_ERROR(135_201, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_POWERBUG_FILE_NOT_FOUND_ERROR(135_202, ErrorType.INFRA_ISSUE),
  ANDROID_POWERBUG_FIND_GEN_FILE_DIR_ERROR(135_203, ErrorType.INFRA_ISSUE),
  ANDROID_POWERBUG_GENERATE_PERFGATE_FILE_ERROR(135_204, ErrorType.INFRA_ISSUE),

  // Android Battery Metrics: 135_301 ~ 135_400
  ANDROID_BATTERY_METRICS_GENERATE_RAW_DATA_PERFGATE_FILE_ERROR(
      135_301, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_BATTERY_METRICS_GENERATE_SUMMARY_PERFGATE_FILE_ERROR(135_302, ErrorType.DEPENDENCY_ISSUE),

  // PreCrawlPlugin: 135_401 ~ 135_410
  ANDROID_APP_FAIL_TO_DOWNLOAD(135_401, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APP_DOWNLOAD_ERROR(135_402, ErrorType.INFRA_ISSUE),
  ANDROID_APK_PREPARE_ERROR(135_403, ErrorType.INFRA_ISSUE),
  ANDROID_APK_NOT_PROVIDED(135_404, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APK_FILE_ERROR(135_405, ErrorType.DEPENDENCY_ISSUE),
  SKIP_THE_METHOD(135_406, ErrorType.DEPENDENCY_ISSUE),

  // RerunPlugin: 135_411 ~ 135_420
  ANDROID_RERUN_PLUGIN_CRASH_WITHOUT_TEST(135_411, ErrorType.INFRA_ISSUE),
  ANDROID_RERUN_PLUGIN_NO_CRAWL_OUTPUT_ERROR(135_412, ErrorType.INFRA_ISSUE),
  ANDROID_RERUN_PLUGIN_PREPARE_DROPBOX_DIR_FAILURE(135_413, ErrorType.INFRA_ISSUE),

  // AndroidGmsCoreInstallerPlugin.java: 135_421 ~ 135_520
  ANDROID_GMSCORE_INSTALLER_PLUGIN_GMSCORE_APK_NOT_EXIST(135_421, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_GMSCORE_INSTALLER_PLUGIN_COPY_APK_ERROR(135_422, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_GMSCORE_INSTALLER_PLUGIN_FETCH_APK_ERROR(135_423, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_GMSCORE_INSTALLER_PLUGIN_INCOMPATIBLE_W_DEVICE_TYPE(135_424, ErrorType.CUSTOMER_ISSUE),
  ANDROID_GMSCORE_INSTALLER_PLUGIN_DEVICE_SPEC_NOT_FOUND_ERROR(135_425, ErrorType.CUSTOMER_ISSUE),
  ANDROID_GMSCORE_INSTALLER_PLUGIN_DUPLICATE_FILE_TAG_ERROR(135_426, ErrorType.CUSTOMER_ISSUE),
  ANDROID_GMSCORE_INSTALLER_PLUGIN_INCOMPATIBLE_EXEC_MODE(135_427, ErrorType.INFRA_ISSUE),
  ANDROID_GMSCORE_INSTALLER_PLUGIN_GET_CHANNEL_VERSION_ERROR(135_428, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_GMSCORE_INSTALLER_PLUGIN_GET_RELEASE_CHANNEL_VERSION_ERROR(
      135_429, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_GMSCORE_INSTALLER_PLUGIN_X20_CLIENT_VERSION_TOO_OLD_ERROR(
      135_430, ErrorType.CUSTOMER_ISSUE),

  /** Android Apps: 140_001 ~ 145_000 */
  // Device Daemon app: 140_001 ~ 140_020
  ANDROID_DEVICE_DAEMON_V1_APK_NOT_FOUND(140_001, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_DAEMON_V2_APK_NOT_FOUND(140_002, ErrorType.INFRA_ISSUE),

  // DeviceDaemonHelper: 140_021 ~ 140_120
  ANDROID_DEVICE_DAEMON_HELPER_GET_SDK_ERROR(140_021, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_DAEMON_HELPER_INSTALL_DAEMON_ERROR(140_022, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_DAEMON_HELPER_START_DAEMON_ERROR(140_023, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_DAEMON_HELPER_GET_NETWORK_SSID_ERROR(140_024, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_DAEMON_HELPER_UNINSTALL_DAEMON_ERROR(140_025, ErrorType.INFRA_ISSUE),
  ANDROID_DEVICE_DAEMON_HELPER_GRANT_DAEMON_PERMISSION_ERROR(140_026, ErrorType.INFRA_ISSUE),

  // App Compat: 140_121 ~ 140_150
  ANDROID_APP_CRASH(140_121, ErrorType.CUSTOMER_ISSUE),
  ANDROID_NATIVE_CRASH(140_122, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ANR(140_123, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APP_STARTUP_TIMEOUT(140_124, ErrorType.CUSTOMER_ISSUE),
  ANDROID_UNSPECIFIED_CRASH(140_125, ErrorType.CUSTOMER_ISSUE),

  ANDROID_APP_COMPAT_POSTPROCESSOR_ERROR(140_140, ErrorType.INFRA_ISSUE),
  ANDROID_APP_COMPAT_CRAWL_STATS_ERROR(140_141, ErrorType.UNDETERMINED),
  ANDROID_APP_COMPAT_BUILD_NOT_FOUND_ERROR(140_142, ErrorType.DEPENDENCY_ISSUE),

  /** Android Decorators Validators: 145_001 ~ 150_000 */
  // AndroidFlashDeviceDecoratorValidator: 145_001 ~ 145_020
  ANDROID_FLASH_DEVICE_DECORATOR_VALIDATOR_FLAG_NOT_TRUE(145_001, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FLASH_DEVICE_DECORATOR_VALIDATOR_DEVICE_NOT_SUPPORTED(145_002, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FLASH_DEVICE_DECORATOR_VALIDATOR_GET_PROPERTY_ERROR(145_003, ErrorType.INFRA_ISSUE),

  // AndroidFactoryResetDecoratorValidator: 145_021 ~ 145_040
  ANDROID_FACTORY_RESET_DECORATOR_VALIDATOR_TCP_DEVICE_NOT_SUPPORTED(
      145_021, ErrorType.CUSTOMER_ISSUE),

  /** MH Lightning API (go/mh-lightning-api): 150_001 ~ 155_000 */
  // ApkInstaller: 150_001 ~ 150_200
  ANDROID_APK_INSTALLER_UPDATE_DIMENSION_ERROR(150_001, ErrorType.INFRA_ISSUE),
  ANDROID_APK_INSTALLER_DEVICE_SDK_TOO_LOW(150_002, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APK_INSTALLER_GMS_INCOMPATIBLE(150_003, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_APK_INSTALLER_INVALID_GMS_VERSION(150_004, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_APK_INSTALLER_APPLY_MULTI_PACKAGE_INSTALL_TO_GMS(150_005, ErrorType.CUSTOMER_ISSUE),

  // SystemStateManager: 150_201 ~ 150_400
  SYSTEM_STATE_MANAGER_REBOOT_DEVICE_ERROR(150_201, ErrorType.INFRA_ISSUE),

  // FileOperator: 150_401 ~ 150_600
  ANDROID_FILE_OPERATOR_PUSH_FILE_OR_DIR_ERROR(150_401, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_OPERATOR_FILE_NOT_FOUND(150_402, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FILE_OPERATOR_ILLEGAL_ARGUMENT(150_403, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FILE_OPERATOR_PULL_FILE_ERROR(150_404, ErrorType.INFRA_ISSUE),
  ANDROID_FILE_OPERATOR_REMOVE_FILE_INVALID_ARGUMENT(150_405, ErrorType.CUSTOMER_ISSUE),
  ANDROID_FILE_OPERATOR_PREPARE_DES_DIR_ERROR(150_406, ErrorType.INFRA_ISSUE),

  // NetworkConnector: 150_601 ~ 150_700
  NETWORK_CONNECTOR_CONNECT_TO_WIFI_ERROR(150_601, ErrorType.INFRA_ISSUE),
  NETWORK_CONNECTOR_INSTALL_WIFIUTIL_ERROR(150_602, ErrorType.INFRA_ISSUE),
  NETWORK_CONNECTOR_CONNECT_TO_WIFI_FAILURE(150_603, ErrorType.DEPENDENCY_ISSUE),

  // AndroidAccountManager: 150_701 ~ 150_800
  ANDROID_ACCOUNT_MANAGER_CHECK_DEVICE_ROOTED_ERROR(150_701, ErrorType.INFRA_ISSUE),
  ANDROID_ACCOUNT_MANAGER_UNROOTED_DEVICE_NOT_SUPPORT_LST(150_702, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ACCOUNT_MANAGER_ACCOUNT_WRONG_PASSWORD(150_703, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ACCOUNT_MANAGER_ADD_ACCOUNT_ERROR(150_704, ErrorType.UNDETERMINED),
  ANDROID_ACCOUNT_MANAGER_INVALID_ARGS(150_705, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ACCOUNT_MANAGER_APK_INSTALL_ERROR(150_706, ErrorType.UNDETERMINED),
  ANDROID_ACCOUNT_MANAGER_REMOVE_ACCOUNT_ERROR(150_707, ErrorType.INFRA_ISSUE),
  ANDROID_ACCOUNT_MANAGER_APK_INSTALL_INSUFFICIENT_STORAGE(150_708, ErrorType.DEPENDENCY_ISSUE),

  // AdbShell: 150_801 ~ 150_900
  ADB_SHELL_COMMAND_EMPTY_ARGS(150_801, ErrorType.CUSTOMER_ISSUE),
  ADB_SHELL_COMMAND_INVALID_ARGS(150_802, ErrorType.CUSTOMER_ISSUE),

  // ***********************************************************************************************
  // Other Variant Android Platforms: 170_001 ~ 200_000
  // ***********************************************************************************************

  // Android TV: 170_601 ~ 170_700
  ANDROID_TV_BUILD_ERROR(170_601, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_TV_FLASH_ALL_ERROR(170_602, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_TV_INCOMPLETE_FLASH(170_603, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_TV_FILE_FLASHALL_NOT_FOUND(170_604, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_TV_REQUIRED_BOARD_ERROR(170_605, ErrorType.DEPENDENCY_ISSUE),

  // Android Cicada Infra Issue: 170_701 ~ 170_800
  ANDROID_CICADA_CONNECT_AVD_ERROR(170_701, ErrorType.INFRA_ISSUE),
  ANDROID_CICADA_DISCONNECT_AVD_ERROR(170_702, ErrorType.INFRA_ISSUE),
  ANDROID_CICADA_SSH_KEY_GEN_ERROR(170_703, ErrorType.INFRA_ISSUE),
  ANDROID_CICADA_SSH_KEY_DELETE_ERROR(170_704, ErrorType.INFRA_ISSUE),
  ANDROID_CICADA_SSH_TUNNEL_AVD_ERROR(170_705, ErrorType.INFRA_ISSUE),
  ANDROID_CICADA_ACQUIRE_AVD_ERROR(170_706, ErrorType.INFRA_ISSUE),
  ANDROID_CICADA_RELEASE_AVD_ERROR(170_707, ErrorType.INFRA_ISSUE),
  ANDROID_CICADA_INVALID_PARAM_ERROR(170_708, ErrorType.INFRA_ISSUE),
  ANDROID_CICADA_CREATE_AVD_ERROR(170_709, ErrorType.CUSTOMER_ISSUE), // b/134361622
  ANDROID_CICADA_DELETE_AVD_ERROR(170_710, ErrorType.INFRA_ISSUE),
  ANDROID_CICADA_AVD_IN_BAD_STATE_ERROR(170_711, ErrorType.DEPENDENCY_ISSUE),

  // ANDROID BUILD: 170_801 ~ 170_900
  ANDROID_BUILD_ERROR(170_801, ErrorType.UNDETERMINED),
  ANDROID_BUILD_OTA_CONFIG_ERROR(170_802, ErrorType.UNDETERMINED),
  ANDROID_BUILD_DES_DIR_NOT_FOUND_ERROR(170_803, ErrorType.UNDETERMINED),
  ANDROID_BUILD_INVALID_SPEC_ERROR(170_804, ErrorType.CUSTOMER_ISSUE),
  ANDROID_BUILD_INIT_ERROR(170_805, ErrorType.INFRA_ISSUE),
  ANDROID_BUILD_INTERNAL_API_ERROR(170_806, ErrorType.INFRA_ISSUE),
  ANDROID_BUILD_NO_ARTIFACTS_ERROR(170_807, ErrorType.CUSTOMER_ISSUE),
  ANDROID_BUILD_INVALID_BUILD_TYPE_ERROR(170_808, ErrorType.CUSTOMER_ISSUE),
  ANDROID_BUILD_FETCH_ARTIFACT_ERROR(170_809, ErrorType.INFRA_ISSUE),
  ANDROID_BUILD_NOT_FOUND_BUILD_ERROR(170_810, ErrorType.CUSTOMER_ISSUE),
  ANDROID_BUILD_SERVICE_UNAVAILABLE(170_811, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_BUILD_BRANCH_TARGET_HAS_NO_BUILD_ID(170_812, ErrorType.CUSTOMER_ISSUE),

  ANDROID_BUILD_ANTS_CREATE_WORKUNIT_ERROR(170_831, ErrorType.INFRA_ISSUE),
  ANDROID_BUILD_ANTS_FINISH_WORKUNIT_ERROR(170_832, ErrorType.INFRA_ISSUE),
  ANDROID_BUILD_ANTS_CREATE_INVOCATION_ERROR(170_833, ErrorType.INFRA_ISSUE),
  ANDROID_BUILD_ANTS_FINISH_INVOCATION_ERROR(170_834, ErrorType.INFRA_ISSUE),
  ANDROID_BUILD_ANTS_UPDATE_WORKUNIT_ERROR(170_835, ErrorType.INFRA_ISSUE),

  // GMS CORE BUILD VARIANT GETTER: 170_901 ~ 171_000
  ANDROID_GMS_CORE_VARIANT_GETTER_GET_EXPECTED_BUILD_VARIANT_ERROR(170_901, ErrorType.INFRA_ISSUE),

  // ACTS (Android Comms Test Suite): 171_001 ~ 171_100
  ANDROID_ACTS_TEST_FAIL(171_001, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ACTS_TEST_SKIP(171_002, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ACTS_TEST_ERROR(171_003, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ACTS_UNKNOWN_ERROR(171_004, ErrorType.UNDETERMINED),
  ANDROID_ACTS_SETUP_ERROR(171_005, ErrorType.UNDETERMINED),
  ANDROID_ACTS_MISSING_ACTS_BINARY_ERROR(171_006, ErrorType.UNDETERMINED),
  ANDROID_ACTS_MISSING_TESTS_DIR_ERROR(171_007, ErrorType.UNDETERMINED),
  ANDROID_ACTS_MISSING_FRAMEWORK_DIR_ERROR(171_008, ErrorType.UNDETERMINED),
  ANDROID_ACTS_MISSING_PYTHON_ERROR(171_009, ErrorType.UNDETERMINED),
  ANDROID_ACTS_RESULTS_PARSER_ERROR(171_010, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ACTS_RESULTS_MISSING_BEGIN_TIME_ERROR(171_011, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ACTS_RESULTS_MISSING_END_TIME_ERROR(171_012, ErrorType.CUSTOMER_ISSUE),
  ANDROID_ACTS_MISSING_FILE_ERROR(171_013, ErrorType.DEPENDENCY_ISSUE),

  // Android screenrecord: 171_101 ~ 171_200
  ANDROID_SCREENRECORD_WRONG_FRAME_DIMENSIONS(171_101, ErrorType.INFRA_ISSUE),

  // Android Oxygen CUSTOMER_ISSUE Issue: 171_201 ~ 171_300
  ANDROID_OXYGEN_MISSING_PARAMETERS(171_201, ErrorType.CUSTOMER_ISSUE),
  ANDROID_OXYGEN_START_ADB_TUNNEL_ERROR(171_202, ErrorType.INFRA_ISSUE),
  ANDROID_OXYGEN_STOP_ADB_TUNNEL_ERROR(171_203, ErrorType.INFRA_ISSUE),
  ANDROID_OXYGEN_INVALID_DEVICE_ID(171_204, ErrorType.INFRA_ISSUE),
  ANDROID_OXYGEN_USER_NOT_IN_ALLOWLIST(171_205, ErrorType.CUSTOMER_ISSUE),

  // AndroidApolloGmsCoreAndAppDecorator: 172_001 ~ 172_100
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_DEVICE_NOT_FOUND(172_001, ErrorType.INFRA_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_GET_PACKAGE_VERSION_FAIL(172_002, ErrorType.INFRA_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_GET_EN_VERSION_FAIL(172_003, ErrorType.INFRA_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_GET_DIMENSION_FAIL(172_004, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_START_ANUBIS_SERVICE_FAIL(
      172_005, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_START_EN_SERVICE_FAIL(172_006, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_START_GSERVICES_SERVICE_FAIL(
      172_007, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_APK_NOT_FOUND(172_008, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_UNINSTALL_GMSCORE_FAIL(
      172_009, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_INSTALL_GMSCORE_FAIL(172_010, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_TOO_MANY_APKS(172_011, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_INSTALL_NEARBY_APK_FAIL(
      172_012, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_INSTALL_TESTSUPPORT_APK_FAIL(
      172_013, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_INSTALL_TESTSUPPORT_DRIVER_APK_FAIL(
      172_014, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_INSTALL_ANUBIS_APK_FAIL(
      172_015, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_PULL_BLUETOOTH_DB_FILE_FAIL(
      172_016, ErrorType.CUSTOMER_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_GET_VERSIONS_FAIL(172_017, ErrorType.INFRA_ISSUE),
  ANDROID_APOLLO_GMSCORE_AND_APP_DECORATOR_CLEAN_UP_TEST_SUPPORT_FAIL(
      172_018, ErrorType.CUSTOMER_ISSUE),

  // AndroidKibbleDecorator: 173_001 - 173_100
  ANDROID_KIBBLE_START_COLLECTION_FAIL(173_001, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_KIBBLE_STOP_COLLECTION_FAIL(173_002, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_KIBBLE_NO_COLLECTORS_ONLINE(173_003, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_KIBBLE_COLLECTOR_NO_MATCH(173_004, ErrorType.DEPENDENCY_ISSUE),
  ANDROID_KIBBLE_COLLECTOR_TIMEOUT(173_005, ErrorType.DEPENDENCY_ISSUE),

  ANDROID_ERROR_ID_PLACE_HOLDER_TO_BE_RENAMED(200_000, ErrorType.UNDETERMINED);

  public static final int MIN_CODE = ExtErrorId.MAX_CODE + 1;
  public static final int MAX_CODE = 200_000;

  private final int code;
  private final ErrorType type;

  AndroidErrorId(int code, ErrorType type) {
    Preconditions.checkArgument(code >= MIN_CODE);
    Preconditions.checkArgument(code <= MAX_CODE);
    Preconditions.checkArgument(type != ErrorType.UNCLASSIFIED);
    this.code = code;
    this.type = type;
  }

  @Override
  public int code() {
    return code;
  }

  @Override
  public ErrorType type() {
    return type;
  }

  @Override
  public String toString() {
    return ErrorIdFormatter.formatErrorId(this);
  }
}
