/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.devtools.mobileharness.api.model.error;

import com.google.common.base.Preconditions;
import com.google.devtools.common.metrics.stability.model.proto.ErrorTypeProto.ErrorType;
import com.google.devtools.common.metrics.stability.util.ErrorIdFormatter;

/**
 * Extended error IDs for other Mobile Harness platform(iOS, mobly, etc) supports except Android,
 * like utilities, Driver/Decorator, Detector/Device implementations. For Android platform related,
 * check/update in {@link AndroidErrorId} instead.
 *
 * @see <a href="http://go/mh-exception">MH Exception</a> for more detail and guidance
 */
public enum ExtErrorId implements ErrorId {
  // ***********************************************************************************************
  // iOS: 60_001 ~ 80_000
  // ***********************************************************************************************

  // iOS Utils: 60_001 ~ 63_000
  // Misc: 60_001 ~ 61_000
  IOS_SIGN_FILE_LOCK_ERROR(60_001, ErrorType.INFRA_ISSUE),
  IOS_HANDLE_TEST_FILE_ERROR(60_002, ErrorType.INFRA_ISSUE),
  IOS_XCODE_ERROR(60_003, ErrorType.INFRA_ISSUE),
  IOS_NUMBER_FORMAT_ERROR(60_004, ErrorType.INFRA_ISSUE),
  IOS_DISK_IMAGE_NOT_FOUND(60_005, ErrorType.INFRA_ISSUE),
  IOS_PLIST_PARSE_ERROR(60_006, ErrorType.INFRA_ISSUE),
  IOS_BUILT_IN_XCTEST_ERROR(60_007, ErrorType.INFRA_ISSUE),
  IOS_PROVISIONING_PROFILE_PARSE_ERROR(60_008, ErrorType.INFRA_ISSUE),
  IOS_FFMPEG_GET_VIDEO_DURATION_ERROR(60_009, ErrorType.INFRA_ISSUE),
  IOS_SPONGE_PARSING_ERROR(60_010, ErrorType.INFRA_ISSUE),

  // iOS app: 61_001 ~ 62_000
  // iOS app info: 61_001 ~ 61_200
  IOS_APP_MINIMUM_OS_VERSION_NOT_MATCH(61_001, ErrorType.CUSTOMER_ISSUE),
  IOS_BUNDLE_ARCHITECTURE_NOT_MATCH(61_002, ErrorType.CUSTOMER_ISSUE),
  IOS_APP_FILE_TYPE_NOT_MATCH(61_003, ErrorType.CUSTOMER_ISSUE),
  IOS_APP_INFO_ERROR(61_004, ErrorType.CUSTOMER_ISSUE),
  IOS_APP_EXTRACT_ERROR(61_005, ErrorType.CUSTOMER_ISSUE),
  IOS_APP_SIGNING_ERROR(61_006, ErrorType.INFRA_ISSUE),
  IOS_APP_ARCHITECTURE_ERROR(61_007, ErrorType.CUSTOMER_ISSUE),
  IOS_BUNDLE_NOT_CODESIGN_ERROR(61_008, ErrorType.CUSTOMER_ISSUE),
  IOS_DEVICE_IDENTITY_INVALID(61_009, ErrorType.DEPENDENCY_ISSUE),
  IOS_DEVICE_IDENTITY_ALLOCATION_NOT_MATCHED(61_010, ErrorType.INFRA_ISSUE),
  IOS_APP_CRASH_ERROR(61_011, ErrorType.CUSTOMER_ISSUE),
  IOS_SIGNING_IDENTITY_NOT_SUPPORT(61_012, ErrorType.INFRA_ISSUE),

  // iOS MH daemon: 61_201 ~ 61_300
  IOS_DAEMON_APP_ERROR(61_201, ErrorType.INFRA_ISSUE),
  IOS_DAEMON_APP_GET_IP_ADDRESS_ERROR(61_202, ErrorType.INFRA_ISSUE),
  IOS_DAEMON_APP_GET_WIFI_STABILITY_ERROR(61_203, ErrorType.INFRA_ISSUE),

  // iOS Devices: 62_001 ~ 63_000
  IOS_LAUNCH_APP_TIMEOUT_ERROR(62_001, ErrorType.DEPENDENCY_ISSUE),
  IOS_LAUNCH_APP_NOT_START_FAILED(62_002, ErrorType.CUSTOMER_ISSUE),
  IOS_TERMINATE_APP_ERROR(62_003, ErrorType.INFRA_ISSUE),
  IOS_REBOOT_DEVICE_ERROR(62_004, ErrorType.INFRA_ISSUE),
  IOS_WAIT_FOR_DEVICE_WARMUP_ERROR(62_005, ErrorType.INFRA_ISSUE),
  IOS_LAUNCH_APP_ERROR(62_006, ErrorType.CUSTOMER_ISSUE),
  IOS_DEVICE_WIFI_DISCONNECTED(62_007, ErrorType.CUSTOMER_ISSUE),
  IOS_DEVICE_GET_ARCHITECTURE_PARSE(62_008, ErrorType.INFRA_ISSUE),
  IOS_LAUNCH_APP_SUCCESS_AND_TIMEOUT_ERROR(62_009, ErrorType.UNDETERMINED),

  // iOS Real Devices: 63_001 ~ 63_500
  // General iOS real devices: 63_001 ~ 63_400
  IOS_REAL_DEVICE_BLOCK_OS_UPGRADE_EXPECTED_ERROR(63_001, ErrorType.INFRA_ISSUE),
  IOS_REAL_DEVICE_BUSY_STATUS(63_002, ErrorType.DEPENDENCY_ISSUE),
  IOS_CFGUTIL_UTIL_BIN_INIT_ERROR(63_003, ErrorType.INFRA_ISSUE),
  IOS_CFGUTIL_DEPLOYMENT_ERROR(63_004, ErrorType.CUSTOMER_ISSUE),
  IOS_CFGUTIL_COMMAND_ERROR(63_005, ErrorType.DEPENDENCY_ISSUE),
  IOS_SET_WIFI_ERROR(63_006, ErrorType.DEPENDENCY_ISSUE),
  IOS_REMOVE_WIFI_ERROR(63_007, ErrorType.DEPENDENCY_ISSUE),
  IOS_SET_PROXY_ERROR(63_008, ErrorType.DEPENDENCY_ISSUE),
  IOS_REMOVE_PROXY_ERROR(63_009, ErrorType.DEPENDENCY_ISSUE),
  IOS_DEVICE_NOT_WIRELESS_CONNECTED(63_010, ErrorType.INFRA_ISSUE),
  IOS_DEVICE_NOT_USB_CONNECTED(63_011, ErrorType.INFRA_ISSUE),
  IOS_DEVICE_EMPTY_ARCHITECTURE_DIMENSION(63_012, ErrorType.INFRA_ISSUE),
  IOS_SCREEN_ROTATION_LOCK_ERROR(63_013, ErrorType.INFRA_ISSUE),

  // idevice tools: 63_401_63_500
  IDEVICEDIAGNOSTICS_GET_TEMPERATURE_ERROR(63_401, ErrorType.DEPENDENCY_ISSUE),
  IDEVICEFS_ACCESS_DIR_PERMISSION_DENIED(63_402, ErrorType.DEPENDENCY_ISSUE),
  IDEVICEINSTALLER_INSTALL_APP_VERIFICATION_FAILED(64_003, ErrorType.CUSTOMER_ISSUE),
  IDEVICEINSTALLER_INSTALL_APP_FAILED(63_404, ErrorType.DEPENDENCY_ISSUE),
  IDEVICEINSTALLER_UNINSTALL_APP_FAILED(63_405, ErrorType.DEPENDENCY_ISSUE),
  IDEVICEINSTALLER_APP_INFO_PARSE_ERROR(63_406, ErrorType.DEPENDENCY_ISSUE),
  IDEVICEAPPRUNNER_ATTACH_APP_ERROR(63_407, ErrorType.DEPENDENCY_ISSUE),
  IDEVICEAPPRUNNER_APP_NOT_INSTALLED_ERROR(63_408, ErrorType.DEPENDENCY_ISSUE),
  IDEVICESCREENSHOT_ERROR(63_409, ErrorType.DEPENDENCY_ISSUE),
  IDEVICEIMAGEMOUNTER_MOUNT_DEVICE_ERROR(63_410, ErrorType.DEPENDENCY_ISSUE),
  IDEVICEINFO_GET_PROPERTY_ERROR(63_411, ErrorType.DEPENDENCY_ISSUE),
  IDEVICE_DEVICE_NOT_FOUND(63_412, ErrorType.DEPENDENCY_ISSUE),
  IDEVICEINSTALLER_NO_MATCHING_APP_INFO(63_413, ErrorType.DEPENDENCY_ISSUE),
  IDEVICEINFO_PARSE_SYSTEM_TIME_ERROR(63_414, ErrorType.DEPENDENCY_ISSUE),
  IDEVICESCREENSHOT_COUND_NOT_GET_SCREENSHOT(63_415, ErrorType.DEPENDENCY_ISSUE),
  IDEVICE_LOCKDOWND_MUX_ERROR(63_416, ErrorType.DEPENDENCY_ISSUE),
  IDEVICEAPPRUNNER_SEND_RECV_ERROR(63_417, ErrorType.INFRA_ISSUE),

  // iOS Simulator: 63_501 ~ 64_000
  // General iOS simulator: 63_501 ~ 63_600
  IOS_SIM_STATE_ERROR(63_501, ErrorType.DEPENDENCY_ISSUE),
  IOS_SIM_WARM_UP_TIMEOUT(63_502, ErrorType.DEPENDENCY_ISSUE),
  IOS_SIM_FETCH_LOG_ERROR(63_503, ErrorType.DEPENDENCY_ISSUE),
  IOS_CORESIMULATOR_ERROR(63_504, ErrorType.DEPENDENCY_ISSUE),
  IOS_SIM_ASYNC_RUN_APP_NOT_IMPLEMENTED(63_505, ErrorType.INFRA_ISSUE),
  IOS_SIM_FORWARD_PORT_ERROR(63_506, ErrorType.INFRA_ISSUE),
  IOS_NO_BOOTED_SIM_ERROR(63_507, ErrorType.INFRA_ISSUE),
  IOS_SIM_SET_LOCATION_NOT_IMPLEMENTED(63_508, ErrorType.INFRA_ISSUE),
  IOS_SIM_RESET_LOCATION_NOT_IMPLEMENTED(63_509, ErrorType.INFRA_ISSUE),

  // simctl: 63_601 ~ 63_700
  IOS_SIMCTL_ERROR(63_601, ErrorType.DEPENDENCY_ISSUE),
  IOS_SIMCTL_TIMEOUT(63_602, ErrorType.DEPENDENCY_ISSUE),
  IOS_SIMCTL_BOOT_ERROR(63_603, ErrorType.DEPENDENCY_ISSUE),
  IOS_SIMCTL_LAUNCH_APP_ERROR(63_604, ErrorType.DEPENDENCY_ISSUE),
  IOS_SIMCTL_LIST_ERROR(63_605, ErrorType.DEPENDENCY_ISSUE),
  IOS_SIMCTL_SHUTDOWN_ERROR(63_606, ErrorType.DEPENDENCY_ISSUE),
  IOS_SIMCTL_GET_APP_INFO_ERROR(63_607, ErrorType.DEPENDENCY_ISSUE),
  IOS_SIMCTL_BOOT_TIMEOUT_ERROR(63_608, ErrorType.DEPENDENCY_ISSUE),

  // iOS Drivers: 64_001 ~ 65_000
  // IosLaunchAppDriver: 64_001 ~ 64_100
  IOS_LAUNCH_APP_DRIVER_SIGNAL_ERROR(64_001, ErrorType.CUSTOMER_ISSUE),
  IOS_LAUNCH_APP_DRIVER_LAUNCH_SIGNAL_NOT_FOUND_ERROR(64_002, ErrorType.CUSTOMER_ISSUE),

  // iOS testing drivers 64_101 ~ 64_200
  IOS_XCTEST_RUNNER_QUOTA_ERROR(64_101, ErrorType.INFRA_ISSUE),
  IOS_XCTEST_NOT_FOUND(64_102, ErrorType.INFRA_ISSUE),
  IOS_XCTEST_NEED_NEW_SIM_ERROR(64_103, ErrorType.DEPENDENCY_ISSUE),
  IOS_TEST_CASE_NOT_FOUND(64_104, ErrorType.CUSTOMER_ISSUE),
  IOS_XCTEST_FILE_NAME_INVALID(64_105, ErrorType.CUSTOMER_ISSUE),
  IOS_XCTEST_LIST_TESTS_ERROR(64_106, ErrorType.INFRA_ISSUE),
  IOS_KIF_LIST_TESTS_ERROR(64_107, ErrorType.INFRA_ISSUE),
  IOS_GUNIT_CONVERT_TEST_APP_ERROR(64_108, ErrorType.INFRA_ISSUE),
  IOS_XCTEST_FAIL(64_109, ErrorType.CUSTOMER_ISSUE),
  IOS_KIF_FAIL(64_110, ErrorType.CUSTOMER_ISSUE),
  IOS_XCTEST_TEST_NOT_START(64_111, ErrorType.INFRA_ISSUE),
  IOS_XCODEBUILD_TEST_RUNNER_EXITED_BEFORE_TEST_EXECUTION(64_112, ErrorType.DEPENDENCY_ISSUE),
  IOS_XCODEBUILD_DESTINATION_SPECIFIER_NOT_MATCH(64_113, ErrorType.INFRA_ISSUE),
  IOS_XCTEST_EXECUTOR_WORK_DIR_MISSING(64_114, ErrorType.INFRA_ISSUE),
  IOS_XCTEST_TIMEOUT(64_115, ErrorType.CUSTOMER_ISSUE),
  IOS_XCTEST_FAIL_WITH_LOST_CONNECTION(64_116, ErrorType.INFRA_ISSUE),
  IOS_XCTEST_BUNDLER_DAMAGED(64_117, ErrorType.CUSTOMER_ISSUE),
  IOS_XCTEST_FAIL_WITH_NO_VALID_PROVISIONING_PROFILE(64_118, ErrorType.UNDETERMINED),
  IOS_GUNIT_TEST_FAILED(64_119, ErrorType.INFRA_ISSUE),
  IOS_GUNIT_TEST_ERROR(64_120, ErrorType.UNDETERMINED),
  IOS_XCODEBUILD_UNABLE_FIND_DEVICE(64_121, ErrorType.INFRA_ISSUE),
  IOS_XCODEBUILD_FAILED_TO_LOAD_TEST_BUNDLE(64_122, ErrorType.CUSTOMER_ISSUE),
  IOS_XCTEST_FAIL_WITH_APP_CRASHED_AND_DISCONNECTED(64_123, ErrorType.CUSTOMER_ISSUE),
  IOS_XCTEST_CRASH_ERROR(64_124, ErrorType.CUSTOMER_ISSUE),

  // iOS Decorators: 65_001 ~ 67_000
  // IosFilePullerDecorator: 65_001 ~ 65_100
  IOS_FILE_PULLER_DECORATOR_PULL_FILE_FAIL(65_001, ErrorType.CUSTOMER_ISSUE),

  // IosPerformanceDecorator: 65_101 ~ 65_200
  IOS_PERFORMANCE_DECORATOR_APP_NOT_INSTALLED_ERROR(65_101, ErrorType.DEPENDENCY_ISSUE),
  IOS_PERFORMANCE_LOGGER_FAILURE(65_102, ErrorType.INFRA_ISSUE),
  IOS_PERFORMANCE_SUBTEST_ERROR(65_103, ErrorType.UNDETERMINED),
  IOS_PERFORMANCE_TEST_FAILURE(65_104, ErrorType.CUSTOMER_ISSUE),

  // IosRealDeviceScreenRecorderDecorator: 65_201 ~ 65_210
  IOS_BUILT_IN_SCREEN_RECORDER_ERROR(65_201, ErrorType.INFRA_ISSUE),
  IOS_BUILT_IN_SCREEN_RECORDER_ENVIRONMENT_NOT_SUPPORTED(65_202, ErrorType.INFRA_ISSUE),
  IOS_SCREENSHOT_RECORDER_NOT_STARTED_CAPACITY_ISSUE(65_203, ErrorType.DEPENDENCY_ISSUE),
  IOS_SCREEN_RECORDER_BROADCAST_APP_INIT_ERROR(65_204, ErrorType.INFRA_ISSUE),
  IOS_SCREEN_RECORDER_V3_START_RECORDER_ERROR(65_205, ErrorType.INFRA_ISSUE),
  IOS_SCREEN_RECORDER_V3_STOP_RECORDER_ERROR(65_206, ErrorType.INFRA_ISSUE),
  IOS_SCREEN_RECORDER_V3_VIDEO_FILE_ERROR(65_207, ErrorType.INFRA_ISSUE),
  IOS_SCREEN_RECORDER_BROADCAST_APP_INVALID(65_208, ErrorType.INFRA_ISSUE),
  IOS_SCREEN_RECORDER_BUILT_IN_TEST_ARTIFACT_INVALID(65_209, ErrorType.INFRA_ISSUE),

  // IosGoogleAccountDecorator: 65_211 ~ 65_220
  IOS_GOOGLE_ACCOUNT_DECORATOR_WIPEOUT_ERROR(65_211, ErrorType.INFRA_ISSUE),
  IOS_GOOGLE_ACCOUNT_DECORATOR_SIGNIN_FAILURE(65_212, ErrorType.INFRA_ISSUE),
  IOS_GOOGLE_ACCOUNT_DECORATOR_INSTALL_APP_ERROR_RECOVERED_BY_REBOOT(65_213, ErrorType.INFRA_ISSUE),
  IOS_GOOGLE_ACCOUNT_BUILT_IN_TEST_ARTIFACT_INVALID(65_214, ErrorType.INFRA_ISSUE),

  // IosLocationDecorator: 65_221 ~ 65_230
  IOS_LOCATION_DECORATOR_INVALID_PARAMS(65_221, ErrorType.CUSTOMER_ISSUE),

  // IosLazyProxyDecorator: 65_231 ~ 65_240
  IOS_LAZYPROXY_LOCALHOST_IP_ERROR(65_231, ErrorType.DEPENDENCY_ISSUE),
  IOS_LAZYPROXY_INSTALL_CACERT_ERROR(65_232, ErrorType.DEPENDENCY_ISSUE),
  IOS_LAZYPROXY_CACERTKEY_READ_ERROR(65_233, ErrorType.DEPENDENCY_ISSUE),

  // IosRealDeviceSettingsDecorator: 65_241 ~ 65_250
  IOS_SETTINGS_DECORATOR_AUTOLOCK_FAILURE(65_241, ErrorType.INFRA_ISSUE),

  // iOS performance: 67_001 ~ 67_500
  // Misc: 67_001 ~ 67_100
  IOS_PERFORMANCE_REGRESSION(67_001, ErrorType.CUSTOMER_ISSUE),
  IOS_DYLD_PARSER_UNABLE_TO_PARSE(67_002, ErrorType.INFRA_ISSUE),
  IOS_DYLD_PARSER_OS_VERSION_NOT_SUPPORT(67_003, ErrorType.CUSTOMER_ISSUE),

  // iOS Monsoon: 67_101 ~ 67_200
  IOS_MONSOON_DEVICE_NOT_CONNECTED(67_101, ErrorType.INFRA_ISSUE),
  IOS_MONSOON_TEST_PASS_SIGNAL_NOT_FOUND(67_102, ErrorType.CUSTOMER_ISSUE),
  IOS_MONSOON_DEVICE_NOT_SUPPORTED(67_103, ErrorType.CUSTOMER_ISSUE),
  IOS_MONSOON_PARSE_TIMESTAMP_ERROR(67_106, ErrorType.INFRA_ISSUE),
  IOS_MONSOON_NO_TEST_END_TIMESTAMP(67_107, ErrorType.CUSTOMER_ISSUE),

  // Mac status 70_001 ~ 71_000:
  MAC_CERTIFICATE_INVALID(70_001, ErrorType.INFRA_ISSUE),
  MAC_CREATE_TEMP_FILE_ERROR(70_002, ErrorType.INFRA_ISSUE),

  // ***********************************************************************************************
  // Other Platforms: 80_001 ~ 100_000
  // ***********************************************************************************************

  // Monsoon: 80_001 ~ 80_500
  // Monsoon lab related issues 80_001 ~ 80_100:
  MONSOON_OVERMUCH_DIMENSION(80_001, ErrorType.CUSTOMER_ISSUE),
  MONSOON_MISSING_DIMENSION(80_002, ErrorType.CUSTOMER_ISSUE),
  MONSOON_NO_ENOUGH_TIME(80_003, ErrorType.CUSTOMER_ISSUE),
  MONSOON_DEVICE_NOT_SUPPORTED(80_004, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_SERIAL_NUMBER_ERROR(80_005, ErrorType.CUSTOMER_ISSUE),
  MONSOON_ONLY_SUPPORT_HVPM(80_006, ErrorType.CUSTOMER_ISSUE),

  // Monsoon operation issues 80_101 ~ 80_300:
  MONSOON_LOG_FILE_NOT_FOUND(80_101, ErrorType.INFRA_ISSUE),
  MONSOON_LOG_FILE_EMPTY(80_102, ErrorType.INFRA_ISSUE),
  MONSOON_GET_STATUS_ERROR(80_103, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_CREATE_LOG_FILE_ERROR(80_104, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_COMBINE_SPEC_ERROR(80_105, ErrorType.CUSTOMER_ISSUE),
  MONSOON_RUN_TEST_ERROR(80_106, ErrorType.INFRA_ISSUE),
  MONSOON_FIND_GEN_FILE_DIR_ERROR(80_107, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_GENERATE_SUMMARY_PERFGATE_FILE_ERROR(80_108, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_CLIENT_CONNECT_BACK_ERROR(80_109, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_PROCESS_INSTRUMENT_ERROR(80_110, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_SYNC_MONITOR_ERROR(80_111, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_ASYNC_MONITOR_ERROR(80_112, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_CLEAR_CLIENT_LOG_ERROR(80_113, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_GENERATE_RAW_DATA_PERFGATE_FILE_ERROR(80_114, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_RUN_COMMAND_FAILED(80_115, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_RUN_ASYNC_COMMAND_FAILED(80_116, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_RUN_COMMAND_SET_VOLTAGE_FAILED(80_117, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_RUN_COMMAND_SET_CURRENT_FAILED(80_118, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_RUN_COMMAND_SET_START_CURRENT_FAILED(80_119, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_RUN_COMMAND_TURN_OFF_USB_FAILED(80_120, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_RUN_COMMAND_TURN_ON_USB_FAILED(80_121, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_RUN_COMMAND_MONITOR_FAILED(80_122, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_RUN_COMMAND_ASYNC_MONITOR_FAILED(80_123, ErrorType.DEPENDENCY_ISSUE),

  // Monsoon test issues 80_301 ~ 80_400:
  MONSOON_TEST_GET_ANDROID_LOGCAT_ERROR(80_301, ErrorType.DEPENDENCY_ISSUE),
  MONSOON_TEST_NO_PASS_SIGNAL(80_302, ErrorType.CUSTOMER_ISSUE),
  MONSOON_UNRELATED_TEST_FAIL_SIGNAL(80_303, ErrorType.CUSTOMER_ISSUE),

  // Bluetooth Low Energy: 80_501 ~ 80_600
  BLE_CHECK_TOOL_ERROR(80_501, ErrorType.DEPENDENCY_ISSUE),
  BLE_CHECK_ADAPTER_ERROR(80_502, ErrorType.DEPENDENCY_ISSUE),
  BLE_SCAN_DEVICE_ERROR(80_503, ErrorType.DEPENDENCY_ISSUE),
  BLE_DEVICE_NOT_FOUND(80_504, ErrorType.DEPENDENCY_ISSUE),
  BLE_INTERACT_WITH_DEVICE_ERROR(80_505, ErrorType.DEPENDENCY_ISSUE),
  BLE_RESET_DEVICE_ERROR(80_506, ErrorType.DEPENDENCY_ISSUE),

  // Mac Resource files: 80_901 ~ 81_000
  MAC_RES_NOT_FOUND(80_901, ErrorType.UNDETERMINED),

  // Mobly: 81_001 ~ 81_100
  MOBLY_SPONGE_OUTPUT_PARSING_ERROR(81_001, ErrorType.CUSTOMER_ISSUE),
  MOBLY_TESTBED_SUBDEVICE_CALLABLE_ERROR(81_002, ErrorType.INFRA_ISSUE),
  MOBLY_TESTBED_ADHOC_DRIVER_END_WITH_UNKNOWN_RESULT(81_003, ErrorType.INFRA_ISSUE),
  MOBLY_FAILED_TO_FIND_CONFIG_FILE_ERROR(81_004, ErrorType.CUSTOMER_ISSUE),
  MOBLY_FAILED_TO_READ_TESTBED_CONFIG_ERROR(81_005, ErrorType.CUSTOMER_ISSUE),
  MOBLY_TESTBED_CONFIG_MISSING_KEY_ERROR(81_006, ErrorType.CUSTOMER_ISSUE),
  MOBLY_TESTBED_CONFIG_PARSING_ERROR(81_007, ErrorType.CUSTOMER_ISSUE),
  MOBLY_INVALID_TESTBED_MODEL_CONFIG_ERROR(81_008, ErrorType.CUSTOMER_ISSUE),
  MOBLY_INVALID_TESTBED_CONTROLLER_CONFIG_ERROR(81_009, ErrorType.CUSTOMER_ISSUE),
  MOBLY_CONFIG_GENERATION_ERROR(81_010, ErrorType.CUSTOMER_ISSUE),
  MOBLY_FAILED_TO_CREATE_TEMP_DIRECTORY_ERROR(81_011, ErrorType.CUSTOMER_ISSUE),
  MOBLY_TESTBED_NAME_EMPTY_ERROR(81_012, ErrorType.CUSTOMER_ISSUE),
  MOBLY_EXECUTE_ERROR(81_013, ErrorType.UNDETERMINED),
  MOBLY_OUTPUT_PARSING_ERROR(81_014, ErrorType.INFRA_ISSUE),
  MOBLY_MISC_TESTBED_SUBDEVICE_JSON_TYPE_NAME_ERROR(81_015, ErrorType.INFRA_ISSUE),
  MOBLY_SUBDEVICE_TYPE_NOT_FOUND_ERROR(81_016, ErrorType.INFRA_ISSUE),
  MOBLY_TESTBED_ADHOC_DRIVER_SUBTEST_WITH_INFRA_ERROR_RESULT(81_017, ErrorType.INFRA_ISSUE),
  MOBLY_TESTBED_ADHOC_DRIVER_SUBTEST_WITH_DEPENDENCY_ERROR_RESULT(
      81_018, ErrorType.DEPENDENCY_ISSUE),
  MOBLY_TESTBED_ADHOC_DRIVER_SUBTEST_WITH_CUSTOMER_ERROR_RESULT(81_019, ErrorType.CUSTOMER_ISSUE),
  MOBLY_TESTBED_ADHOC_DRIVER_SUBTEST_WITH_UNDETERMINED_ERROR_RESULT(81_020, ErrorType.UNDETERMINED),
  MOBLY_TESTBED_ADHOC_DRIVER_SUBTEST_WITH_FAIL_RESULT(81_021, ErrorType.CUSTOMER_ISSUE),
  MOBLY_TEST_FAILURE(81_022, ErrorType.CUSTOMER_ISSUE),
  MOBLY_TEST_TIMEOUT(81_023, ErrorType.CUSTOMER_ISSUE),
  MOBLY_TEST_SUMMARY_YAML_PARSING_ERROR(81_024, ErrorType.INFRA_ISSUE),
  MOBLY_TEST_SCRIPT_ERROR(81_025, ErrorType.CUSTOMER_ISSUE),
  MOBLY_COMMAND_OUTPUT_EMPTY(81_026, ErrorType.INFRA_ISSUE),
  MOBLY_FAILED_TO_READ_COMMAND_OUTPUT(81_027, ErrorType.INFRA_ISSUE),
  MOBLY_TEST_CASE_FAILURE(81_028, ErrorType.CUSTOMER_ISSUE),
  MOBLY_TEST_CASE_ERROR(81_029, ErrorType.CUSTOMER_ISSUE),
  MOBLY_TEST_CASE_SKIPPED(81_030, ErrorType.CUSTOMER_ISSUE),
  MOBLY_TEST_SUMMARY_YAML_CONVERT_XML_ERROR(81_031, ErrorType.INFRA_ISSUE),

  MOBLY_AOSP_CREATE_VENV_ERROR(81_081, ErrorType.INFRA_ISSUE),
  MOBLY_AOSP_PYTHON_VERSION_NOT_FOUND_ERROR(81_082, ErrorType.INFRA_ISSUE),
  MOBLY_AOSP_UNZIP_TEST_PACKAGE_ERROR(81_083, ErrorType.CUSTOMER_ISSUE),
  MOBLY_AOSP_RESOLVE_TEST_PATH_ERROR(81_084, ErrorType.CUSTOMER_ISSUE),
  MOBLY_AOSP_PIP_INSTALL_ERROR(81_085, ErrorType.CUSTOMER_ISSUE),

  // Available: 81_101 ~ 81_200

  // Flutter Driver: 81_201 ~ 81_300
  FLUTTER_DRIVER_TEST_FAIL(81_201, ErrorType.CUSTOMER_ISSUE),
  FLUTTER_DRIVER_TEST_PRE_RUN_FAILURE(81_202, ErrorType.CUSTOMER_ISSUE),
  FLUTTER_DRIVER_TEST_POST_RUN_FAILURE(81_203, ErrorType.CUSTOMER_ISSUE),
  FLUTTER_DRIVER_TEST_UNSUPPORTED_DEVICE(81_204, ErrorType.CUSTOMER_ISSUE),
  FLUTTER_DRIVER_ANDROID_APP_START_FAILURE(81_205, ErrorType.CUSTOMER_ISSUE),
  FLUTTER_DRIVER_ANDROID_TEST_PORT_FORWARD_ERROR(81_206, ErrorType.CUSTOMER_ISSUE),
  FLUTTER_DRIVER_IOS_APP_ERROR(81_207, ErrorType.CUSTOMER_ISSUE),

  // Concord Testing Framework: 81_301 ~ 81_600
  CONCORD_START_EMULATOR_ERROR(81_301, ErrorType.UNDETERMINED),

  // Android test target parser: 81_601 ~ 81_700
  ANDROID_TEST_PARSER_NOT_ANDROID_TEST(81_601, ErrorType.CUSTOMER_ISSUE),
  ANDROID_TEST_PARSER_NO_TEST_APK_GENERATED(81_602, ErrorType.CUSTOMER_ISSUE),
  ANDROID_TEST_PARSER_NO_BINARY_UNDER_TEST(81_603, ErrorType.CUSTOMER_ISSUE),
  ANDROID_TEST_PARSER_BINARY_UNDER_TEST_IS_NOT_ANDROID_BINARY(81_604, ErrorType.CUSTOMER_ISSUE),
  ANDROID_TEST_PARSER_NO_BINARY_APK_GENERATED(81_605, ErrorType.CUSTOMER_ISSUE),
  ANDROID_TEST_PARSER_NO_TARGET_DEVICE_ASSIGNED(81_606, ErrorType.CUSTOMER_ISSUE),
  ANDROID_TEST_PARSER_INVALID_TARGET_DEVICE(81_607, ErrorType.CUSTOMER_ISSUE),

  // Copycat: 81_701 ~ 81_800
  COPYCAT_MOBLY_SNIPPET_NO_FREE_PORT_ERROR(81_701, ErrorType.DEPENDENCY_ISSUE),
  COPYCAT_MOBLY_SNIPPET_LOGCAT_INACCESSIBLE_ERROR(81_702, ErrorType.DEPENDENCY_ISSUE),
  COPYCAT_MOBLY_SNIPPET_PORT_NOT_FOUND_IN_LOGCAT_ERROR(81_703, ErrorType.DEPENDENCY_ISSUE),
  COPYCAT_MOBLY_SNIPPET_PORT_FORWARD_ERROR(81_704, ErrorType.DEPENDENCY_ISSUE),
  COPYCAT_MOBLY_SNIPPET_HOST_NOT_FOUND_ERROR(81_705, ErrorType.DEPENDENCY_ISSUE),
  COPYCAT_MOBLY_SNIPPET_UNEXPECTED_END_OF_STREAM_ERROR(81_706, ErrorType.DEPENDENCY_ISSUE),
  COPYCAT_MOBLY_SNIPPET_JSON_PARSE_ERROR(81_707, ErrorType.DEPENDENCY_ISSUE),
  COPYCAT_MOBLY_SNIPPET_REMOTE_INIT_ERROR(81_708, ErrorType.DEPENDENCY_ISSUE),
  COPYCAT_MOBLY_SNIPPET_PORT_CLOSE_ERROR(81_709, ErrorType.DEPENDENCY_ISSUE),
  COPYCAT_MOBLY_SNIPPET_REMOTE_STOP_ERROR(81_710, ErrorType.DEPENDENCY_ISSUE),
  COPYCAT_MOBLY_SNIPPET_SOCKET_CLOSED_ERROR(81_711, ErrorType.DEPENDENCY_ISSUE),

  // FuchsiaTesting: 81_801 - 82_800
  // Fuchsia platform tools 81_801 - 82_000
  FUCHSIA_HOST_COMMAND_NETLS_EXECUTION_ERROR(81_803, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_HOST_COMMAND_PM_EXECUTION_ERROR(81_804, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_HOST_COMMAND_SHELL_EXECUTION_ERROR(81_805, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_SSH_PRIVATE_KEY_GENERATE_ERROR(81_806, ErrorType.INFRA_ISSUE),
  FUCHSIA_SSH_AUTHORIZED_KEYS_GENERATE_ERROR(81_807, ErrorType.INFRA_ISSUE),
  FUCHSIA_HOST_COMMAND_DEVICE_FINDER_OUTPUT_PARSE_ERROR(81_808, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_HOST_COMMAND_PM_START_SERVE(81_809, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_HOST_COMMAND_PM_STOP_PROCESS(81_810, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_PACKAGE_MANAGER_PUBLISH_ERROR(81_811, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_PACKAGE_MANAGER_START_SERVE_ERROR(81_812, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_COMMAND_GET_PACKAGE_TESTS_ERROR(81_813, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_COMMAND_RUN_PACKAGE_ERROR(81_814, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_COMMAND_AMBERCTL_ADD_SOURCE_ERROR(81_815, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_COMMAND_PKGCTL_ADD_URL_ERROR(81_816, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_HOST_COMMAND_FAR_EXTRACT_ERROR(81_818, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_HOST_COMMAND_FAR_LIST_ERROR(81_819, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_HOST_COMMAND_FAR_CAT_ERROR(81_820, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_PACKAGE_READER_PACKAGE_NAME_NOT_FOUND_ERROR(81_821, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_PACKAGE_READER_COMPONENT_MANIFEST_NOT_FOUND_ERROR(81_822, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_PACKAGE_READER_EXTRACT_ERROR(81_823, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_COMMAND_TILES_START_ERROR(81_824, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_COMMAND_TILES_ADD_ERROR(81_825, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_COMMAND_OBSERVATORY_PORT_NOT_FOUND(81_826, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_COMMAND_PORT_FORWARD_ERROR(81_827, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_HOST_COMMAND_EXECUTION_ERROR(81_828, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_PAVE_TAR_EXTRACT_ERROR(81_829, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_PAVE_COPY_IMAGES_FROM_GCS_ERROR(81_830, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_MODULE_PROVISION_ERROR_RESOURCE_NOT_FOUND(81_831, ErrorType.INFRA_ISSUE),
  FUCHSIA_DEVICE_COMMAND_SESSION_RESTART_ERROR(81_832, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_COMMAND_SESSION_LOGIN_ERROR(81_833, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_INVALID_SSH_PRIVATE_KEY_ERROR(81_835, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_PAVE_BUILD_ID_ERROR(81_836, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_HOST_COMMAND_DEV_FINDER_EXECUTION_ERROR(81_837, ErrorType.INFRA_ISSUE),
  FUCHSIA_LOCK_UTIL_ACQUIRE_LOCK_ERROR(81_838, ErrorType.INFRA_ISSUE),
  FUCHSIA_LOCK_UTIL_RELEASE_LOCK_ERROR(81_839, ErrorType.INFRA_ISSUE),
  FUCHSIA_LOG_LISTENER_START_PROCESS_ERROR(81_840, ErrorType.INFRA_ISSUE),
  FUCHSIA_LOG_LISTENER_STOP_PROCESS_ERROR(81_841, ErrorType.INFRA_ISSUE),
  FUCHSIA_ZIRCON_LOG_LISTENER_START_PROCESS_ERROR(81_842, ErrorType.INFRA_ISSUE),
  FUCHSIA_ZIRCON_LOG_LISTENER_STOP_PROCESS_ERROR(81_843, ErrorType.INFRA_ISSUE),
  FUCHSIA_PACKAGE_MANAGER_INVALID_REPO_PATH(81_844, ErrorType.INFRA_ISSUE),
  FUCHSIA_SDK_PACKAGES_UNEXPECTED_FORMAT(81_845, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_LOG_LISTENER_LOG_WRITER_ERROR(81_846, ErrorType.INFRA_ISSUE),
  FUCHSIA_SSH_AGENT_NOT_FOUND_ERROR(81_847, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_SSH_ADD_ERROR(81_848, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_PAVE_BOOTSERVER_TIMEOUT(81_849, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_HOST_COMMAND_AMTCTRL_ERROR(81_850, ErrorType.INFRA_ISSUE),
  FUCHSIA_HOST_COMMAND_AMT_UNSUPPORTED_ERROR(81_851, ErrorType.INFRA_ISSUE),
  FUCHSIA_HOST_COMMAND_SCP_EXECUTION_ERROR(81_852, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_FILE_UTIL_FILE_NOT_EXIST_ERROR(81_853, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_FILE_SCP_FROM_DEVICE_ERROR(81_854, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_DEVICE_COMMAND_WLAN_CONNECT_ERROR(81_855, ErrorType.INFRA_ISSUE),
  FUCHSIA_DEVICE_COMMAND_NET_IF_LIST_PARSE_ERROR(81_860, ErrorType.INFRA_ISSUE),
  FUCHSIA_DEVICE_COMMAND_NET_IF_LIST_EMPTY_OUTPUT_ERROR(81_861, ErrorType.INFRA_ISSUE),
  FUCHSIA_SYMBOLIZE_TEMP_FILE_IO_ERROR(81_862, ErrorType.INFRA_ISSUE),
  FUCHSIA_SYMBOLIZE_SYMBOLS_CACHE_PREPARE_ERROR(81_863, ErrorType.INFRA_ISSUE),
  FUCHSIA_SYMBOLIZE_INPUT_FILE_IO_ERROR(81_864, ErrorType.INFRA_ISSUE),
  FUCHSIA_SYMBOLIZE_PROC_STDIN_IO_ERROR(81_865, ErrorType.INFRA_ISSUE),
  FUCHSIA_SDK_IMAGE_NOT_FOUND_ERROR(81_866, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_SDK_PACKAGES_NOT_FOUND_ERROR(81_867, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_HOST_COMMAND_GRPC_GETIPV6_OUTPUT_PARSE_ERROR(81_868, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_GCS_BUCKET_NOT_FOUND_ERROR(81_869, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_HOST_COMMAND_FFX_EXECUTION_ERROR(81_870, ErrorType.INFRA_ISSUE),
  FUCHSIA_FFX_PACKAGE_SERVER_MULTIPLE_REPOSITORY_ERROR(81_871, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_HOST_COMMAND_PORT_NOT_FOUND_ERROR(81_872, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_PACKAGE_MANAGER_URL_ERROR(81_873, ErrorType.CUSTOMER_ISSUE),

  // Fuchsia device management 82_001 - 82_200
  FUCHSIA_DEVICE_LOOKUP_ERROR(82_001, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_REBOOT_ERROR(82_002, ErrorType.INFRA_ISSUE),
  FUCHSIA_DEVICE_REBOOT_RECOVERY_ERROR(82_003, ErrorType.INFRA_ISSUE),
  FUCHSIA_DEVICE_HARDWARE_PAVE_UNSUPPORTED_ERROR(82_004, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_ARCH_PAVE_IMAGE_UNSUPPORTED_ERROR(82_005, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_PREPAVE_ERROR(82_006, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_DEVICE_PAVE_ERROR(82_007, ErrorType.DEPENDENCY_ISSUE),
  FUCHSIA_DEVICE_PAVE_IMAGE_NOT_FOUND_ERROR(82_008, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DECORATOR_WRONG_DEVICE_TYPE(82_009, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_FLUTTER_DRIVER_TILES_ERROR(82_010, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_FLUTTER_DRIVER_RUN_TEST_ERROR(82_011, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_UNDETERMINED_HARDWARE(82_012, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_SETUP_ERROR(82_013, ErrorType.INFRA_ISSUE),
  FUCHSIA_DECORATOR_SERVE_PACKAGE_ERROR(82_014, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_HARDWARE_PAVE_IMAGE_UNSUPPORTED_ERROR(82_015, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_SHELL_ERROR(82_016, ErrorType.INFRA_ISSUE),
  FUCHSIA_DEVICE_SSH_UNKNOWN_ERROR(82_017, ErrorType.INFRA_ISSUE),
  FUCHSIA_FLUTTER_DRIVER_MISSING_FAR_ERROR(82_018, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DEVICE_PRERUN_TEST_ERROR(82_019, ErrorType.INFRA_ISSUE),
  FUCHSIA_GRPC_GETSTATE_ERROR(82_020, ErrorType.INFRA_ISSUE),
  FUCHSIA_GRPC_RECOVER_ERROR(82_021, ErrorType.INFRA_ISSUE),
  FUCHSIA_GRPC_GETIPV6_ERROR(82_022, ErrorType.INFRA_ISSUE),
  FUCHSIA_DEVICE_POST_RUN_TEST_ERROR(82_023, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_GRPC_GETDEVICES_ERROR(82_024, ErrorType.INFRA_ISSUE),
  FUCHSIA_GRPC_SETUNKOWN_ERROR(82_025, ErrorType.INFRA_ISSUE),
  FUCHSIA_GRPC_STARTSERIAL_ERROR(82_026, ErrorType.INFRA_ISSUE),
  FUCHSIA_GRPC_STOPSERIAL_ERROR(82_027, ErrorType.INFRA_ISSUE),
  FUCHSIA_GRPC_GETTYPE_ERROR(82_028, ErrorType.INFRA_ISSUE),
  FUCHSIA_GRPC_HEALTHCHECK_ERROR(82_029, ErrorType.INFRA_ISSUE),
  FUCHSIA_DEVICE_NOT_IN_FASTBOOT_ERROR(82_030, ErrorType.DEPENDENCY_ISSUE),

  // Fuchsia drivers and runners: 82_201 - TBD
  FUCHSIA_PACKAGE_RUNNER_WRITE_LOG_ERROR(82_201, ErrorType.INFRA_ISSUE),
  FUCHSIA_PACKAGE_RUNNER_RUN_PACKAGE_ERROR(82_202, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_PACKAGE_TEST_FAIL(82_203, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_PACKAGE_RUNNER_RUN_CC_PACKAGE_ERROR(82_204, ErrorType.INFRA_ISSUE),
  FUCHSIA_SHELL_COMMAND_DECORATOR_ERROR(82_205, ErrorType.INFRA_ISSUE),
  FUCHSIA_PACKAGE_RUNNER_WRONG_DEVICE_STATE(82_206, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_FLUTTER_DRIVER_WRONG_DEVICE_STATE(82_207, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_PAVE_DECORATOR_INVALID_MANIFEST_FILE_ERROR(82_208, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_SDK_INVALID_MANIFEST_CONTENT_ERROR(82_209, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DART_BIN_NOT_FOUND(82_210, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DART_TEST_SNAPSHOT_NOT_FOUND(82_211, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DART_TEST_FAILURE(82_212, ErrorType.CUSTOMER_ISSUE),
  FUCHSIA_DART_TEST_SNAPSHOT_RUNNER_ERROR(82_213, ErrorType.INFRA_ISSUE),

  // TestTopBox: 82_801 - 82_900
  TTB_LAB_SERVER_CONFIG_ERROR(82_801, ErrorType.CUSTOMER_ISSUE),
  TTB_INVALID_DEVICE_MODEL(82_802, ErrorType.CUSTOMER_ISSUE),
  TTB_TEST_FAILURE(82_803, ErrorType.CUSTOMER_ISSUE),
  TTB_TEST_ERROR(82_804, ErrorType.INFRA_ISSUE),

  // Nest Devices: 82_901 ~ 83_400
  // Nest Detector: 82_901 ~ 83_000
  NEST_DM_DETECTOR_ERROR(82_901, ErrorType.INFRA_ISSUE),

  // Nest device management: 83_001 ~ 83_100
  NEST_DEVICE_HEALTH_CHECK_ERROR(83_001, ErrorType.INFRA_ISSUE),
  NEST_DEVICE_CONNECTION_ERROR(83_002, ErrorType.INFRA_ISSUE),

  // NoOpDriver: 83_401 ~ 83_420
  NO_OP_DRIVER_NON_PASSING_RESULT_SET_BY_MESSAGE(83_401, ErrorType.CUSTOMER_ISSUE),
  NO_OP_DRIVER_NON_PASSING_RESULT_SET_BY_PARAM(83_402, ErrorType.CUSTOMER_ISSUE),

  // Available: 83_421 ~ 83_500

  // Hermetic Server: 83_501 ~ 83_600
  HERMETIC_SERVER_GENERAL_ERROR(83_501, ErrorType.CUSTOMER_ISSUE),
  HERMETIC_SERVER_LOG_ERROR(83_502, ErrorType.DEPENDENCY_ISSUE),
  HERMETIC_SERVER_DATA_ERROR(83_503, ErrorType.DEPENDENCY_ISSUE),
  HERMETIC_SERVER_BINARY_ERROR(83_504, ErrorType.DEPENDENCY_ISSUE),
  HERMETIC_SERVER_PORT_ERROR(83_505, ErrorType.DEPENDENCY_ISSUE),
  HERMETIC_SERVER_CERT_ERROR(83_506, ErrorType.DEPENDENCY_ISSUE),
  HERMETIC_SERVER_DECORATOR_ERROR(83_549, ErrorType.CUSTOMER_ISSUE),
  HERMETIC_FE_BINARY_ERROR(83_551, ErrorType.DEPENDENCY_ISSUE),
  HERMETIC_FE_PROXY_ERROR(83_552, ErrorType.DEPENDENCY_ISSUE),
  HERMETIC_FE_DECORATOR_ERROR(83_599, ErrorType.CUSTOMER_ISSUE),

  // KaiOS: 83_601 ~ 83_800
  KAIOS_DEVICE_PORT_FORWARD_ERROR(83_601, ErrorType.INFRA_ISSUE),
  KAIOS_DEVICE_APP_INSTALLATION_ERROR(83_602, ErrorType.INFRA_ISSUE),
  KAIOS_DEVICE_APP_LAUNCH_ERROR(83_603, ErrorType.INFRA_ISSUE),
  KAIOS_DEVICE_APP_CLOSE_ERROR(83_604, ErrorType.INFRA_ISSUE),
  KAIOS_DEVICE_APP_UNINSTALL_ERROR(83_605, ErrorType.INFRA_ISSUE),
  KAIOS_DEVICE_MESSAGE_PARSING_ERROR(83_606, ErrorType.INFRA_ISSUE),
  KAIOS_DEVICE_READING_MESSAGE_FROM_DEVICE_FAILED(83_607, ErrorType.INFRA_ISSUE),
  KAIOS_DEVICE_FAILED_TO_RETRIEVE_WEBAPPS_ACTOR(83_608, ErrorType.INFRA_ISSUE),
  KAIOS_DEVICE_INSTALL_REQUEST_FAILED(83_609, ErrorType.INFRA_ISSUE),
  KAIOS_DEVICE_UNINSTALL_REQUEST_FAILED(83_610, ErrorType.INFRA_ISSUE),
  KAIOS_DEVICE_LAUNCH_REQUEST_FAILED(83_611, ErrorType.INFRA_ISSUE),
  KAIOS_DEVICE_CLOSE_REQUEST_FAILED(83_612, ErrorType.INFRA_ISSUE),
  KAIOS_DEVICE_KAIOS_PROPERTY_DETECT_IN_DISPATCHER_FAILED(83_613, ErrorType.INFRA_ISSUE),
  KAIOS_DEVICE_NO_WEBAPPS_ACTORS_ERROR(83_614, ErrorType.INFRA_ISSUE),
  KAIOS_DEVICE_UNABLE_TO_LOCATE_GECKODRIVER(83_615, ErrorType.INFRA_ISSUE),
  KAIOS_DEVICE_NO_GECKODRIVER_AVAILABLE_FOR_SERVER_PLATFORM(83_616, ErrorType.INFRA_ISSUE),
  KAIOS_DEVICE_COMMAND_EXE_ERROR(83_617, ErrorType.CUSTOMER_ISSUE),

  // ACID remote driver: 83_801 ~ 83_900
  ACID_REMOTE_DEVICE_TYPE_NO_SUPPORT_ERROR(83_801, ErrorType.CUSTOMER_ISSUE),
  ACID_REMOTE_ANDROID_UNABLE_RECONNECT_ERROR(83_802, ErrorType.INFRA_ISSUE),
  ACID_REMOTE_SCRCPY_KILL_FAIL_ERROR(83_803, ErrorType.INFRA_ISSUE),
  ACID_REMOTE_DRIVER_EXECUTE_FAIL(83_804, ErrorType.INFRA_ISSUE),
  ACID_REMOTE_DRIVER_SCRCPY_START_FAIL(83_805, ErrorType.INFRA_ISSUE),
  ACID_REMOTE_DRIVER_RECONNECT_WAIT_FOR_DEVICE_ERROR(83_806, ErrorType.INFRA_ISSUE),
  ACID_REMOTE_DRIVER_RESTART_RTC_INTERRUPTED(83_807, ErrorType.INFRA_ISSUE),

  // Embedded Linux Devices: 83_901 ~ 84_400
  EMBEDDED_LINUX_UTIL_REMOVE_FILE_OR_DIR_ERROR(83_901, ErrorType.INFRA_ISSUE),
  EMBEDDED_LINUX_UTIL_MAKE_DIRECTORY_ERROR(83_902, ErrorType.INFRA_ISSUE),
  EMBEDDED_LINUX_UTIL_RUN_NATIVE_BIN_ERROR(83_903, ErrorType.INFRA_ISSUE),
  EMBEDDED_LINUX_UTIL_SET_PERMISSION_ERROR(83_904, ErrorType.INFRA_ISSUE),
  EMBEDDED_LINUX_NATIVE_BIN_DRIVER_RUN_BINARY_ERROR(83_905, ErrorType.INFRA_ISSUE),
  EMBEDDED_LINUX_FILE_PUSHER_DECORATOR_DELETE_FILE_ERROR(83_906, ErrorType.INFRA_ISSUE),
  EMBEDDED_LINUX_FILE_PULLER_DECORATOR_OUTPUT_FILE_NOT_FOUND(83_907, ErrorType.INFRA_ISSUE),
  EMBEDDED_LINUX_SHELL_COMMAND_EXECUTION_ERROR(83_908, ErrorType.INFRA_ISSUE),

  // Generic runner: 84_401 - 84_500
  GENERIC_RUNNER_DRIVER_PROCESS_ERROR(84_401, ErrorType.UNDETERMINED),
  GENERIC_RUNNER_DRIVER_EXIT_NON_ZERO(84_402, ErrorType.CUSTOMER_ISSUE),
  GENERIC_RUNNER_DRIVER_PARAM_SIGNAL_FAILURE_NOT_SET(84_403, ErrorType.CUSTOMER_ISSUE),
  GENERIC_RUNNER_DRIVER_OUTPUT_CONTAINS_PARAM_SIGNAL_FAILURE(84_404, ErrorType.CUSTOMER_ISSUE),
  GENERIC_RUNNER_DRIVER_ERROR(84_405, ErrorType.CUSTOMER_ISSUE),

  // TestBeds: 84_501 - 84_600
  TESTBED_CONFIG_TESTBED_ID_NOT_EXIST_ERROR(84_501, ErrorType.CUSTOMER_ISSUE),
  TESTBED_CONFIG_SUBDEVICE_NOT_EXIST_ERROR(84_502, ErrorType.CUSTOMER_ISSUE),
  TESTBED_CONFIG_TESTBED_SUBDEVICE_SAME_NAME_ERROR(84_503, ErrorType.CUSTOMER_ISSUE),
  TESTBED_PARSING_TYPE_NOT_EXIST_ERROR(84_504, ErrorType.CUSTOMER_ISSUE),
  TESTBED_PARSING_ID_NOT_EXIST_ERROR(84_505, ErrorType.CUSTOMER_ISSUE),
  TESTBED_PARSING_NAME_NOT_EXIST_ERROR(84_506, ErrorType.CUSTOMER_ISSUE),
  TESTBED_PARSING_DEVICE_NOT_EXIST_ERROR(84_507, ErrorType.CUSTOMER_ISSUE),
  TESTBED_PARSING_DEVICE_KEY_NOT_EXIST_ERROR(84_508, ErrorType.CUSTOMER_ISSUE),
  TESTBED_CONFIG_SUBDEVICE_ID_EMPTY_ERROR(84_509, ErrorType.CUSTOMER_ISSUE),
  TESTBED_YAML_PARSING_ERROR(84_510, ErrorType.CUSTOMER_ISSUE),
  TESTBED_CONFIG_DUPLICATE_ID_ERROR(84_511, ErrorType.CUSTOMER_ISSUE),
  TESTBED_DEVICE_DECORATOR_NOT_COMPATIBLE_ERROR(84_512, ErrorType.CUSTOMER_ISSUE),
  TESTBED_DEVICE_DECORATOR_SETUP_ERROR(84_513, ErrorType.CUSTOMER_ISSUE),

  // Maneki (part 1): 84_601 ~ 84_700
  MANEKI_MISSING_CONFIG(84_601, ErrorType.INFRA_ISSUE),
  MANEKI_INVALID_CONFIG(84_602, ErrorType.INFRA_ISSUE),
  MANEKI_TEST_START_FAILURE(84_603, ErrorType.CUSTOMER_ISSUE),
  MANEKI_TEST_FAILURE(84_604, ErrorType.CUSTOMER_ISSUE),
  MANEKI_TEST_TIMEOUT(84_605, ErrorType.CUSTOMER_ISSUE),
  MANEKI_COMMAND_ERROR(84_606, ErrorType.CUSTOMER_ISSUE),
  MANEKI_GET_IP_FROM_MAC_ADDR_ERROR(84_607, ErrorType.CUSTOMER_ISSUE),
  MANEKI_YTS_DRIVER_MISSING_DIAL_ADDRESS_ERROR(84_608, ErrorType.INFRA_ISSUE),
  MANEKI_YTS_DRIVER_NO_TEST_RUN(84_609, ErrorType.CUSTOMER_ISSUE),
  MANEKI_YTS_CLI_LAUNCH_CMD_FAILED(84_610, ErrorType.CUSTOMER_ISSUE),
  MANEKI_YTS_CLI_TEST_FAILED(84_611, ErrorType.CUSTOMER_ISSUE),
  MANEKI_SSH_INVALID_COMMAND_ERROR(84_612, ErrorType.CUSTOMER_ISSUE),
  MANEKI_SSH_INVALID_ADDRESS_ERROR(84_613, ErrorType.CUSTOMER_ISSUE),
  MANEKI_SSH_COMMAND_FAILED(84_614, ErrorType.CUSTOMER_ISSUE),
  MANEKI_SCP_INVALID_ADDRESS_ERROR(84_615, ErrorType.CUSTOMER_ISSUE),
  MANEKI_DEVICE_PUSH_FILE_NOT_IMPLEMENTED(84_616, ErrorType.INFRA_ISSUE),
  MANEKI_INVALID_RASPI_DEVICE_UNKNOWN_GENERATION_ERROR(84_617, ErrorType.INFRA_ISSUE),
  MANEKI_INVALID_RASPI_DEVICE_PARSE_MODEL_ERROR(84_618, ErrorType.INFRA_ISSUE),
  MANEKI_INVALID_RASPI_DEVICE_UNKNOWN_MODEL_ERROR(84_619, ErrorType.INFRA_ISSUE),
  MANEKI_INVALID_RASPI_DEVICE_UNKNOWN_VERSION_ERROR(84_620, ErrorType.INFRA_ISSUE),
  MANEKI_INVALID_RASPI_DEVICE_UNKNOWN_CPU_FREQ_ERROR(84_621, ErrorType.INFRA_ISSUE),
  MANEKI_INVALID_RASPI_DEVICE_UNKNOWN_NUM_CPUS_ERROR(84_622, ErrorType.INFRA_ISSUE),
  MANEKI_RASPBERRY_PI_PRE_RUN_TEST_CLEAN_PROCESS_ERROR(84_623, ErrorType.INFRA_ISSUE),
  MANEKI_RASPBERRY_PI_PRE_RUN_TEST_CLEAN_HOME_DIRECTORY_ERROR(84_624, ErrorType.INFRA_ISSUE),
  MANEKI_GENERIC_DEVICE_ID_NOT_FOUND_IN_CONFIG(84_625, ErrorType.INFRA_ISSUE),
  MANEKI_UTIL_SELECTOR_INVALID_DEVICE_TYPE(84_626, ErrorType.CUSTOMER_ISSUE),
  MANEKI_INVALID_TEST_TYPE(84_627, ErrorType.CUSTOMER_ISSUE),
  MANEKI_INVALID_CONFIG_GENERIC_DEVICE_ADDRESS_MISSING(84_628, ErrorType.INFRA_ISSUE),
  MANEKI_ANDROID_IP_CMD_ERROR(84_629, ErrorType.INFRA_ISSUE),
  MANEKI_INVALID_CONFIG_RASPI_DEVICE_ADDRESS_MISSING(84_630, ErrorType.INFRA_ISSUE),
  MANEKI_DEVICE_LAUNCHER_PLUGIN_CMD_ERROR(84_631, ErrorType.INFRA_ISSUE),
  MANEKI_DEVICE_LAUNCHER_PLUGIN_YT_FAILED_TO_LAUNCH(84_632, ErrorType.INFRA_ISSUE),
  MANEKI_DEVICE_LAUNCHER_PLUGIN_LAUNCHER_NOT_FOUND(84_633, ErrorType.CUSTOMER_ISSUE),
  MANEKI_DEVICE_LAUNCHER_PLUGIN_EVALUATOR_FAILURE(84_634, ErrorType.INFRA_ISSUE),
  MANEKI_DEVICE_SERVER_LAUNCHER_PLUGIN_CMD_ERROR(84_635, ErrorType.INFRA_ISSUE),
  MANEKI_DEVICE_SERVER_LAUNCHER_PLUGIN_YT_FAILED_TO_LAUNCH(84_636, ErrorType.INFRA_ISSUE),
  MANEKI_DEVICE_SERVER_LAUNCHER_PLUGIN_LAUNCHER_NOT_FOUND(84_637, ErrorType.CUSTOMER_ISSUE),
  MANEKI_RASPBERRY_PI_PRE_RUN_TEST_CLEAN_TMP_DIRECTORY_ERROR(84_638, ErrorType.INFRA_ISSUE),
  MANEKI_ANDROID_CLEAN_TMP_DIRECTORY_ERROR(84_639, ErrorType.INFRA_ISSUE),
  MANEKI_ANDROID_LIST_XML_FILES_ERROR(84_640, ErrorType.INFRA_ISSUE),
  MANEKI_ANDROID_COPY_XML_FILE_TO_TMP_DIRECTORY_ERROR(84_641, ErrorType.INFRA_ISSUE),
  MANEKI_COMPUTE_FILE_SIZE_ERROR(84_642, ErrorType.INFRA_ISSUE),
  MANEKI_DEVICE_NOT_SUPPORT_PUSH_PULL_FILE(84_643, ErrorType.INFRA_ISSUE),
  MANEKI_XML_FILES_LISTING_ERROR(84_644, ErrorType.INFRA_ISSUE),
  MANEKI_NO_XML_FILES_FOUND(84_645, ErrorType.INFRA_ISSUE),
  MANEKI_TMP_DIR_ERROR_FOR_XML_FILES(84_646, ErrorType.INFRA_ISSUE),
  MANEKI_XML_FILES_DOWNLOAD_ERROR(84_647, ErrorType.INFRA_ISSUE),
  MANEKI_XML_FILES_SIZE_ERROR(84_648, ErrorType.INFRA_ISSUE),
  MANEKI_XML_FILES_TOO_LARGE(84_649, ErrorType.INFRA_ISSUE),
  MANEKI_XML_FILES_PARSING_ERROR(84_650, ErrorType.INFRA_ISSUE),
  MANEKI_ANDROID_DEVICE_INVALID_ABI_DIMENSION(84_651, ErrorType.INFRA_ISSUE),
  MANEKI_ANDROID_DEVICE_CHECK_APP_INSTALLED_FAILED(84_652, ErrorType.INFRA_ISSUE),
  MANEKI_INVALID_CONFIG_RASPI_DEVICE_ID_MISSING(84_653, ErrorType.INFRA_ISSUE),
  MANEKI_ANDROID_DEVICE_GET_DEVICE_ADDRESS_PARAMS_ERROR(84_654, ErrorType.INFRA_ISSUE),
  MANEKI_YTS_DRIVER_OPTIONAL_TEST_FAILED(84_655, ErrorType.CUSTOMER_ISSUE),
  MANEKI_YTS_DRIVER_TEST_FAILED_OTHER(84_656, ErrorType.CUSTOMER_ISSUE),
  MANEKI_YTS_DRIVER_XML_FILES_PARSING_ERROR(84_657, ErrorType.INFRA_ISSUE),
  MANEKI_YTS_CLI_AGENT_URL_REQUIRED_FOR_MLOADER(84_658, ErrorType.CUSTOMER_ISSUE),
  MANEKI_YTS_CLI_JSONREPORT_FILE_MISSING(84_659, ErrorType.INFRA_ISSUE),
  MANEKI_YTS_CLI_JSONREPORT_PARSING_ERROR(84_660, ErrorType.INFRA_ISSUE),
  MANEKI_YTS_CLI_XML_DOCUMENT_CREATION_ERROR(84_661, ErrorType.INFRA_ISSUE),
  MANEKI_YTS_CLI_XML_FILE_CREATION_ERROR(84_662, ErrorType.INFRA_ISSUE),
  MANEKI_YTS_CLI_XML_TRANSFORM_ERROR(84_663, ErrorType.INFRA_ISSUE),
  MANEKI_YTS_CLI_XML_FILE_WRITE_ERROR(84_664, ErrorType.INFRA_ISSUE),
  MANEKI_YTS_CLI_IDENTICAL_TEST_CASE_ERROR(84_665, ErrorType.INFRA_ISSUE),
  MANEKI_FAILED_XML_FILE_CREATION_ERROR(84_666, ErrorType.INFRA_ISSUE),
  MANEKI_XML_FILE_CANNOT_BE_PARSED_ERROR(84_667, ErrorType.CUSTOMER_ISSUE),
  MANEKI_XML_FILE_UNEXPECTED_TOP_NODE_ERROR(84_668, ErrorType.CUSTOMER_ISSUE),
  MANEKI_FAILED_XML_DOCUMENT_CREATION_ERROR(84_669, ErrorType.CUSTOMER_ISSUE),
  MANEKI_FAILED_XML_FILE_WRITE_ERROR(84_670, ErrorType.CUSTOMER_ISSUE),
  MANEKI_MISSING_WEB_RELEASE_CODE_ERROR(84_671, ErrorType.CUSTOMER_ISSUE),
  MANEKI_INVALID_OTA_AUTH_TOKEN_CLIENT(84_672, ErrorType.CUSTOMER_ISSUE),
  MANEKI_YTS_CLI_IP_NOT_FOUND(84_673, ErrorType.INFRA_ISSUE),
  MANEKI_YTS_CLI_ANDROID_CONNECTION_FAILED(84_674, ErrorType.INFRA_ISSUE),
  MANEKI_YTS_DRIVER_LAUNCH_CMD_FAILED(84_675, ErrorType.CUSTOMER_ISSUE),
  MANEKI_YTS_DRIVER_TEST_FAILED(84_676, ErrorType.CUSTOMER_ISSUE),
  MANEKI_DEVICE_PULL_FILE_NOT_IMPLEMENTED(84_677, ErrorType.INFRA_ISSUE),
  MANEKI_ANDROID_DEVICE_UNINSTALL_APP_FAILED(84_678, ErrorType.INFRA_ISSUE),
  MANEKI_GCS_ARCHIVE_NOT_FOUND(84_679, ErrorType.CUSTOMER_ISSUE),
  MANEKI_GSUTIL_OS_NOT_SUPPORTED(84_680, ErrorType.CUSTOMER_ISSUE),
  MANEKI_GCS_ARCHIVE_DOWNLOAD_FAILED(84_681, ErrorType.CUSTOMER_ISSUE),
  MANEKI_GCS_ARCHIVE_EXTRACTION_FAILED(84_682, ErrorType.CUSTOMER_ISSUE),
  MANEKI_GCS_LOCAL_ARCHIVE_NOT_FOUND(84_683, ErrorType.CUSTOMER_ISSUE),
  MANEKI_GCS_LOCAL_ARCHIVE_FOLDER_ALREADY_EXISTS(84_684, ErrorType.CUSTOMER_ISSUE),
  MANEKI_INVALID_GCS_ARCHIVE(84_685, ErrorType.CUSTOMER_ISSUE),
  MANEKI_LAUNCH_APP_NOT_IMPLEMENTED(84_686, ErrorType.CUSTOMER_ISSUE),
  MANEKI_KILL_APP_NOT_IMPLEMENTED(84_687, ErrorType.CUSTOMER_ISSUE),
  MANEKI_GET_COBALT_LOG_CALLBACKS_NOT_IMPLEMENTED(84_688, ErrorType.CUSTOMER_ISSUE),
  MANEKI_YOUTUBE_APP_INVALID_STATUS_BEFORE_LAUNCH(84_689, ErrorType.CUSTOMER_ISSUE),
  MANEKI_YOUTUBE_APP_CRASHED(84_690, ErrorType.CUSTOMER_ISSUE),
  MANEKI_YOUTUBE_APP_STOPPED_BEFORE_READY(84_691, ErrorType.CUSTOMER_ISSUE),
  MANEKI_YOUTUBE_APP_READY_TIMEOUT(84_692, ErrorType.CUSTOMER_ISSUE),
  MANEKI_CREATE_BUFFERED_WRITER_ERROR(84_693, ErrorType.CUSTOMER_ISSUE),
  MANEKI_ANDROID_LAUNCH_APP_FAILURE(84_694, ErrorType.CUSTOMER_ISSUE),
  MANEKI_ANDROID_LAUNCH_APP_SETUP_FAILURE(84_695, ErrorType.CUSTOMER_ISSUE),
  MANEKI_ANDROID_LAUNCH_APP_INVALID_ARGS(84_696, ErrorType.CUSTOMER_ISSUE),
  MANEKI_INVALID_CONFIG_WIN_DEVICE_ADDRESS_MISSING(84_697, ErrorType.INFRA_ISSUE),
  MANEKI_INVALID_CONFIG_WIN_HOST_ADDRESS_MISSING(84_698, ErrorType.INFRA_ISSUE),
  MANEKI_WIN_SSH_COMMAND_FAILED(84_699, ErrorType.CUSTOMER_ISSUE),
  MANEKI_WIN_SSH_INVALID_ADDRESS_ERROR(84_700, ErrorType.INFRA_ISSUE),
  // See Maneki part 2 below (86_501 ~ 86_600) for additional Maneki related error IDs.

  // Chopin 84_701 ~ 84_800
  CHOPIN_INVALID_CONFIG_FORMAT(84_701, ErrorType.DEPENDENCY_ISSUE),
  CHOPIN_FILE_HANDLING_ERROR(84_702, ErrorType.INFRA_ISSUE),
  CHOPIN_CREATE_DOMAIN_SOCKET_ERROR(84_703, ErrorType.INFRA_ISSUE),
  CHOPIN_EXECUTE_STEP_FAILED(84_704, ErrorType.CUSTOMER_ISSUE),
  CHOPIN_LAB_UNSUPPORTED(84_705, ErrorType.INFRA_ISSUE),

  // USB Devices: 84_801 ~ 84_900
  USB_DEVICE_INFO_PARSE_ERROR(84_801, ErrorType.INFRA_ISSUE),
  USB_DEVICE_LIBUSB_DETECTION_ERROR(84_802, ErrorType.INFRA_ISSUE),
  USB_DEVICE_LOCATION_DETECTION_ERROR(84_803, ErrorType.INFRA_ISSUE),

  // Djar: 84_901 ~ 85_000
  DJAR_SERVICE_STARTUP_ERROR(84_901, ErrorType.INFRA_ISSUE),

  // Vinson: 85_001 ~ 85_100
  VINSON_EXECUTE_ERROR(85_001, ErrorType.UNDETERMINED),
  VINSON_TEST_TIMEOUT(85_002, ErrorType.DEPENDENCY_ISSUE),
  VINSON_TEST_FAILURE(85_003, ErrorType.CUSTOMER_ISSUE),
  VINSON_DEVICE_NOT_SUPPORTED(85_004, ErrorType.CUSTOMER_ISSUE),
  VINSON_FILE_NOT_FOUND(85_005, ErrorType.INFRA_ISSUE),
  VINSON_FILE_TYPE_ERROR(85_006, ErrorType.INFRA_ISSUE),
  VINSON_UNZIP_ERROR(85_007, ErrorType.INFRA_ISSUE),
  VINSON_WIFI_CONFIG_CREATION_ERROR(85_008, ErrorType.INFRA_ISSUE),
  VINSON_TEST_ERROR(85_009, ErrorType.DEPENDENCY_ISSUE),

  // UTP Android Converters: 85_101 ~ 85_200
  UTP_ANDROID_REAL_DEVICE_CONVERTER_GET_DEVICE_PROVIDER_FILE_ERROR(85_101, ErrorType.INFRA_ISSUE),
  UTP_ANDROID_INSTRUMENTATION_CONVERTER_GET_RESOURCE_FILE_ERROR(85_102, ErrorType.INFRA_ISSUE),
  UTP_ANDROID_INSTRUMENTATION_FAILURE(85_103, ErrorType.UNDETERMINED),
  UTP_ANDROID_INSTRUMENTATION_RESULT_ERROR(85_104, ErrorType.CUSTOMER_ISSUE),
  UTP_ANDROID_INSTRUMENTATION_RESULT_FAILED(85_105, ErrorType.CUSTOMER_ISSUE),
  UTP_ANDROID_INSTRUMENTATION_RESULT_IGNORED(85_106, ErrorType.CUSTOMER_ISSUE),
  UTP_ANDROID_INSTRUMENTATION_NO_TEST_CASE(85_107, ErrorType.UNDETERMINED),
  UTP_ANDROID_INSTRUMENTATION_UI_OBJECT_NOT_FOUND(85_108, ErrorType.CUSTOMER_ISSUE),
  UTP_ANDROID_INSTRUMENTATION_NULL_POINTER_EXCEPTION(85_109, ErrorType.CUSTOMER_ISSUE),
  UTP_ANDROID_INSTRUMENTATION_PATTERN_SYNTAX_EXCEPTION(85_110, ErrorType.CUSTOMER_ISSUE),
  UTP_ANDROID_INSTRUMENTATION_NO_TEST_SUITE_RESULT(85_111, ErrorType.UNDETERMINED),
  UTP_ANDROID_INSTRUMENTATION_EMPTY_TEST_SUITE_RESULT(85_112, ErrorType.UNDETERMINED),
  UTP_ANDROID_INSTRUMENTATION_RESULT_SKIPPED(85_113, ErrorType.CUSTOMER_ISSUE),
  UTP_ANDROID_INSTRUMENTATION_UNRECOGNIZED_TEST_RESULT(85_114, ErrorType.UNDETERMINED),
  UTP_ANDROID_INSTRUMENTATION_UTP_RUNNER_EXIT_CODE_2(85_115, ErrorType.UNDETERMINED),
  UTP_ANDROID_ROBO_CONVERTER_GET_TEST_DRIVER_FILE_ERROR(85_116, ErrorType.INFRA_ISSUE),
  // UTP iOS Converters: 85_201 ~ 85_400
  UTP_IOS_REAL_DEVICE_CONVERTER_GET_DEVICE_PROVIDER_FILE_ERROR(85_201, ErrorType.INFRA_ISSUE),
  UTP_IOS_NO_TEST_SUITE_RESULT(85_202, ErrorType.UNDETERMINED),
  UTP_IOS_UNRECOGNIZED_TEST_RESULT(85_203, ErrorType.INFRA_ISSUE),
  UTP_IOS_RESULT_FAILED(85_204, ErrorType.CUSTOMER_ISSUE),
  UTP_IOS_RESULT_SKIPPED(85_205, ErrorType.CUSTOMER_ISSUE),
  UTP_IOS_RESULT_ERROR(85_206, ErrorType.CUSTOMER_ISSUE),
  UTP_IOS_TEST_CASE_CRASHED(85_207, ErrorType.CUSTOMER_ISSUE),
  UTP_IOS_TEST_CASE_TIMEOUT(85_208, ErrorType.CUSTOMER_ISSUE),
  UTP_IOS_UNSUPPORTED_TEST_TYPE(85_209, ErrorType.CUSTOMER_ISSUE),
  UTP_IOS_SPONGE_RESULT_ERROR(85_210, ErrorType.INFRA_ISSUE),
  UTP_IOS_TEST_GENERAL_ERROR(85_211, ErrorType.UNDETERMINED),
  UTP_IOS_TEST_DYLD_CRASHED(85_212, ErrorType.INFRA_ISSUE),
  UTP_IOS_TEST_RUNNER_FAILED(85_213, ErrorType.INFRA_ISSUE),
  UTP_IOS_LAUNCH_REQUEST_DENIED(85_214, ErrorType.INFRA_ISSUE),
  UTP_IOS_UNABLE_TO_FIND_DESTINATION_SPECIFIER(85_215, ErrorType.INFRA_ISSUE),
  UTP_IOS_UNABLE_TO_FIND_DEVICE_IDENTIFIER(85_216, ErrorType.INFRA_ISSUE),
  UTP_IOS_UNABLE_TO_FIND_DTSERVICEHUB(85_217, ErrorType.INFRA_ISSUE),
  UTP_IOS_DEVICE_NO_LONGER_CONNECTED(85_218, ErrorType.INFRA_ISSUE),
  UTP_IOS_VALID_PROVISIONING_PROFILE_NOT_FOUND(85_219, ErrorType.INFRA_ISSUE),
  UTP_IOS_TIMEOUT_WITH_SLOW_SIMULATOR_BOOT(85_220, ErrorType.INFRA_ISSUE),
  UTP_IOS_DTXPROXY_CHANNEL_ERROR(85_221, ErrorType.INFRA_ISSUE),
  UTP_IOS_FAILED_TO_LAUNCH_APP(85_222, ErrorType.INFRA_ISSUE),
  UTP_IOS_TEST_BUNDLE_FAILED_TO_START(85_223, ErrorType.INFRA_ISSUE),
  UTP_IOS_FAILED_TO_ACTIVATE_APP(85_224, ErrorType.INFRA_ISSUE),
  UTP_IOS_LAUNCH_PROGRESS_TIMEOUT(85_225, ErrorType.INFRA_ISSUE),
  UTP_IOS_AUTOMATION_SESSION_TIMEOUT(85_226, ErrorType.INFRA_ISSUE),
  UTP_IOS_SYSTEM_ALERT_INTERACTION_FAILURE(85_227, ErrorType.INFRA_ISSUE),
  UTP_IOS_NO_TEST_CASE_TO_RUN_ERROR(85_228, ErrorType.CUSTOMER_ISSUE),

  // Other UTP Converters: 85_401 ~ 86_000
  UTP_NO_OP_DEVICE_CONVERTER_GET_DEVICE_PROVIDER_FILE_ERROR(85_401, ErrorType.INFRA_ISSUE),
  UTP_NO_OP_DRIVER_CONVERTER_GET_TEST_DRIVER_FILE_ERROR(85_402, ErrorType.INFRA_ISSUE),

  // Fitbit: 86_001 ~ 86_100
  FITBIT_FDC_GET_RESOURCE_FILE_ERROR(86_001, ErrorType.DEPENDENCY_ISSUE),
  FITBIT_FDC_BINARY_NOT_FOUND(86_002, ErrorType.DEPENDENCY_ISSUE),
  FITBIT_FDC_PROCESS_AWAIT_ERROR(86_003, ErrorType.DEPENDENCY_ISSUE),
  FITBIT_CONNECTBIT_LAUNCH_ERROR(86_004, ErrorType.CUSTOMER_ISSUE),
  FITBIT_TESTBED_DEVICE_CONFIG_ERROR(86_005, ErrorType.CUSTOMER_ISSUE),
  FITBIT_FWUP_TIMEOUT(86_006, ErrorType.CUSTOMER_ISSUE),

  // OBS Driver:86_101 ~ 86_200
  OBSTEST_START_FAILURE(86_101, ErrorType.CUSTOMER_ISSUE),
  OBSTEST_FILE_NOT_FOUND(86_102, ErrorType.INFRA_ISSUE),

  // ACUITI_DECORATOR: 86_201 ~ 86_300
  ACUITI_DECORATOR_FILE_PERMISSION_ERROR(86_201, ErrorType.INFRA_ISSUE),
  ACUITI_DECORATOR_COMMAND_START_ERROR(86_202, ErrorType.INFRA_ISSUE),
  ACUITI_DECORATOR_UNKNOWNHOST(86_203, ErrorType.INFRA_ISSUE),

  // Video devices, e.g. Camera, WebCam: 86_301 ~ 86_400
  VIDEO_DEVICE_V4L_DETECTION_ERROR(86_301, ErrorType.INFRA_ISSUE),

  // LETI (Living Room Endpoints Testing Infrastructure): 86_401 ~ 86_500
  LETI_TEST_EXECUTION_ERROR(86_401, ErrorType.UNDETERMINED),

  // Maneki (part 2): 86_501 ~ 86_600
  MANEKI_WIN_SSH_INVALID_COMMAND_ERROR(86_501, ErrorType.CUSTOMER_ISSUE),
  MANEKI_WIN_SCP_INVALID_ADDRESS_ERROR(86_502, ErrorType.INFRA_ISSUE),
  MANEKI_WIN_SCP_COMMAND_FAILED(86_503, ErrorType.CUSTOMER_ISSUE),
  MANEKI_INVALID_COBALT_PATH(86_504, ErrorType.CUSTOMER_ISSUE),
  MANEKI_GCS_ARCHIVE_DOWNLOADER_PLUGIN_ERROR(86_505, ErrorType.CUSTOMER_ISSUE),
  MANEKI_GCS_ARCHIVE_DOWNLOADER_KEYSTORE_ERROR(86_506, ErrorType.CUSTOMER_ISSUE),
  MANEKI_YOUTUBE_LAUNCHER_PLUGIN_ERROR(86_507, ErrorType.CUSTOMER_ISSUE),
  MANEKI_YOUTUBE_LAUNCHER_DECORATOR_ERROR(86_508, ErrorType.CUSTOMER_ISSUE),

  // EVB Board device: 86_601 ~ 86_700
  EVB_BOARD_UTIL_DEVICE_DETECTION_ERROR(86_601, ErrorType.INFRA_ISSUE),

  // Vega Driver: 86_701 ~ 86_800
  VEGA_TEST_VALIDATOR_FILE_NOT_FOUND(86_701, ErrorType.CUSTOMER_ISSUE),
  VEGA_TEST_START_FAILURE(86_702, ErrorType.CUSTOMER_ISSUE),
  VEGA_TEST_FAILURE(86_703, ErrorType.CUSTOMER_ISSUE),
  VEGA_TEST_TIMEOUT(86_704, ErrorType.CUSTOMER_ISSUE),

  EXT_PLACE_HOLDER_TO_BE_RENAMED(100_000, ErrorType.UNDETERMINED);

  public static final int MIN_CODE = InfraErrorId.MAX_CODE + 1;
  public static final int MAX_CODE = 100_000;

  private final int code;
  private final ErrorType type;

  ExtErrorId(int code, ErrorType type) {
    Preconditions.checkArgument(code >= MIN_CODE);
    Preconditions.checkArgument(code <= MAX_CODE);
    Preconditions.checkArgument(type != ErrorType.UNCLASSIFIED);
    this.code = code;
    this.type = type;
  }

  @Override
  public int code() {
    return code;
  }

  @Override
  public ErrorType type() {
    return type;
  }

  @Override
  public String toString() {
    return ErrorIdFormatter.formatErrorId(this);
  }
}
