# proto-file: third_party/deviceinfra/src/java/com/google/wireless/qa/mobileharness/shared/proto/config.proto
# proto-message: mobileharness.shared.ApiConfig

composite_dimension {
  supported_dimension {
    name: "fake_dimension_name"
    value: "fake_dimension_value"
  }
  required_dimension: {
    name: "fake_required_dimension_name"
    value: "fake_required_dimension_value"
  }
}
