[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino

lib_deps =
    m5stack/M5Unified@0.2.13
    m5stack/M5GFX@0.2.19
    adafruit/Adafruit PWM Servo Driver Library@3.0.2
    adafruit/Adafruit BusIO@1.17.4

monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=3
