/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.wireless.qa.mobileharness.shared.constant;

import com.google.devtools.mobileharness.shared.util.flags.Flags;

/** Definition of the common file directories. */
public final class DirCommon {

  /** Prefix of all the directories generated by Mobile Harness servers. */
  public static final String DEFAULT_FOLDER_PREFIX = "mh_";

  /** Default file name pattern of the log files. */
  public static final String DEFAULT_LOG_FILE_NAME = "log%g.txt";

  /** See {@link GenDir#KEY_NAME_OF_TEST_GEN_FILE_DIR_RELATIVE_PATH}. */
  public static final String KEY_NAME_OF_TEST_GEN_FILE_DIR_RELATIVE_PATH =
      GenDir.KEY_NAME_OF_TEST_GEN_FILE_DIR_RELATIVE_PATH;

  /** The file name of the lab file metadata file. */
  public static final String LAB_FILE_METADATA_FILE_NAME = "lab_file_metadata.txtpb";

  /** Returns the public directory. */
  public static String getPublicDirRoot() {
    return Flags.instance().publicDir.getNonNull();
  }

  /** Returns the root of the temporary directory. */
  public static String getTempDirRoot() {
    return Flags.instance().tmpDirRoot.getNonNull();
  }

  private DirCommon() {}
}
