import {
  JobResult,
  JobStatus,
  TestResult,
  TestStatus,
} from '@deviceinfra/app/core/models/test_overview';
import {MockTestScenario} from '../models';

/** A mock test scenario representing a passed test. */
export const SCENARIO_TEST_PASSED: MockTestScenario = {
  id: '0b40e46b-dcf9-4609-b075-accaf98a74df',
  scenarioName: 'Passed Test',
  overview: {
    id: '0b40e46b-dcf9-4609-b075-accaf98a74df',
    name: 'com.google.codelab.mobileharness.android.hellomobileharness.HelloMobileHarnessTest#customTestArgs',
    status: TestStatus.TEST_STATUS_DONE,
    result: TestResult.TEST_RESULT_PASS,
    job: {
      id: 'd29b84c4-9e7f-4104-8cc8-c5d70bc9d481',
      name: 'hello_mobile_harness_test_on_mh',
      spongeLink: 'http://sponge2/b6a29d4c-6a37-4adc-8f7c-9a08c2d8043c',
      status: JobStatus.JOB_STATUS_DONE,
      result: JobResult.JOB_RESULT_PASS,
    },
    devices: {
      device: [
        {
          id: '23221FDF6001BT',
        },
      ],
    },
    host: {
      name: 'mt85-dm08.iad65.mtaas.example.com',
      ip: '10.11.48.179',
    },
    executionDetails: {
      user: 'qiupingf',
      actualUser: 'qiupingf',
      cloudLogLink:
        'https://pantheon.corp.example.com/logs/query;query=labels.test_id%3D0b40e46b-dcf9-4609-b075-accaf98a74df;timeRange=2026-07-22T09%3A27%3A44.892Z%2F2026-07-22T09%3A28%3A37.781Z?project=udcluster-logging',
      createTime: '2026-07-22T09:27:44.892Z',
      startTime: '2026-07-22T09:28:11.569Z',
      endTime: '2026-07-22T09:28:37.781Z',
      updateTime: '2026-07-22T09:28:37.781Z',
    },
    properties: {
      'dimension_baseband_version': 'g5123b-93368-211225-b-8029609',
      'dimension_screen_density': '420',
      'apk_size_com_google_codelab_mobileharness_android_hellomobileharness':
        '1180291 B',
      'dimension_release_version': '12',
      'dimension_storage_vendor': 'skhynix',
      'dimension_screen_size': '1080x2400',
      'dimension_hardware_sku': 'gb7n6',
      'android_instrumentation_execution_time_ms': '4151',
      'device_id_list': '23221FDF6001BT',
      'dimension_host_os_version': 'Debian GNU/Linux 13 (trixie)',
      'dimension_supports_adhoc': 'true',
      'dimension_os_build': 'SQ1D.220205.004',
      'main_package_name':
        'com.google.codelab.mobileharness.android.hellomobileharness',
      'dimension_firmware_version': 'mp1.0',
      'dimension_mcc_mnc': '',
      'allocated_devices_lst_signin_support': 'supported',
      'dimension_brand': 'google',
      'dimension_usb_accessory_mode': 'true',
      'dimension_host_os': 'Linux',
      'mh_ft_sent_file_num_without_cache': '2',
      'dimension_decorator':
        'AndroidLogcatMonitoringDecorator,AndroidPerfettoDecorator,AndroidLabTestSupportSettingsDecorator,AndroidDeviceSettingsDecorator,AndroidDumpSysDecorator,AcuitiDecorator,AndroidMartianProxyDecorator,AndroidCleanAppsDecorator,NoOpDecorator,AndroidSetPropDecorator,AndroidInstallAppPopupHelperDecorator,AndroidAppVersionDecorator,AndroidChopinDecorator,AndroidForceInstallGmsCoreDecorator,AndroidHermeticServerLauncherDecorator,AndroidNetworkSimulationDecorator,AndroidCrashMonitorDecorator,MaskImageDecorator,AndroidBatteryStatsDecorator,AndroidWebviewBridgeDecorator,AndroidDisplayDeviceInfoDecorator,AndroidSystemHealthMemoryDecorator,AndroidInstallAppsDecorator,AndroidDisableAppsDecorator,AndroidBugreportDecorator,AndroidFrameRenderDecorator,AndroidRandomRotateDecorator,AndroidGeoHttpProxyDecorator,AndroidLocationDecorator,AndroidAccountDecorator,AndroidAdbShellDecorator,AndroidStartAppsDecorator,AndroidFilePusherDecorator,AndroidLazyProxyDecorator,AndroidScreenshotDecorator,AndroidResMonitorDecorator,ManekiAndroidWebdriverPortForwardDecorator,AndroidPerfMonitorDecorator,AndroidFilePullerDecorator,AndroidInstallMainlineModulesDecorator,AndroidPermissionDecorator,AndroidKillProcessDecorator,AndroidStatsWakeLocksDecorator,AndroidOrientationDecorator,AndroidPhoneskySelfUpdateDecorator,AndroidDriveSimControllerDecorator,AndroidRuntimeStatsDecorator,AndroidExportStreamzDecorator,AndroidChromeInstallerDecorator,AndroidEmulatorVideoDecorator,AndroidGmsCoreConfigDecorator,AndroidTimeFDecorator,AndroidNuwaDecorator,AndroidSdVideoDecorator,AndroidHermeticWiredHttpProxyDecorator,AndroidNetworkActivityLoggingDecorator,AndroidHdVideoDecorator,AndroidSwitchUserDecorator,AndroidChromeWebViewInstallerDecorator,AndroidSwitchLanguageDecorator,AndroidLogCatDecorator,AndroidVRFramerateDecorator,ManekiYouTubeLauncherDecorator,AndroidPackageStatsDecorator,AndroidInstallMultipleApksDecorator',
      'dimension_battery_temperature': '29',
      'container_mode': 'false',
      'dimension_writable_external_storage': '/storage/emulated/0',
      'dimension_internal_storage_status': 'ok',
      'dimension_product_board': 'oriole',
      'mh_ft_get_file_num': '1',
      'dimension_driver':
        'AndroidForegroundServiceMessenger,ManekiTest,FlutterDriver,AndroidNuwa,AndroidNativeBin,AndroidMonkey,AndroidInstrumentation,AndroidGUnit,AndroidUIAutomator,AndroidTestLoopTest,AndroidChopin,AndroidMarmosetDriver,AcidRemoteDriver,YtsTest,MoblyTest,VegaTest,AndroidRoboTest,NoOpDriver,AndroidCopycatRemoteControlledMoblySnippetTest,AndroidHawkeyeBaselineExperiment,VinsonDriver',
      'start_delay_ms': '0',
      'dimension_abilist': 'arm64-v8a,armeabi-v7a,armeabi',
      'session_id': 'b6a29d4c-6a37-4adc-8f7c-9a08c2d8043c',
      'dimension_os_version': '31',
      'android_instrumentation_execution_time_sec': '4',
      'dimension_os': 'android',
      'dimension_color': 'blk',
      'dimension_iccids': '',
      'test_link_in_mhfe':
        'http://mobileharness-fe/testdetailview/d29b84c4-9e7f-4104-8cc8-c5d70bc9d481/0b40e46b-dcf9-4609-b075-accaf98a74df',
      'dimension_storage_capacity': '128gb',
      'mh_ft_get_time_without_cache': '2',
      'dimension_pool': 'shared',
      'allocation_requested_epoch_ms': '1784712465019',
      'dimension_internet': 'true',
      'dimension_device_form': 'physical',
      'dimension_total_memory': '7468 MB',
      'instrument_package':
        'com.google.codelab.mobileharness.android.hellomobileharness.test',
      'dimension_pool_name': 'DEFAULT',
      'mh_ft_send_file_num': '4',
      'android_instrumentation_install_apk_time_sec': '2',
      'version_name_com_google_codelab_mobileharness_android_hellomobileharness':
        '1.0',
      'dimension_host_version':
        'omnilab-lab-server-remoteandroid-20260629.01-RC00',
      'dimension_characteristics': 'nosdcard',
      'dimension_free_external_storage_percentage': '96.21%',
      'instrument_options': '',
      'dimension_free_external_storage': '106GB',
      'dimension_supports_gmscore': 'true',
      'dimension_serial': '23221FDF6001BT,23221fdf6001bt',
      'dimension_native_bridge': '0',
      'upload_genfiles_root_path':
        '/cnsexample/eh-d/home/mobileharness/gateway/20260722/s_b6a29d4c-6a37-4adc-8f7c-9a08c2d8043c/j_d29b84c4-9e7f-4104-8cc8-c5d70bc9d481/test_0b40e46b-dcf9-4609-b075-accaf98a74df',
      'dimension_hardware': 'oriole',
      'version_code_com_google_codelab_mobileharness_android_hellomobileharness':
        '1',
      'dimension_sim_card_info': 'NO_SIM',
      'dimension_model': 'pixel 6',
      'dimension_mtaas_device_checkin_group': 'true',
      'aut_id': 'com.google.codelab.mobileharness.android.hellomobileharness',
      'dimension_sdk_version': '31',
      'dimension_svelte_device': 'false',
      'file_transfer_client': 'CloudFileTransferClient',
      'dimension_secure_boot': 'production',
      'dimension_machine_type': 'physical_device',
      'remote_execution_time_ms': '25284',
      'mh_ft_send_file_size_total': '6205107',
      'dimension_soc_model': 'tensor',
      'dimension_kernel_release_number':
        '5.10.43-android12-9-00007-g9771767708df-ab8009062',
      'environment': 'PROD',
      'dimension_network_ssid': 'wl-ftl-mt85-1-5',
      'allocated_quota_pool': 'general-shared-pool',
      'dimension_widevine_security_level': 'L1',
      'dimension_rooted': 'false',
      'dimension_machine_hardware_name': 'aarch64',
      'dimension_build_alias': 'sq1d.220205.004',
      'dimension_lab_location': 'iad65',
      'device_done_epoch_ms': '1784712509860',
      'dimension_abi': 'arm64-v8a',
      'dimension_host_ip': '10.11.48.179',
      'dimension_hardware_ufs': '128gb,skhynix',
      'dimension_product_device': 'oriole',
      'version_name_com_google_android_gms': '26.25.32 (190400-944114241)',
      'dimension_sim_network_operator': 'NO_SIM',
      'dimension_device_class_name': 'AndroidRealDevice',
      'dimension_api_level': '31',
      'dimension_uuid': '23221FDF6001BT',
      'dimension_veritymode': 'enforcing',
      'remote_start_delay_ms': '1',
      'sponge_link_of_test':
        'http://sponge2/b6a29d4c-6a37-4adc-8f7c-9a08c2d8043c',
      'dimension_devicetype':
        'AndroidDevice,AndroidRealDevice,AndroidOnlineDevice',
      'dimension_ddr_vendor': 'samsung',
      '_hats_trigger_id_for_mh': 'v7fyRAaKM0iXoKhPGdD0X94YVmFW',
      'dimension_gms_version': '26.25.32 (190400-944114241)',
      '_test_engine_locator':
        'enable_cloud_rpc: \t true\ncloud_rpc_locator {\n  proxy_metadata {\n    endpoint: "lab_server_endpoint"\n    shard: "mt85-dm08.iad65.mtaas.example.com"\n  }\n  file_transfer_proxy_metadata {\n    endpoint: "lab_cloud_file_transfer_endpoint"\n    shard: "mt85-dm08.iad65.mtaas.example.com"\n  }\n}\ngrpc_locator {\n  grpc_target: "dns:///mt85-dm08.iad65.mtaas.example.com:9994"\n  host_name: "mt85-dm08.iad65.mtaas.example.com"\n  grpc_port: 9994\n  host_ip: "10.11.48.179"\n}\nenable_grpc: true\n',
      'dimension_sign': 'release-keys',
      'allocation_time_ms': '26549',
      'allocation_time_sec': '26',
      'exec_mode': 'remote',
      'actual_user': 'qiupingf',
      'dimension_location_type': 'not_in_china',
      'master_scheduler_latency_sec': '0',
      'dimension_lab_type': 'core',
      'gen_file_in_cnsexample_0':
        '/cnsexample/eh-d/home/mobileharness/gateway/20260722/s_b6a29d4c-6a37-4adc-8f7c-9a08c2d8043c/j_d29b84c4-9e7f-4104-8cc8-c5d70bc9d481/test_0b40e46b-dcf9-4609-b075-accaf98a74df/instrument.log',
      'dimension_num_cpus': '8',
      'gen_file_in_cnsexample_1':
        '/cnsexample/eh-d/home/mobileharness/gateway/20260722/s_b6a29d4c-6a37-4adc-8f7c-9a08c2d8043c/j_d29b84c4-9e7f-4104-8cc8-c5d70bc9d481/test_0b40e46b-dcf9-4609-b075-accaf98a74df/command_history.txt',
      'gen_file_in_cnsexample_2':
        '/cnsexample/eh-d/home/mobileharness/gateway/20260722/s_b6a29d4c-6a37-4adc-8f7c-9a08c2d8043c/j_d29b84c4-9e7f-4104-8cc8-c5d70bc9d481/test_0b40e46b-dcf9-4609-b075-accaf98a74df/test_output.txt',
      'mh_ft_get_time_total': '2',
      'run_as': 'qiupingf',
      'dimension_wifi_rssi': '-63',
      'dimension_free_internal_storage_percentage': '96.21%',
      'dimension_memory_class': '256m',
      'dimension_soc_rev': '3',
      'dimension_language': 'en',
      'dimension_network_address':
        'fe80::c8d0:bdff:fef6:ff58/64,2001:4860:1022:fe06:c8d0:bdff:fef6:ff58/64,2001:4860:1022:fe06:e211:7acd:836e:450/64,10.13.166.197/18',
      'dimension_communication_type': 'ADB',
      'dimension_dm_type': 'fusion',
      'dimension_feature':
        'com.google.android.feature.PIXEL_EXPERIENCE,android.hardware.nfc',
      'remote_test_engine_setup_time_ms': '0',
      'master_scheduler_latency_type': 'TEST_WAIT_FOR_DEVICE',
      'dimension_ddr_type': 'lpddr5',
      'dimension_codename': 'rel,oriole',
      'dimension_revision': 'mp1.0',
      'allocation_received_epoch_ms': '1784712491559',
      'dimension_build': 'sq1d.220205.004,SQ1D.220205.004',
      'dimension_device_supports_container': 'true',
      'mh_ft_get_file_size_total': '2189',
      'dimension_build_type': 'user',
      'android_instrumentation_test_end_epoch_ms': '1784712507600',
      'dimension_battery_level': '80',
      'android_inst_test_method_repeat_times': '1',
      'mh_ft_get_file_size_without_cache': '2189',
      'mh_ft_get_file_num_without_cache': '1',
      'dimension_manufacturer': 'google',
      'dimension_type': 'oriole',
      'dimension_host_name': 'mt85-dm08.iad65.mtaas.example.com',
      'dimension_launcher_gel': 'false',
      'android_instrumentation_install_apk_time_ms': '2648',
      'dimension_external_storage_status': 'ok',
      'is_final_attempt': 'true',
      'version_code_com_google_android_gms': '262532029',
      'mh_ft_send_time_total': '6',
      'android_instrumentation_log_filenames': 'instrument.log',
      'dimension_sim_state': 'absent',
      'hybrid_utp_summary_incompatible_reason': 'not_in_allowlist',
      'dimension_ddr_size': '8gb',
      'mh_ft_send_file_size_without_cache': '4888',
      'dimension_lab_supports_container': 'true',
      'dimension_screenshot_able': 'true',
      'dimension_free_internal_storage': '106GB',
      'dimension_gmscore_signature': '98deb0ca',
      'dimension_launcher_3': 'false',
      'dimension_launcher_1': 'false',
      'dimension_release_version_major': '12',
      'mh_ft_send_time_without_cache': '2',
      'master_central_suspended_duration_sec': '0',
      'instrument_runner': 'androidx.test.runner.AndroidJUnitRunner',
      'dimension_incremental_build': '8151327',
      '_is_run_in_dm': 'false',
      'android_instrumentation_test_start_epoch_ms': '1784712505707',
      'dimension_device': 'oriole',
      '_hats_survey_id_for_mh': '4nHy36U93YzWa1wBUpMn6v',
      'dimension_preview_sdk_version': '0',
      'dimension_bluetooth_mac_address': 'dc:e5:5b:3c:9e:5a',
      'decorator_run_time_ms_AndroidLogCatDecorator': '10564',
      'dimension_battery_status': 'ok',
      'dimension_locale': 'en-us',
      'lab_test_gen_file_dir':
        '/var/log/mh_lab_gen_files/d29b84c4-9e7f-4104-8cc8-c5d70bc9d481/test_0b40e46b-dcf9-4609-b075-accaf98a74df',
      'dimension_is_gki_kernel': 'true',
    },
    timingBreakdown: {
      createTime: '2026-07-22T09:27:44.892Z',
      startTime: '2026-07-22T09:28:11.569Z',
      endTime: '2026-07-22T09:28:37.781Z',
      stages: [
        {
          name: 'Pre-run Test',
          tag: 'client',
          startTime: '2026-07-22T09:27:44.892Z',
          endTime: '2026-07-22T09:28:00.000Z',
        },
        {
          name: 'Run Test',
          tag: 'lab',
          startTime: '2026-07-22T09:28:11.569Z',
          endTime: '2026-07-22T09:28:37.781Z',
        },
      ],
    },
    troubleshooting: {},
  },
  log: '[10:11:15] Test started\n[10:11:18] Clicking button...\n[10:11:25] Assertion passed: Button text matches.\n[10:11:25] Test finished successfully.',
  cloudLogLink:
    'https://pantheon.corp.example.com/logs/query;query=labels.test_id%3D0b40e46b-dcf9-4609-b075-accaf98a74df;timeRange=2026-07-22T09%3A27%3A44.892Z%2F2026-07-22T09%3A28%3A37.781Z?project=udcluster-logging',
};
